packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  electron-winstaller: true
  esbuild: true
  protobufjs: false
  sharp: true
  vue-demi: true

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - sharp

patchedDependencies:
  dockview-core@7.0.2: patches/dockview-core@7.0.2.patch
  dockview-vue@7.0.2: patches/dockview-vue@7.0.2.patch
