// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/agent/turn/turnpb/turn.proto

package turnpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonRequest) Reset() {
	*x = JsonRequest{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonRequest) ProtoMessage() {}

func (x *JsonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonRequest.ProtoReflect.Descriptor instead.
func (*JsonRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{0}
}

func (x *JsonRequest) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{1}
}

func (x *JsonResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*RunRequest_StartJson
	//	*RunRequest_InjectJson
	//	*RunRequest_OutboundAssetsJson
	//	*RunRequest_Cancel
	Body          isRunRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetBody() isRunRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RunRequest) GetStartJson() []byte {
	if x != nil {
		if x, ok := x.Body.(*RunRequest_StartJson); ok {
			return x.StartJson
		}
	}
	return nil
}

func (x *RunRequest) GetInjectJson() []byte {
	if x != nil {
		if x, ok := x.Body.(*RunRequest_InjectJson); ok {
			return x.InjectJson
		}
	}
	return nil
}

func (x *RunRequest) GetOutboundAssetsJson() []byte {
	if x != nil {
		if x, ok := x.Body.(*RunRequest_OutboundAssetsJson); ok {
			return x.OutboundAssetsJson
		}
	}
	return nil
}

func (x *RunRequest) GetCancel() bool {
	if x != nil {
		if x, ok := x.Body.(*RunRequest_Cancel); ok {
			return x.Cancel
		}
	}
	return false
}

type isRunRequest_Body interface {
	isRunRequest_Body()
}

type RunRequest_StartJson struct {
	StartJson []byte `protobuf:"bytes,1,opt,name=start_json,json=startJson,proto3,oneof"`
}

type RunRequest_InjectJson struct {
	InjectJson []byte `protobuf:"bytes,2,opt,name=inject_json,json=injectJson,proto3,oneof"`
}

type RunRequest_OutboundAssetsJson struct {
	OutboundAssetsJson []byte `protobuf:"bytes,3,opt,name=outbound_assets_json,json=outboundAssetsJson,proto3,oneof"`
}

type RunRequest_Cancel struct {
	Cancel bool `protobuf:"varint,4,opt,name=cancel,proto3,oneof"`
}

func (*RunRequest_StartJson) isRunRequest_Body() {}

func (*RunRequest_InjectJson) isRunRequest_Body() {}

func (*RunRequest_OutboundAssetsJson) isRunRequest_Body() {}

func (*RunRequest_Cancel) isRunRequest_Body() {}

type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*RunResponse_Started
	//	*RunResponse_Event
	//	*RunResponse_Completed
	Body          isRunResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{3}
}

func (x *RunResponse) GetBody() isRunResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RunResponse) GetStarted() *Started {
	if x != nil {
		if x, ok := x.Body.(*RunResponse_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *RunResponse) GetEvent() *EventResponse {
	if x != nil {
		if x, ok := x.Body.(*RunResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunResponse) GetCompleted() *Completed {
	if x != nil {
		if x, ok := x.Body.(*RunResponse_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

type isRunResponse_Body interface {
	isRunResponse_Body()
}

type RunResponse_Started struct {
	Started *Started `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type RunResponse_Event struct {
	Event *EventResponse `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type RunResponse_Completed struct {
	Completed *Completed `protobuf:"bytes,3,opt,name=completed,proto3,oneof"`
}

func (*RunResponse_Started) isRunResponse_Body() {}

func (*RunResponse_Event) isRunResponse_Body() {}

func (*RunResponse_Completed) isRunResponse_Body() {}

type Started struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Started) Reset() {
	*x = Started{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{4}
}

func (x *Started) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{5}
}

func (x *EventResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EventResponse) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *EventResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EventResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EventResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Completed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completed) Reset() {
	*x = Completed{}
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completed) ProtoMessage() {}

func (x *Completed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_agent_turn_turnpb_turn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completed.ProtoReflect.Descriptor instead.
func (*Completed) Descriptor() ([]byte, []int) {
	return file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP(), []int{6}
}

var File_internal_agent_turn_turnpb_turn_proto protoreflect.FileDescriptor

const file_internal_agent_turn_turnpb_turn_proto_rawDesc = "" +
	"\n" +
	"%internal/agent/turn/turnpb/turn.proto\x12\rmemoh.turn.v1\"!\n" +
	"\vJsonRequest\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\"\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\xa6\x01\n" +
	"\n" +
	"RunRequest\x12\x1f\n" +
	"\n" +
	"start_json\x18\x01 \x01(\fH\x00R\tstartJson\x12!\n" +
	"\vinject_json\x18\x02 \x01(\fH\x00R\n" +
	"injectJson\x122\n" +
	"\x14outbound_assets_json\x18\x03 \x01(\fH\x00R\x12outboundAssetsJson\x12\x18\n" +
	"\x06cancel\x18\x04 \x01(\bH\x00R\x06cancelB\x06\n" +
	"\x04body\"\xb9\x01\n" +
	"\vRunResponse\x122\n" +
	"\astarted\x18\x01 \x01(\v2\x16.memoh.turn.v1.StartedH\x00R\astarted\x124\n" +
	"\x05event\x18\x02 \x01(\v2\x1c.memoh.turn.v1.EventResponseH\x00R\x05event\x128\n" +
	"\tcompleted\x18\x03 \x01(\v2\x18.memoh.turn.v1.CompletedH\x00R\tcompletedB\x06\n" +
	"\x04body\" \n" +
	"\aStarted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x9e\x01\n" +
	"\rEventResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\v\n" +
	"\tCompleted2\x8d\x03\n" +
	"\vTurnService\x12C\n" +
	"\bStopTurn\x12\x1a.memoh.turn.v1.JsonRequest\x1a\x1b.memoh.turn.v1.JsonResponse\x12@\n" +
	"\x03Run\x12\x19.memoh.turn.v1.RunRequest\x1a\x1a.memoh.turn.v1.RunResponse(\x010\x01\x12Q\n" +
	"\x13RespondToolApproval\x12\x1a.memoh.turn.v1.JsonRequest\x1a\x1c.memoh.turn.v1.EventResponse0\x01\x12N\n" +
	"\x10RespondUserInput\x12\x1a.memoh.turn.v1.JsonRequest\x1a\x1c.memoh.turn.v1.EventResponse0\x01\x12T\n" +
	"\x19AdvancePlainTextUserInput\x12\x1a.memoh.turn.v1.JsonRequest\x1a\x1b.memoh.turn.v1.JsonResponseB6Z4github.com/felinics/memoh/internal/agent/turn/turnpbb\x06proto3"

var (
	file_internal_agent_turn_turnpb_turn_proto_rawDescOnce sync.Once
	file_internal_agent_turn_turnpb_turn_proto_rawDescData []byte
)

func file_internal_agent_turn_turnpb_turn_proto_rawDescGZIP() []byte {
	file_internal_agent_turn_turnpb_turn_proto_rawDescOnce.Do(func() {
		file_internal_agent_turn_turnpb_turn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_agent_turn_turnpb_turn_proto_rawDesc), len(file_internal_agent_turn_turnpb_turn_proto_rawDesc)))
	})
	return file_internal_agent_turn_turnpb_turn_proto_rawDescData
}

var file_internal_agent_turn_turnpb_turn_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_agent_turn_turnpb_turn_proto_goTypes = []any{
	(*JsonRequest)(nil),   // 0: memoh.turn.v1.JsonRequest
	(*JsonResponse)(nil),  // 1: memoh.turn.v1.JsonResponse
	(*RunRequest)(nil),    // 2: memoh.turn.v1.RunRequest
	(*RunResponse)(nil),   // 3: memoh.turn.v1.RunResponse
	(*Started)(nil),       // 4: memoh.turn.v1.Started
	(*EventResponse)(nil), // 5: memoh.turn.v1.EventResponse
	(*Completed)(nil),     // 6: memoh.turn.v1.Completed
}
var file_internal_agent_turn_turnpb_turn_proto_depIdxs = []int32{
	4, // 0: memoh.turn.v1.RunResponse.started:type_name -> memoh.turn.v1.Started
	5, // 1: memoh.turn.v1.RunResponse.event:type_name -> memoh.turn.v1.EventResponse
	6, // 2: memoh.turn.v1.RunResponse.completed:type_name -> memoh.turn.v1.Completed
	0, // 3: memoh.turn.v1.TurnService.StopTurn:input_type -> memoh.turn.v1.JsonRequest
	2, // 4: memoh.turn.v1.TurnService.Run:input_type -> memoh.turn.v1.RunRequest
	0, // 5: memoh.turn.v1.TurnService.RespondToolApproval:input_type -> memoh.turn.v1.JsonRequest
	0, // 6: memoh.turn.v1.TurnService.RespondUserInput:input_type -> memoh.turn.v1.JsonRequest
	0, // 7: memoh.turn.v1.TurnService.AdvancePlainTextUserInput:input_type -> memoh.turn.v1.JsonRequest
	1, // 8: memoh.turn.v1.TurnService.StopTurn:output_type -> memoh.turn.v1.JsonResponse
	3, // 9: memoh.turn.v1.TurnService.Run:output_type -> memoh.turn.v1.RunResponse
	5, // 10: memoh.turn.v1.TurnService.RespondToolApproval:output_type -> memoh.turn.v1.EventResponse
	5, // 11: memoh.turn.v1.TurnService.RespondUserInput:output_type -> memoh.turn.v1.EventResponse
	1, // 12: memoh.turn.v1.TurnService.AdvancePlainTextUserInput:output_type -> memoh.turn.v1.JsonResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_agent_turn_turnpb_turn_proto_init() }
func file_internal_agent_turn_turnpb_turn_proto_init() {
	if File_internal_agent_turn_turnpb_turn_proto != nil {
		return
	}
	file_internal_agent_turn_turnpb_turn_proto_msgTypes[2].OneofWrappers = []any{
		(*RunRequest_StartJson)(nil),
		(*RunRequest_InjectJson)(nil),
		(*RunRequest_OutboundAssetsJson)(nil),
		(*RunRequest_Cancel)(nil),
	}
	file_internal_agent_turn_turnpb_turn_proto_msgTypes[3].OneofWrappers = []any{
		(*RunResponse_Started)(nil),
		(*RunResponse_Event)(nil),
		(*RunResponse_Completed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_agent_turn_turnpb_turn_proto_rawDesc), len(file_internal_agent_turn_turnpb_turn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_agent_turn_turnpb_turn_proto_goTypes,
		DependencyIndexes: file_internal_agent_turn_turnpb_turn_proto_depIdxs,
		MessageInfos:      file_internal_agent_turn_turnpb_turn_proto_msgTypes,
	}.Build()
	File_internal_agent_turn_turnpb_turn_proto = out.File
	file_internal_agent_turn_turnpb_turn_proto_goTypes = nil
	file_internal_agent_turn_turnpb_turn_proto_depIdxs = nil
}
