// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: internal/agent/turn/turnpb/turn.proto

package turnpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TurnService_StopTurn_FullMethodName                  = "/memoh.turn.v1.TurnService/StopTurn"
	TurnService_Run_FullMethodName                       = "/memoh.turn.v1.TurnService/Run"
	TurnService_RespondToolApproval_FullMethodName       = "/memoh.turn.v1.TurnService/RespondToolApproval"
	TurnService_RespondUserInput_FullMethodName          = "/memoh.turn.v1.TurnService/RespondUserInput"
	TurnService_AdvancePlainTextUserInput_FullMethodName = "/memoh.turn.v1.TurnService/AdvancePlainTextUserInput"
)

// TurnServiceClient is the client API for TurnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TurnServiceClient interface {
	StopTurn(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunRequest, RunResponse], error)
	RespondToolApproval(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
	RespondUserInput(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
	AdvancePlainTextUserInput(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type turnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTurnServiceClient(cc grpc.ClientConnInterface) TurnServiceClient {
	return &turnServiceClient{cc}
}

func (c *turnServiceClient) StopTurn(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, TurnService_StopTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turnServiceClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunRequest, RunResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TurnService_ServiceDesc.Streams[0], TurnService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurnService_RunClient = grpc.BidiStreamingClient[RunRequest, RunResponse]

func (c *turnServiceClient) RespondToolApproval(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TurnService_ServiceDesc.Streams[1], TurnService_RespondToolApproval_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JsonRequest, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurnService_RespondToolApprovalClient = grpc.ServerStreamingClient[EventResponse]

func (c *turnServiceClient) RespondUserInput(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TurnService_ServiceDesc.Streams[2], TurnService_RespondUserInput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JsonRequest, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurnService_RespondUserInputClient = grpc.ServerStreamingClient[EventResponse]

func (c *turnServiceClient) AdvancePlainTextUserInput(ctx context.Context, in *JsonRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, TurnService_AdvancePlainTextUserInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurnServiceServer is the server API for TurnService service.
// All implementations must embed UnimplementedTurnServiceServer
// for forward compatibility.
type TurnServiceServer interface {
	StopTurn(context.Context, *JsonRequest) (*JsonResponse, error)
	Run(grpc.BidiStreamingServer[RunRequest, RunResponse]) error
	RespondToolApproval(*JsonRequest, grpc.ServerStreamingServer[EventResponse]) error
	RespondUserInput(*JsonRequest, grpc.ServerStreamingServer[EventResponse]) error
	AdvancePlainTextUserInput(context.Context, *JsonRequest) (*JsonResponse, error)
	mustEmbedUnimplementedTurnServiceServer()
}

// UnimplementedTurnServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTurnServiceServer struct{}

func (UnimplementedTurnServiceServer) StopTurn(context.Context, *JsonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTurn not implemented")
}
func (UnimplementedTurnServiceServer) Run(grpc.BidiStreamingServer[RunRequest, RunResponse]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedTurnServiceServer) RespondToolApproval(*JsonRequest, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method RespondToolApproval not implemented")
}
func (UnimplementedTurnServiceServer) RespondUserInput(*JsonRequest, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method RespondUserInput not implemented")
}
func (UnimplementedTurnServiceServer) AdvancePlainTextUserInput(context.Context, *JsonRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvancePlainTextUserInput not implemented")
}
func (UnimplementedTurnServiceServer) mustEmbedUnimplementedTurnServiceServer() {}
func (UnimplementedTurnServiceServer) testEmbeddedByValue()                     {}

// UnsafeTurnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurnServiceServer will
// result in compilation errors.
type UnsafeTurnServiceServer interface {
	mustEmbedUnimplementedTurnServiceServer()
}

func RegisterTurnServiceServer(s grpc.ServiceRegistrar, srv TurnServiceServer) {
	// If the following call panics, it indicates UnimplementedTurnServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TurnService_ServiceDesc, srv)
}

func _TurnService_StopTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServiceServer).StopTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurnService_StopTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServiceServer).StopTurn(ctx, req.(*JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurnService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TurnServiceServer).Run(&grpc.GenericServerStream[RunRequest, RunResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurnService_RunServer = grpc.BidiStreamingServer[RunRequest, RunResponse]

func _TurnService_RespondToolApproval_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JsonRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TurnServiceServer).RespondToolApproval(m, &grpc.GenericServerStream[JsonRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurnService_RespondToolApprovalServer = grpc.ServerStreamingServer[EventResponse]

func _TurnService_RespondUserInput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JsonRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TurnServiceServer).RespondUserInput(m, &grpc.GenericServerStream[JsonRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TurnService_RespondUserInputServer = grpc.ServerStreamingServer[EventResponse]

func _TurnService_AdvancePlainTextUserInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurnServiceServer).AdvancePlainTextUserInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TurnService_AdvancePlainTextUserInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurnServiceServer).AdvancePlainTextUserInput(ctx, req.(*JsonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TurnService_ServiceDesc is the grpc.ServiceDesc for TurnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TurnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoh.turn.v1.TurnService",
	HandlerType: (*TurnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopTurn",
			Handler:    _TurnService_StopTurn_Handler,
		},
		{
			MethodName: "AdvancePlainTextUserInput",
			Handler:    _TurnService_AdvancePlainTextUserInput_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _TurnService_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RespondToolApproval",
			Handler:       _TurnService_RespondToolApproval_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RespondUserInput",
			Handler:       _TurnService_RespondUserInput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/agent/turn/turnpb/turn.proto",
}
