// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearBotAgentCredential = `-- name: ClearBotAgentCredential :one
UPDATE bot_agents
SET agent_credential_id = NULL,
    updated_at = now()
WHERE bot_agents.bot_id = $1
  AND bot_agents.id = $2
  AND bot_agents.team_id = public.memoh_current_team_id()
  AND bot_agents.deleted_at IS NULL
  AND bot_agents.agent_credential_id IS NOT NULL
RETURNING (
    SELECT prev.agent_credential_id
    FROM bot_agents prev
    WHERE prev.id = bot_agents.id
) AS previous_credential_id
`

type ClearBotAgentCredentialParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	BotAgentID pgtype.UUID `json:"bot_agent_id"`
}

func (q *Queries) ClearBotAgentCredential(ctx context.Context, arg ClearBotAgentCredentialParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, clearBotAgentCredential, arg.BotID, arg.BotAgentID)
	var previous_credential_id pgtype.UUID
	err := row.Scan(&previous_credential_id)
	return previous_credential_id, err
}

const countBotAgentCredentialRefs = `-- name: CountBotAgentCredentialRefs :one
SELECT count(*) FROM bot_agents
WHERE agent_credential_id = $1
  AND team_id = public.memoh_current_team_id()
  AND deleted_at IS NULL
`

func (q *Queries) CountBotAgentCredentialRefs(ctx context.Context, agentCredentialID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBotAgentCredentialRefs, agentCredentialID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentCredential = `-- name: CreateAgentCredential :one
INSERT INTO agent_credentials (
    owner_user_id, provider, auth_kind, label,
    encrypted_payload, encryption_nonce, key_version,
    account_metadata, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
RETURNING id, team_id, owner_user_id, provider, auth_kind, label, encrypted_payload, encryption_nonce, key_version, account_metadata, expires_at, credential_version, revoked_at, created_at, updated_at
`

type CreateAgentCredentialParams struct {
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Provider         string             `json:"provider"`
	AuthKind         string             `json:"auth_kind"`
	Label            string             `json:"label"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	EncryptionNonce  []byte             `json:"encryption_nonce"`
	KeyVersion       int32              `json:"key_version"`
	AccountMetadata  []byte             `json:"account_metadata"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAgentCredential(ctx context.Context, arg CreateAgentCredentialParams) (AgentCredential, error) {
	row := q.db.QueryRow(ctx, createAgentCredential,
		arg.OwnerUserID,
		arg.Provider,
		arg.AuthKind,
		arg.Label,
		arg.EncryptedPayload,
		arg.EncryptionNonce,
		arg.KeyVersion,
		arg.AccountMetadata,
		arg.ExpiresAt,
	)
	var i AgentCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Provider,
		&i.AuthKind,
		&i.Label,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.KeyVersion,
		&i.AccountMetadata,
		&i.ExpiresAt,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentCredential = `-- name: GetAgentCredential :one
SELECT id, team_id, owner_user_id, provider, auth_kind, label, encrypted_payload, encryption_nonce, key_version, account_metadata, expires_at, credential_version, revoked_at, created_at, updated_at FROM agent_credentials
WHERE id = $1 AND team_id = public.memoh_current_team_id()
`

func (q *Queries) GetAgentCredential(ctx context.Context, id pgtype.UUID) (AgentCredential, error) {
	row := q.db.QueryRow(ctx, getAgentCredential, id)
	var i AgentCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Provider,
		&i.AuthKind,
		&i.Label,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.KeyVersion,
		&i.AccountMetadata,
		&i.ExpiresAt,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotAgentCredential = `-- name: GetBotAgentCredential :one
SELECT c.id, c.team_id, c.owner_user_id, c.provider, c.auth_kind, c.label, c.encrypted_payload, c.encryption_nonce, c.key_version, c.account_metadata, c.expires_at, c.credential_version, c.revoked_at, c.created_at, c.updated_at, a.runtime::text AS agent_runtime
FROM bot_agents a
JOIN agent_credentials c
  ON c.team_id = a.team_id AND c.id = a.agent_credential_id
WHERE a.bot_id = $1
  AND a.id = $2
  AND a.team_id = public.memoh_current_team_id()
  AND a.deleted_at IS NULL
`

type GetBotAgentCredentialParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	BotAgentID pgtype.UUID `json:"bot_agent_id"`
}

type GetBotAgentCredentialRow struct {
	ID                pgtype.UUID        `json:"id"`
	TeamID            pgtype.UUID        `json:"team_id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	Provider          string             `json:"provider"`
	AuthKind          string             `json:"auth_kind"`
	Label             string             `json:"label"`
	EncryptedPayload  []byte             `json:"encrypted_payload"`
	EncryptionNonce   []byte             `json:"encryption_nonce"`
	KeyVersion        int32              `json:"key_version"`
	AccountMetadata   []byte             `json:"account_metadata"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CredentialVersion int64              `json:"credential_version"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AgentRuntime      string             `json:"agent_runtime"`
}

func (q *Queries) GetBotAgentCredential(ctx context.Context, arg GetBotAgentCredentialParams) (GetBotAgentCredentialRow, error) {
	row := q.db.QueryRow(ctx, getBotAgentCredential, arg.BotID, arg.BotAgentID)
	var i GetBotAgentCredentialRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Provider,
		&i.AuthKind,
		&i.Label,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.KeyVersion,
		&i.AccountMetadata,
		&i.ExpiresAt,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentRuntime,
	)
	return i, err
}

const getBotAgentRuntime = `-- name: GetBotAgentRuntime :one
SELECT runtime
FROM bot_agents
WHERE bot_id = $1
  AND id = $2
  AND team_id = public.memoh_current_team_id()
  AND deleted_at IS NULL
`

type GetBotAgentRuntimeParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	BotAgentID pgtype.UUID `json:"bot_agent_id"`
}

func (q *Queries) GetBotAgentRuntime(ctx context.Context, arg GetBotAgentRuntimeParams) (string, error) {
	row := q.db.QueryRow(ctx, getBotAgentRuntime, arg.BotID, arg.BotAgentID)
	var runtime string
	err := row.Scan(&runtime)
	return runtime, err
}

const revokeAgentCredentialByID = `-- name: RevokeAgentCredentialByID :one
UPDATE agent_credentials
SET revoked_at = now(),
    credential_version = credential_version + 1,
    updated_at = now()
WHERE id = $1
  AND team_id = public.memoh_current_team_id()
  AND revoked_at IS NULL
RETURNING id, team_id, owner_user_id, provider, auth_kind, label, encrypted_payload, encryption_nonce, key_version, account_metadata, expires_at, credential_version, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeAgentCredentialByID(ctx context.Context, id pgtype.UUID) (AgentCredential, error) {
	row := q.db.QueryRow(ctx, revokeAgentCredentialByID, id)
	var i AgentCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Provider,
		&i.AuthKind,
		&i.Label,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.KeyVersion,
		&i.AccountMetadata,
		&i.ExpiresAt,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAgentCredentialsForBot = `-- name: RevokeAgentCredentialsForBot :exec
UPDATE agent_credentials c
SET revoked_at = now(),
    credential_version = credential_version + 1,
    updated_at = now()
WHERE c.team_id = public.memoh_current_team_id()
  AND c.revoked_at IS NULL
  AND EXISTS (
    SELECT 1 FROM bot_agents a
    WHERE a.team_id = c.team_id AND a.agent_credential_id = c.id AND a.bot_id = $1
  )
  AND NOT EXISTS (
    SELECT 1 FROM bot_agents o
    WHERE o.team_id = c.team_id AND o.agent_credential_id = c.id
      AND o.bot_id <> $1 AND o.deleted_at IS NULL
  )
`

func (q *Queries) RevokeAgentCredentialsForBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAgentCredentialsForBot, botID)
	return err
}

const setBotAgentCredential = `-- name: SetBotAgentCredential :one
UPDATE bot_agents
SET agent_credential_id = $2,
    updated_at = now()
WHERE bot_agents.bot_id = $1
  AND bot_agents.id = $3
  AND bot_agents.team_id = public.memoh_current_team_id()
  AND bot_agents.deleted_at IS NULL
RETURNING (
    SELECT prev.agent_credential_id
    FROM bot_agents prev
    WHERE prev.id = bot_agents.id
) AS previous_credential_id
`

type SetBotAgentCredentialParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	CredentialID pgtype.UUID `json:"credential_id"`
	BotAgentID   pgtype.UUID `json:"bot_agent_id"`
}

func (q *Queries) SetBotAgentCredential(ctx context.Context, arg SetBotAgentCredentialParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, setBotAgentCredential, arg.BotID, arg.CredentialID, arg.BotAgentID)
	var previous_credential_id pgtype.UUID
	err := row.Scan(&previous_credential_id)
	return previous_credential_id, err
}

const updateAgentCredentialPayloadCAS = `-- name: UpdateAgentCredentialPayloadCAS :one
UPDATE agent_credentials
SET encrypted_payload = $1,
    encryption_nonce = $2,
    key_version = $3,
    account_metadata = $4,
    expires_at = $5,
    credential_version = credential_version + 1,
    updated_at = now()
WHERE id = $6
  AND team_id = public.memoh_current_team_id()
  AND credential_version = $7
  AND revoked_at IS NULL
RETURNING id, team_id, owner_user_id, provider, auth_kind, label, encrypted_payload, encryption_nonce, key_version, account_metadata, expires_at, credential_version, revoked_at, created_at, updated_at
`

type UpdateAgentCredentialPayloadCASParams struct {
	EncryptedPayload []byte             `json:"encrypted_payload"`
	EncryptionNonce  []byte             `json:"encryption_nonce"`
	KeyVersion       int32              `json:"key_version"`
	AccountMetadata  []byte             `json:"account_metadata"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ID               pgtype.UUID        `json:"id"`
	ExpectedVersion  int64              `json:"expected_version"`
}

func (q *Queries) UpdateAgentCredentialPayloadCAS(ctx context.Context, arg UpdateAgentCredentialPayloadCASParams) (AgentCredential, error) {
	row := q.db.QueryRow(ctx, updateAgentCredentialPayloadCAS,
		arg.EncryptedPayload,
		arg.EncryptionNonce,
		arg.KeyVersion,
		arg.AccountMetadata,
		arg.ExpiresAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i AgentCredential
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Provider,
		&i.AuthKind,
		&i.Label,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.KeyVersion,
		&i.AccountMetadata,
		&i.ExpiresAt,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
