// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_session_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentSessionPublicationsBySession = `-- name: DeleteAgentSessionPublicationsBySession :execrows
DELETE FROM agent_session_publications publication
WHERE publication.team_id = public.memoh_current_team_id()
  AND publication.session_id = $1
`

func (q *Queries) DeleteAgentSessionPublicationsBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSessionPublicationsBySession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentSessionStateLineFilesNotIn = `-- name: DeleteAgentSessionStateLineFilesNotIn :execrows
DELETE FROM agent_session_state_lines line
WHERE line.team_id = public.memoh_current_team_id()
  AND line.session_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements_text($2::jsonb) AS kept(path)
    WHERE kept.path = line.file_path
  )
`

type DeleteAgentSessionStateLineFilesNotInParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	KeptPaths []byte      `json:"kept_paths"`
}

// Remove files the incoming version no longer contains, including files a
// crashed candidate introduced that neither the canonical nor the incoming
// version knows about. kept_paths is a JSONB array of file path strings.
func (q *Queries) DeleteAgentSessionStateLineFilesNotIn(ctx context.Context, arg DeleteAgentSessionStateLineFilesNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSessionStateLineFilesNotIn, arg.SessionID, arg.KeptPaths)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentSessionStateLinesBySession = `-- name: DeleteAgentSessionStateLinesBySession :execrows
DELETE FROM agent_session_state_lines
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
`

func (q *Queries) DeleteAgentSessionStateLinesBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSessionStateLinesBySession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentSessionStatesBySession = `-- name: DeleteAgentSessionStatesBySession :execrows
DELETE FROM agent_session_states state
WHERE state.team_id = public.memoh_current_team_id()
  AND state.session_id = $1
`

func (q *Queries) DeleteAgentSessionStatesBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSessionStatesBySession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeDecisionProjectionsByRun = `-- name: DeleteRuntimeDecisionProjectionsByRun :execrows
DELETE FROM bot_history_messages message
WHERE message.team_id = public.memoh_current_team_id()
  AND message.bot_id = $1
  AND message.session_id = $2
  AND message.run_id = $3
  AND message.role = 'assistant'
  AND message.runtime_type <> 'model'
  AND message.metadata @> '{"agent_decision_projection": true}'::jsonb
`

type DeleteRuntimeDecisionProjectionsByRunParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

// Decision cards are temporary stream projections. Delete by their stable
// run marker as well as by returned IDs so an insert whose COMMIT ack was lost
// cannot survive the final canonical round as a duplicate assistant message.
func (q *Queries) DeleteRuntimeDecisionProjectionsByRun(ctx context.Context, arg DeleteRuntimeDecisionProjectionsByRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeDecisionProjectionsByRun, arg.BotID, arg.SessionID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentSessionCanonicalStateShape = `-- name: GetAgentSessionCanonicalStateShape :one
SELECT state.through_run_id, state.file_shapes
FROM agent_session_publications publication
JOIN bot_sessions session
  ON session.team_id = publication.team_id
 AND session.id = publication.session_id
 AND session.bot_id = $1
JOIN agent_session_states state
  ON state.team_id = publication.team_id
 AND state.session_id = publication.session_id
 AND state.through_run_id = publication.run_id
WHERE publication.team_id = public.memoh_current_team_id()
  AND publication.session_id = $2
  AND publication.checkpoint_reset = false
`

type GetAgentSessionCanonicalStateShapeParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type GetAgentSessionCanonicalStateShapeRow struct {
	ThroughRunID pgtype.UUID `json:"through_run_id"`
	FileShapes   []byte      `json:"file_shapes"`
}

// The committed head version's per-file shapes: the authoritative read bound
// for Load and the append-only baseline for the next staging. Reset heads
// have no state row, so this returns no rows for them.
func (q *Queries) GetAgentSessionCanonicalStateShape(ctx context.Context, arg GetAgentSessionCanonicalStateShapeParams) (GetAgentSessionCanonicalStateShapeRow, error) {
	row := q.db.QueryRow(ctx, getAgentSessionCanonicalStateShape, arg.BotID, arg.SessionID)
	var i GetAgentSessionCanonicalStateShapeRow
	err := row.Scan(&i.ThroughRunID, &i.FileShapes)
	return i, err
}

const getAgentSessionPublicationHead = `-- name: GetAgentSessionPublicationHead :one
SELECT publication.run_id, publication.checkpoint_reset
FROM agent_session_publications publication
JOIN bot_sessions session
  ON session.team_id = publication.team_id
 AND session.id = publication.session_id
WHERE publication.team_id = public.memoh_current_team_id()
  AND publication.session_id = $1
  AND session.bot_id = $2
  AND session.runtime_type <> 'model'
  AND session.deleted_at IS NULL
`

type GetAgentSessionPublicationHeadParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

type GetAgentSessionPublicationHeadRow struct {
	RunID           pgtype.UUID `json:"run_id"`
	CheckpointReset bool        `json:"checkpoint_reset"`
}

// Return the canonical publication head independently from snapshot
// availability. Warm runtimes use this small watermark before every native
// prompt so another server instance (or a history clear) cannot leave two
// process-local conversations advancing from different canonical heads.
func (q *Queries) GetAgentSessionPublicationHead(ctx context.Context, arg GetAgentSessionPublicationHeadParams) (GetAgentSessionPublicationHeadRow, error) {
	row := q.db.QueryRow(ctx, getAgentSessionPublicationHead, arg.SessionID, arg.BotID)
	var i GetAgentSessionPublicationHeadRow
	err := row.Scan(&i.RunID, &i.CheckpointReset)
	return i, err
}

const getAgentSessionState = `-- name: GetAgentSessionState :one
WITH target_session AS MATERIALIZED (
  SELECT session.team_id, session.id
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.id = $1
    AND session.bot_id = $2
    AND session.runtime_type <> 'model'
    AND session.deleted_at IS NULL
  FOR SHARE
)
SELECT
  publication.run_id AS through_run_id,
  state.through_run_id AS staged_through_run_id,
  COALESCE(state.agent_id, '')::text AS agent_id,
  COALESCE(state.agent_session_id, '')::text AS agent_session_id,
  COALESCE(state.cwd, '')::text AS cwd,
  COALESCE(state.transcript_path, '')::text AS transcript_path,
  COALESCE(state.runtime_fencing_token, 0)::bigint AS runtime_fencing_token,
  COALESCE(state.file_count, 0)::int AS file_count,
  COALESCE(state.record_count, 0)::bigint AS record_count,
  COALESCE(state.file_shapes, '[]'::jsonb) AS file_shapes
FROM agent_session_publications publication
JOIN target_session session
  ON session.team_id = publication.team_id
 AND session.id = publication.session_id
LEFT JOIN agent_session_states state
  ON state.team_id = publication.team_id
 AND state.session_id = publication.session_id
 AND state.through_run_id = publication.run_id
WHERE publication.team_id = public.memoh_current_team_id()
  AND publication.session_id = $1
  AND publication.checkpoint_reset = false
`

type GetAgentSessionStateParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

type GetAgentSessionStateRow struct {
	ThroughRunID        pgtype.UUID `json:"through_run_id"`
	StagedThroughRunID  pgtype.UUID `json:"staged_through_run_id"`
	AgentID             string      `json:"agent_id"`
	AgentSessionID      string      `json:"agent_session_id"`
	Cwd                 string      `json:"cwd"`
	TranscriptPath      string      `json:"transcript_path"`
	RuntimeFencingToken int64       `json:"runtime_fencing_token"`
	FileCount           int32       `json:"file_count"`
	RecordCount         int64       `json:"record_count"`
	FileShapes          []byte      `json:"file_shapes"`
}

// A staged snapshot becomes readable only after its run owns the session's
// canonical publication head. Returning the head even when the LEFT JOIN
// misses lets the adapter distinguish "no runtime history yet" from "history
// committed but its snapshot is missing".
func (q *Queries) GetAgentSessionState(ctx context.Context, arg GetAgentSessionStateParams) (GetAgentSessionStateRow, error) {
	row := q.db.QueryRow(ctx, getAgentSessionState, arg.SessionID, arg.BotID)
	var i GetAgentSessionStateRow
	err := row.Scan(
		&i.ThroughRunID,
		&i.StagedThroughRunID,
		&i.AgentID,
		&i.AgentSessionID,
		&i.Cwd,
		&i.TranscriptPath,
		&i.RuntimeFencingToken,
		&i.FileCount,
		&i.RecordCount,
		&i.FileShapes,
	)
	return i, err
}

const getRuntimeConfigEpoch = `-- name: GetRuntimeConfigEpoch :one
SELECT
  bot.runtime_config_epoch AS bot_runtime_config_epoch,
  COALESCE(session.runtime_config_epoch, 0)::bigint AS session_runtime_config_epoch
FROM bots bot
LEFT JOIN bot_sessions session
  ON session.team_id = bot.team_id
 AND session.bot_id = bot.id
 AND session.id = $1
 AND session.deleted_at IS NULL
WHERE bot.team_id = public.memoh_current_team_id()
  AND bot.id = $2
  AND (
    $1::uuid IS NULL
    OR session.id IS NOT NULL
  )
`

type GetRuntimeConfigEpochParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

type GetRuntimeConfigEpochRow struct {
	BotRuntimeConfigEpoch     int64 `json:"bot_runtime_config_epoch"`
	SessionRuntimeConfigEpoch int64 `json:"session_runtime_config_epoch"`
}

// A handle records this pair before its process starts. Bound resolution and
// every prompt compare it again, so a reset on another server invalidates
// idle and unbound processes that have no active session_run to route to.
func (q *Queries) GetRuntimeConfigEpoch(ctx context.Context, arg GetRuntimeConfigEpochParams) (GetRuntimeConfigEpochRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeConfigEpoch, arg.SessionID, arg.BotID)
	var i GetRuntimeConfigEpochRow
	err := row.Scan(&i.BotRuntimeConfigEpoch, &i.SessionRuntimeConfigEpoch)
	return i, err
}

const getRuntimeLeadingUserMessageID = `-- name: GetRuntimeLeadingUserMessageID :one
SELECT message.id
FROM bot_history_messages message
JOIN session_runs run
  ON run.team_id = message.team_id
 AND run.run_id = message.run_id
 AND run.bot_id = message.bot_id
 AND run.session_id = message.session_id
 AND run.turn_id = message.turn_id
 AND run.turn_position = message.turn_position
WHERE message.team_id = public.memoh_current_team_id()
  AND message.bot_id = $1
  AND message.session_id = $2
  AND message.run_id = $3
  AND message.turn_id = $4
  AND message.role = 'user'
  AND message.runtime_type <> 'model'
  AND message.turn_message_seq = 1
ORDER BY message.created_at DESC, message.id DESC
LIMIT 1
`

type GetRuntimeLeadingUserMessageIDParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

// Reconcile the single eager user row after an uncertain COMMIT. The caller
// first waits on the session row in a separate statement, so no row here is a
// definitive rollback rather than an observation racing the old backend.
func (q *Queries) GetRuntimeLeadingUserMessageID(ctx context.Context, arg GetRuntimeLeadingUserMessageIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRuntimeLeadingUserMessageID,
		arg.BotID,
		arg.SessionID,
		arg.RunID,
		arg.TurnID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRuntimeRoundOutcome = `-- name: GetRuntimeRoundOutcome :one
SELECT COALESCE(message.metadata->>'agent_turn_outcome', '')::text AS outcome
FROM bot_history_messages message
JOIN session_runs run
  ON run.team_id = message.team_id
 AND run.run_id = message.run_id
 AND run.bot_id = message.bot_id
 AND run.session_id = message.session_id
 AND run.turn_id = message.turn_id
 AND run.turn_position = message.turn_position
WHERE message.team_id = public.memoh_current_team_id()
  AND message.bot_id = $1
  AND message.session_id = $2
  AND message.run_id = $3
  AND message.role = 'assistant'
  AND message.runtime_type <> 'model'
  AND message.turn_visible = true
  AND message.metadata->>'agent_turn_outcome' IN ('succeeded', 'failed', 'aborted')
ORDER BY message.turn_message_seq DESC, message.created_at DESC, message.id DESC
LIMIT 1
`

type GetRuntimeRoundOutcomeParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

// Read the terminal runtime outcome for commit-unknown reconciliation after
// the caller has first waited on the session write lock.
func (q *Queries) GetRuntimeRoundOutcome(ctx context.Context, arg GetRuntimeRoundOutcomeParams) (string, error) {
	row := q.db.QueryRow(ctx, getRuntimeRoundOutcome, arg.BotID, arg.SessionID, arg.RunID)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const insertAgentSessionStateLines = `-- name: InsertAgentSessionStateLines :one
WITH target_state AS MATERIALIZED (
  SELECT state.team_id, state.session_id, state.through_run_id
  FROM agent_session_states state
  WHERE state.team_id = public.memoh_current_team_id()
    AND state.session_id = $1
    AND state.through_run_id = $2
),
input_lines AS MATERIALIZED (
  SELECT
    item->>'file_path' AS file_path,
    (item->>'line_number')::bigint AS line_number,
    item->>'content' AS content,
    octet_length(item->>'content') AS content_bytes
  FROM jsonb_array_elements($3::jsonb) AS input(item)
),
inserted_lines AS (
  INSERT INTO agent_session_state_lines (
    team_id,
    session_id,
    file_path,
    line_number,
    content,
    content_bytes
  )
  SELECT
    state.team_id,
    state.session_id,
    line.file_path,
    line.line_number,
    line.content,
    line.content_bytes
  FROM target_state state
  CROSS JOIN input_lines line
  RETURNING content_bytes
)
SELECT
  count(*)::bigint AS rows_written,
  COALESCE(sum(content_bytes::bigint + 1), 0)::bigint AS jsonl_bytes
FROM inserted_lines
`

type InsertAgentSessionStateLinesParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ThroughRunID pgtype.UUID `json:"through_run_id"`
	StateLines   []byte      `json:"state_lines"`
}

type InsertAgentSessionStateLinesRow struct {
	RowsWritten int64 `json:"rows_written"`
	JsonlBytes  int64 `json:"jsonl_bytes"`
}

// content travels as a JSON string inside the envelope and lands verbatim in
// the TEXT column, so the stored bytes are exactly the capture's compacted
// bytes and every digest survives the database round trip.
func (q *Queries) InsertAgentSessionStateLines(ctx context.Context, arg InsertAgentSessionStateLinesParams) (InsertAgentSessionStateLinesRow, error) {
	row := q.db.QueryRow(ctx, insertAgentSessionStateLines, arg.SessionID, arg.ThroughRunID, arg.StateLines)
	var i InsertAgentSessionStateLinesRow
	err := row.Scan(&i.RowsWritten, &i.JsonlBytes)
	return i, err
}

const listAgentSessionStateLinePage = `-- name: ListAgentSessionStateLinePage :many
WITH file_bounds AS MATERIALIZED (
  SELECT bound.key AS file_path, bound.value::bigint AS max_line
  FROM jsonb_each_text($2::jsonb) AS bound(key, value)
),
candidate_lines AS MATERIALIZED (
  SELECT line.file_path, line.line_number, line.content_bytes
  FROM agent_session_state_lines line
  JOIN file_bounds bound
    ON bound.file_path = line.file_path
   AND line.line_number <= bound.max_line
  JOIN bot_sessions session
    ON session.team_id = line.team_id
   AND session.id = line.session_id
   AND session.bot_id = $3
   AND session.runtime_type <> 'model'
   AND session.deleted_at IS NULL
  WHERE line.team_id = public.memoh_current_team_id()
    AND line.session_id = $1
    AND (
      line.file_path > $4::text
      OR (
        line.file_path = $4::text
        AND line.line_number > $5::bigint
      )
    )
  ORDER BY line.file_path, line.line_number
  LIMIT $6::int
),
sized_lines AS MATERIALIZED (
  SELECT
    candidate_lines.file_path,
    candidate_lines.line_number,
    row_number() OVER (
      ORDER BY candidate_lines.file_path, candidate_lines.line_number
    ) AS ordinal,
    sum(
      octet_length(candidate_lines.file_path)
      + candidate_lines.content_bytes
      + 32
    ) OVER (
      ORDER BY candidate_lines.file_path, candidate_lines.line_number
    ) AS cumulative_bytes
  FROM candidate_lines
),
selected_lines AS MATERIALIZED (
  SELECT file_path, line_number
  FROM sized_lines
  WHERE ordinal = 1
     OR cumulative_bytes <= $7::bigint
)
SELECT line.file_path, line.line_number, line.content
FROM selected_lines selected
JOIN agent_session_state_lines line
  ON line.team_id = public.memoh_current_team_id()
 AND line.session_id = $1
 AND line.file_path = selected.file_path
 AND line.line_number = selected.line_number
ORDER BY line.file_path, line.line_number
`

type ListAgentSessionStateLinePageParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	FileBounds      []byte      `json:"file_bounds"`
	BotID           pgtype.UUID `json:"bot_id"`
	AfterFilePath   string      `json:"after_file_path"`
	AfterLineNumber int64       `json:"after_line_number"`
	MaxResults      int32       `json:"max_results"`
	MaxPageBytes    int64       `json:"max_page_bytes"`
}

type ListAgentSessionStateLinePageRow struct {
	FilePath   string `json:"file_path"`
	LineNumber int64  `json:"line_number"`
	Content    string `json:"content"`
}

// Keyset pagination keeps the Go result bounded independently of snapshot
// size. The cumulative byte guard normally limits a page to max_page_bytes;
// ordinal 1 guarantees progress when one valid JSONL record is larger than
// that target (the adapter applies the stricter per-record hard limit).
// file_bounds is the requested version's shape as a {path: records} object:
// it is the version-membership filter, hiding lines beyond the version's per-
// file record counts (a crashed candidate's dangling tail) and files the
// version never contained.
func (q *Queries) ListAgentSessionStateLinePage(ctx context.Context, arg ListAgentSessionStateLinePageParams) ([]ListAgentSessionStateLinePageRow, error) {
	rows, err := q.db.Query(ctx, listAgentSessionStateLinePage,
		arg.SessionID,
		arg.FileBounds,
		arg.BotID,
		arg.AfterFilePath,
		arg.AfterLineNumber,
		arg.MaxResults,
		arg.MaxPageBytes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSessionStateLinePageRow
	for rows.Next() {
		var i ListAgentSessionStateLinePageRow
		if err := rows.Scan(&i.FilePath, &i.LineNumber, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAgentSessionStateVersions = `-- name: PruneAgentSessionStateVersions :execrows
DELETE FROM agent_session_states state
WHERE state.team_id = public.memoh_current_team_id()
  AND state.session_id = $1
  AND state.through_run_id <> $2
  AND NOT EXISTS (
    SELECT 1
    FROM agent_session_publications publication
    WHERE publication.team_id = state.team_id
      AND publication.session_id = state.session_id
      AND publication.checkpoint_reset = false
      AND publication.run_id = state.through_run_id
  )
`

type PruneAgentSessionStateVersionsParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ThroughRunID pgtype.UUID `json:"through_run_id"`
}

// Bound normal storage to the incoming staged candidate plus the current
// canonical head. A failed candidate can survive only until the next stage;
// a crash before this statement rolls the entire replacement back.
func (q *Queries) PruneAgentSessionStateVersions(ctx context.Context, arg PruneAgentSessionStateVersionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAgentSessionStateVersions, arg.SessionID, arg.ThroughRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trimAgentSessionStateLines = `-- name: TrimAgentSessionStateLines :execrows
DELETE FROM agent_session_state_lines
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
  AND file_path = $2
  AND line_number > $3::bigint
`

type TrimAgentSessionStateLinesParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	FilePath    string      `json:"file_path"`
	KeepRecords int64       `json:"keep_records"`
}

// Delete one file's lines beyond keep_records. keep_records = 0 clears the
// file for a full rewrite; a positive value clears a crashed candidate's
// dangling tail before the next append.
func (q *Queries) TrimAgentSessionStateLines(ctx context.Context, arg TrimAgentSessionStateLinesParams) (int64, error) {
	result, err := q.db.Exec(ctx, trimAgentSessionStateLines, arg.SessionID, arg.FilePath, arg.KeepRecords)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAgentSessionPublication = `-- name: UpsertAgentSessionPublication :execrows
WITH target_session AS MATERIALIZED (
  SELECT session.team_id, session.id, session.runtime_fencing_token
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.id = $2
    AND session.bot_id = $3
    AND session.runtime_type <> 'model'
    AND session.deleted_at IS NULL
),
target_run AS MATERIALIZED (
  SELECT target.team_id, target.id AS session_id, run.run_id
  FROM target_session target
  JOIN session_runs run
    ON run.team_id = target.team_id
   AND run.session_id = target.id
   AND run.bot_id = $3
   AND run.run_id = $4
   AND run.fencing_token = target.runtime_fencing_token
)
INSERT INTO agent_session_publications (team_id, session_id, run_id, checkpoint_reset)
SELECT target.team_id, target.session_id, target.run_id, $1
FROM target_run target
ON CONFLICT (team_id, session_id) DO UPDATE SET
  run_id = EXCLUDED.run_id,
  checkpoint_reset = EXCLUDED.checkpoint_reset,
  updated_at = now()
`

type UpsertAgentSessionPublicationParams struct {
	CheckpointReset bool        `json:"checkpoint_reset"`
	SessionID       pgtype.UUID `json:"session_id"`
	BotID           pgtype.UUID `json:"bot_id"`
	RunID           pgtype.UUID `json:"run_id"`
}

// Written in the same transaction as the round's canonical messages. The run
// join proves the run belongs to this tenant+session and still owns the
// session's current fencing generation, so a stale runtime cannot move the
// head.
func (q *Queries) UpsertAgentSessionPublication(ctx context.Context, arg UpsertAgentSessionPublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAgentSessionPublication,
		arg.CheckpointReset,
		arg.SessionID,
		arg.BotID,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAgentSessionState = `-- name: UpsertAgentSessionState :one
WITH target_session AS MATERIALIZED (
  SELECT session.team_id, session.id, session.runtime_fencing_token
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.id = $8
    AND session.bot_id = $9
    AND session.runtime_type <> 'model'
    AND session.deleted_at IS NULL
),
target_run AS MATERIALIZED (
  SELECT target.team_id, target.id AS session_id, target.runtime_fencing_token, run.run_id
  FROM target_session target
  JOIN session_runs run
    ON run.team_id = target.team_id
   AND run.session_id = target.id
   AND run.bot_id = $9
   AND run.run_id = $10
   AND run.fencing_token = target.runtime_fencing_token
   AND run.state IN ('running', 'waiting_decision')
)
INSERT INTO agent_session_states (
  team_id,
  session_id,
  through_run_id,
  agent_id,
  agent_session_id,
  cwd,
  transcript_path,
  runtime_fencing_token,
  file_count,
  record_count,
  file_shapes
)
SELECT
  target.team_id,
  target.session_id,
  target.run_id,
  $1,
  $2,
  $3,
  $4,
  target.runtime_fencing_token,
  $5,
  $6,
  $7
FROM target_run target
ON CONFLICT (team_id, session_id, through_run_id) DO UPDATE SET
  agent_id = EXCLUDED.agent_id,
  agent_session_id = EXCLUDED.agent_session_id,
  cwd = EXCLUDED.cwd,
  transcript_path = EXCLUDED.transcript_path,
  runtime_fencing_token = EXCLUDED.runtime_fencing_token,
  file_count = EXCLUDED.file_count,
  record_count = EXCLUDED.record_count,
  file_shapes = EXCLUDED.file_shapes,
  updated_at = now()
WHERE agent_session_states.runtime_fencing_token <= EXCLUDED.runtime_fencing_token
RETURNING agent_session_states.team_id, agent_session_states.session_id, agent_session_states.through_run_id, agent_session_states.agent_id, agent_session_states.agent_session_id, agent_session_states.cwd, agent_session_states.transcript_path, agent_session_states.runtime_fencing_token, agent_session_states.file_count, agent_session_states.record_count, agent_session_states.file_shapes, agent_session_states.created_at, agent_session_states.updated_at
`

type UpsertAgentSessionStateParams struct {
	AgentID        string      `json:"agent_id"`
	AgentSessionID string      `json:"agent_session_id"`
	Cwd            string      `json:"cwd"`
	TranscriptPath string      `json:"transcript_path"`
	FileCount      int32       `json:"file_count"`
	RecordCount    int64       `json:"record_count"`
	FileShapes     []byte      `json:"file_shapes"`
	SessionID      pgtype.UUID `json:"session_id"`
	BotID          pgtype.UUID `json:"bot_id"`
	ThroughRunID   pgtype.UUID `json:"through_run_id"`
}

// This is deliberately a staging write. Canonical history is committed later
// by the application; GetAgentSessionState is the promotion gate. The run join
// proves that an arbitrary run id cannot be attached to another session and
// that this process still owns the run's current fencing generation.
func (q *Queries) UpsertAgentSessionState(ctx context.Context, arg UpsertAgentSessionStateParams) (AgentSessionState, error) {
	row := q.db.QueryRow(ctx, upsertAgentSessionState,
		arg.AgentID,
		arg.AgentSessionID,
		arg.Cwd,
		arg.TranscriptPath,
		arg.FileCount,
		arg.RecordCount,
		arg.FileShapes,
		arg.SessionID,
		arg.BotID,
		arg.ThroughRunID,
	)
	var i AgentSessionState
	err := row.Scan(
		&i.TeamID,
		&i.SessionID,
		&i.ThroughRunID,
		&i.AgentID,
		&i.AgentSessionID,
		&i.Cwd,
		&i.TranscriptPath,
		&i.RuntimeFencingToken,
		&i.FileCount,
		&i.RecordCount,
		&i.FileShapes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
