// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const botAgentIsDefault = `-- name: BotAgentIsDefault :one
SELECT EXISTS (
  SELECT 1
  FROM bots
  WHERE team_id = public.memoh_current_team_id()
    AND id = $1
    AND default_bot_agent_id = $2
) AS is_default
`

type BotAgentIsDefaultParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) BotAgentIsDefault(ctx context.Context, arg BotAgentIsDefaultParams) (bool, error) {
	row := q.db.QueryRow(ctx, botAgentIsDefault, arg.BotID, arg.ID)
	var is_default bool
	err := row.Scan(&is_default)
	return is_default, err
}

const createBotAgent = `-- name: CreateBotAgent :one
INSERT INTO bot_agents (bot_id, name, runtime, enabled, metadata)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
`

type CreateBotAgentParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	Name     string      `json:"name"`
	Runtime  string      `json:"runtime"`
	Enabled  bool        `json:"enabled"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateBotAgent(ctx context.Context, arg CreateBotAgentParams) (BotAgent, error) {
	row := q.db.QueryRow(ctx, createBotAgent,
		arg.BotID,
		arg.Name,
		arg.Runtime,
		arg.Enabled,
		arg.Metadata,
	)
	var i BotAgent
	err := row.Scan(
		&i.TeamID,
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Runtime,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AgentCredentialID,
	)
	return i, err
}

const findActiveBotAgentByRuntimeProvider = `-- name: FindActiveBotAgentByRuntimeProvider :one
SELECT team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
FROM bot_agents
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND runtime = $2
  AND metadata->>'provider' = $3::text
  AND enabled
  AND deleted_at IS NULL
ORDER BY created_at, id
LIMIT 1
`

type FindActiveBotAgentByRuntimeProviderParams struct {
	BotID    pgtype.UUID `json:"bot_id"`
	Runtime  string      `json:"runtime"`
	Provider string      `json:"provider"`
}

func (q *Queries) FindActiveBotAgentByRuntimeProvider(ctx context.Context, arg FindActiveBotAgentByRuntimeProviderParams) (BotAgent, error) {
	row := q.db.QueryRow(ctx, findActiveBotAgentByRuntimeProvider, arg.BotID, arg.Runtime, arg.Provider)
	var i BotAgent
	err := row.Scan(
		&i.TeamID,
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Runtime,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AgentCredentialID,
	)
	return i, err
}

const getActiveBotAgentByID = `-- name: GetActiveBotAgentByID :one
SELECT team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
FROM bot_agents
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
  AND enabled
  AND deleted_at IS NULL
`

type GetActiveBotAgentByIDParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetActiveBotAgentByID(ctx context.Context, arg GetActiveBotAgentByIDParams) (BotAgent, error) {
	row := q.db.QueryRow(ctx, getActiveBotAgentByID, arg.BotID, arg.ID)
	var i BotAgent
	err := row.Scan(
		&i.TeamID,
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Runtime,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AgentCredentialID,
	)
	return i, err
}

const getBotAgentByID = `-- name: GetBotAgentByID :one
SELECT team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
FROM bot_agents
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
`

type GetBotAgentByIDParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetBotAgentByID(ctx context.Context, arg GetBotAgentByIDParams) (BotAgent, error) {
	row := q.db.QueryRow(ctx, getBotAgentByID, arg.BotID, arg.ID)
	var i BotAgent
	err := row.Scan(
		&i.TeamID,
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Runtime,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AgentCredentialID,
	)
	return i, err
}

const listBotAgents = `-- name: ListBotAgents :many
SELECT team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
FROM bot_agents
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND deleted_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListBotAgents(ctx context.Context, botID pgtype.UUID) ([]BotAgent, error) {
	rows, err := q.db.Query(ctx, listBotAgents, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotAgent
	for rows.Next() {
		var i BotAgent
		if err := rows.Scan(
			&i.TeamID,
			&i.ID,
			&i.BotID,
			&i.Name,
			&i.Runtime,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AgentCredentialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBotForAgentMutation = `-- name: LockBotForAgentMutation :one
SELECT id
FROM bots
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
FOR NO KEY UPDATE
`

func (q *Queries) LockBotForAgentMutation(ctx context.Context, botID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBotForAgentMutation, botID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteBotAgent = `-- name: SoftDeleteBotAgent :one
UPDATE bot_agents
SET enabled = false,
    deleted_at = now(),
    updated_at = now()
WHERE bot_agents.team_id = public.memoh_current_team_id()
  AND bot_agents.bot_id = $1
  AND bot_agents.id = $2
  AND bot_agents.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM bots
    WHERE bots.team_id = public.memoh_current_team_id()
      AND bots.id = $1
      AND bots.default_bot_agent_id = bot_agents.id
  )
RETURNING team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
`

type SoftDeleteBotAgentParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteBotAgent(ctx context.Context, arg SoftDeleteBotAgentParams) (BotAgent, error) {
	row := q.db.QueryRow(ctx, softDeleteBotAgent, arg.BotID, arg.ID)
	var i BotAgent
	err := row.Scan(
		&i.TeamID,
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Runtime,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AgentCredentialID,
	)
	return i, err
}

const updateBotAgent = `-- name: UpdateBotAgent :one
UPDATE bot_agents
SET name = $1,
    enabled = $2,
    metadata = CASE
      WHEN $3::boolean THEN $4::jsonb
      ELSE bot_agents.metadata
    END,
    updated_at = now()
WHERE bot_agents.team_id = public.memoh_current_team_id()
  AND bot_agents.bot_id = $5
  AND bot_agents.id = $6
  AND bot_agents.deleted_at IS NULL
  AND (
    $2::boolean
    OR NOT EXISTS (
      SELECT 1
      FROM bots
      WHERE bots.team_id = public.memoh_current_team_id()
        AND bots.id = $5
        AND bots.default_bot_agent_id = bot_agents.id
    )
  )
RETURNING team_id, id, bot_id, name, runtime, enabled, metadata, created_at, updated_at, deleted_at, agent_credential_id
`

type UpdateBotAgentParams struct {
	Name        string      `json:"name"`
	Enabled     bool        `json:"enabled"`
	MetadataSet bool        `json:"metadata_set"`
	Metadata    []byte      `json:"metadata"`
	BotID       pgtype.UUID `json:"bot_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBotAgent(ctx context.Context, arg UpdateBotAgentParams) (BotAgent, error) {
	row := q.db.QueryRow(ctx, updateBotAgent,
		arg.Name,
		arg.Enabled,
		arg.MetadataSet,
		arg.Metadata,
		arg.BotID,
		arg.ID,
	)
	var i BotAgent
	err := row.Scan(
		&i.TeamID,
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Runtime,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AgentCredentialID,
	)
	return i, err
}
