// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_lifecycle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContextLifecycle = `-- name: CreateContextLifecycle :one
INSERT INTO context_lifecycles (
  run_id,
  bot_id,
  session_id,
  status,
  error_code,
  snapshot,
  selection_decisions
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::text,
  $6::jsonb - 'selection_decisions',
  $6::jsonb -> 'selection_decisions'
)
RETURNING run_id, bot_id, session_id, status, error_code, created_at
`

type CreateContextLifecycleParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Status    string      `json:"status"`
	ErrorCode pgtype.Text `json:"error_code"`
	Snapshot  []byte      `json:"snapshot"`
}

type CreateContextLifecycleRow struct {
	RunID     pgtype.UUID        `json:"run_id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Status    string             `json:"status"`
	ErrorCode pgtype.Text        `json:"error_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateContextLifecycle(ctx context.Context, arg CreateContextLifecycleParams) (CreateContextLifecycleRow, error) {
	row := q.db.QueryRow(ctx, createContextLifecycle,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
		arg.Status,
		arg.ErrorCode,
		arg.Snapshot,
	)
	var i CreateContextLifecycleRow
	err := row.Scan(
		&i.RunID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getContextLifecycleByRunID = `-- name: GetContextLifecycleByRunID :one
SELECT run_id, team_id, bot_id, session_id, status, error_code, snapshot, created_at
FROM context_lifecycles
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
`

type GetContextLifecycleByRunIDRow struct {
	RunID     pgtype.UUID        `json:"run_id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Status    string             `json:"status"`
	ErrorCode pgtype.Text        `json:"error_code"`
	Snapshot  []byte             `json:"snapshot"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetContextLifecycleByRunID(ctx context.Context, runID pgtype.UUID) (GetContextLifecycleByRunIDRow, error) {
	row := q.db.QueryRow(ctx, getContextLifecycleByRunID, runID)
	var i GetContextLifecycleByRunIDRow
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ErrorCode,
		&i.Snapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getContextLifecycleSelectionDecisionsByRunID = `-- name: GetContextLifecycleSelectionDecisionsByRunID :one
SELECT selection_decisions
FROM context_lifecycles
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
`

func (q *Queries) GetContextLifecycleSelectionDecisionsByRunID(ctx context.Context, runID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getContextLifecycleSelectionDecisionsByRunID, runID)
	var selection_decisions []byte
	err := row.Scan(&selection_decisions)
	return selection_decisions, err
}

const getLatestAssistantContextLifecycleByRunID = `-- name: GetLatestAssistantContextLifecycleByRunID :one
SELECT id, metadata
FROM bot_history_messages
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND role = 'assistant'
  AND metadata ? 'context_lifecycle'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestAssistantContextLifecycleByRunIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) GetLatestAssistantContextLifecycleByRunID(ctx context.Context, runID pgtype.UUID) (GetLatestAssistantContextLifecycleByRunIDRow, error) {
	row := q.db.QueryRow(ctx, getLatestAssistantContextLifecycleByRunID, runID)
	var i GetLatestAssistantContextLifecycleByRunIDRow
	err := row.Scan(&i.ID, &i.Metadata)
	return i, err
}

const getLatestAssistantContextLifecycleMetadataByRunID = `-- name: GetLatestAssistantContextLifecycleMetadataByRunID :one
SELECT metadata
FROM bot_history_messages
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND role = 'assistant'
  AND metadata ? 'context_lifecycle'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestAssistantContextLifecycleMetadataByRunID(ctx context.Context, runID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLatestAssistantContextLifecycleMetadataByRunID, runID)
	var metadata []byte
	err := row.Scan(&metadata)
	return metadata, err
}

const getLatestContextLifecycleBySession = `-- name: GetLatestContextLifecycleBySession :one
SELECT (snapshot - 'selection_decisions'::text)::jsonb AS snapshot
FROM context_lifecycles
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
ORDER BY created_at DESC, run_id DESC
LIMIT 1
`

func (q *Queries) GetLatestContextLifecycleBySession(ctx context.Context, sessionID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLatestContextLifecycleBySession, sessionID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const hasUnmaterializedContextLifecycleMetadataBySession = `-- name: HasUnmaterializedContextLifecycleMetadataBySession :one
SELECT EXISTS (
  SELECT 1
  FROM bot_history_messages AS messages
  WHERE messages.session_id = $1
    AND messages.role = 'assistant'
    AND messages.metadata ? 'context_lifecycle'
    AND NOT EXISTS (
      SELECT 1
      FROM context_lifecycles AS lifecycles
      WHERE lifecycles.team_id = public.memoh_current_team_id()
        AND lifecycles.run_id = messages.run_id
    )
)
`

func (q *Queries) HasUnmaterializedContextLifecycleMetadataBySession(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasUnmaterializedContextLifecycleMetadataBySession, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRecentAssistantMessagesBySession = `-- name: ListRecentAssistantMessagesBySession :many
SELECT
  id,
  run_id,
  role,
  (metadata #- '{context_lifecycle,selection_decisions}'::text[])::jsonb AS metadata,
  created_at
FROM bot_history_messages
WHERE session_id = $1
  AND role = 'assistant'
  AND metadata ? 'context_lifecycle'
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRecentAssistantMessagesBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	MaxCount  int32       `json:"max_count"`
}

type ListRecentAssistantMessagesBySessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	Role      string             `json:"role"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentAssistantMessagesBySession(ctx context.Context, arg ListRecentAssistantMessagesBySessionParams) ([]ListRecentAssistantMessagesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listRecentAssistantMessagesBySession, arg.SessionID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAssistantMessagesBySessionRow
	for rows.Next() {
		var i ListRecentAssistantMessagesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Role,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentContextLifecyclesBySession = `-- name: ListRecentContextLifecyclesBySession :many
SELECT
  run_id,
  status,
  error_code,
  created_at,
  (snapshot - 'selection_decisions'::text)::jsonb AS snapshot
FROM context_lifecycles
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
ORDER BY created_at DESC, run_id DESC
LIMIT $2
`

type ListRecentContextLifecyclesBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	MaxCount  int32       `json:"max_count"`
}

type ListRecentContextLifecyclesBySessionRow struct {
	RunID     pgtype.UUID        `json:"run_id"`
	Status    string             `json:"status"`
	ErrorCode pgtype.Text        `json:"error_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Snapshot  []byte             `json:"snapshot"`
}

func (q *Queries) ListRecentContextLifecyclesBySession(ctx context.Context, arg ListRecentContextLifecyclesBySessionParams) ([]ListRecentContextLifecyclesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listRecentContextLifecyclesBySession, arg.SessionID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentContextLifecyclesBySessionRow
	for rows.Next() {
		var i ListRecentContextLifecyclesBySessionRow
		if err := rows.Scan(
			&i.RunID,
			&i.Status,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.Snapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTerminalSessionRunsNeedingContextLifecycle = `-- name: ListTerminalSessionRunsNeedingContextLifecycle :many
SELECT
  session_runs.run_id,
  session_runs.bot_id,
  session_runs.session_id,
  session_runs.fencing_token,
  session_runs.state,
  session_runs.error_code
FROM session_runs
LEFT JOIN context_lifecycles
  ON context_lifecycles.team_id = session_runs.team_id
 AND context_lifecycles.run_id = session_runs.run_id
WHERE session_runs.team_id = public.memoh_current_team_id()
  AND session_runs.state IN ('completed', 'aborted', 'failed', 'lost')
  AND (
    context_lifecycles.run_id IS NULL
    OR NOT (
      (session_runs.state = 'completed' AND context_lifecycles.status IN ('completed', 'fallback'))
      OR (session_runs.state = 'failed' AND context_lifecycles.status IN ('failed_provider', 'failed_budget'))
      OR (session_runs.state = 'aborted' AND context_lifecycles.status = 'aborted')
      OR (session_runs.state = 'lost' AND context_lifecycles.status = 'failed_provider')
    )
  )
ORDER BY session_runs.updated_at, session_runs.run_id
LIMIT $1
`

type ListTerminalSessionRunsNeedingContextLifecycleRow struct {
	RunID        pgtype.UUID `json:"run_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	FencingToken int64       `json:"fencing_token"`
	State        string      `json:"state"`
	ErrorCode    pgtype.Text `json:"error_code"`
}

func (q *Queries) ListTerminalSessionRunsNeedingContextLifecycle(ctx context.Context, batchSize int32) ([]ListTerminalSessionRunsNeedingContextLifecycleRow, error) {
	rows, err := q.db.Query(ctx, listTerminalSessionRunsNeedingContextLifecycle, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTerminalSessionRunsNeedingContextLifecycleRow
	for rows.Next() {
		var i ListTerminalSessionRunsNeedingContextLifecycleRow
		if err := rows.Scan(
			&i.RunID,
			&i.BotID,
			&i.SessionID,
			&i.FencingToken,
			&i.State,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAbortedContextLifecycleSnapshot = `-- name: UpdateAbortedContextLifecycleSnapshot :one
UPDATE context_lifecycles
SET snapshot = $1::jsonb - 'selection_decisions',
    selection_decisions = COALESCE($1::jsonb -> 'selection_decisions', selection_decisions)
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $2
  AND bot_id = $3
  AND session_id = $4
  AND status = 'aborted'
RETURNING run_id, bot_id, session_id, status, error_code, created_at
`

type UpdateAbortedContextLifecycleSnapshotParams struct {
	Snapshot  []byte      `json:"snapshot"`
	RunID     pgtype.UUID `json:"run_id"`
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type UpdateAbortedContextLifecycleSnapshotRow struct {
	RunID     pgtype.UUID        `json:"run_id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Status    string             `json:"status"`
	ErrorCode pgtype.Text        `json:"error_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateAbortedContextLifecycleSnapshot(ctx context.Context, arg UpdateAbortedContextLifecycleSnapshotParams) (UpdateAbortedContextLifecycleSnapshotRow, error) {
	row := q.db.QueryRow(ctx, updateAbortedContextLifecycleSnapshot,
		arg.Snapshot,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
	)
	var i UpdateAbortedContextLifecycleSnapshotRow
	err := row.Scan(
		&i.RunID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAbortedContextLifecycle = `-- name: UpsertAbortedContextLifecycle :one
INSERT INTO context_lifecycles (
  run_id,
  bot_id,
  session_id,
  status,
  error_code,
  snapshot,
  selection_decisions
)
VALUES (
  $1,
  $2,
  $3,
  'aborted',
  NULL,
  $4::jsonb - 'selection_decisions',
  $4::jsonb -> 'selection_decisions'
)
ON CONFLICT (run_id) DO UPDATE
SET
  status = 'aborted',
  error_code = NULL
WHERE context_lifecycles.team_id = public.memoh_current_team_id()
  AND context_lifecycles.bot_id = EXCLUDED.bot_id
  AND context_lifecycles.session_id = EXCLUDED.session_id
RETURNING run_id, bot_id, session_id, status, error_code, created_at
`

type UpsertAbortedContextLifecycleParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	Snapshot  []byte      `json:"snapshot"`
}

type UpsertAbortedContextLifecycleRow struct {
	RunID     pgtype.UUID        `json:"run_id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Status    string             `json:"status"`
	ErrorCode pgtype.Text        `json:"error_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertAbortedContextLifecycle(ctx context.Context, arg UpsertAbortedContextLifecycleParams) (UpsertAbortedContextLifecycleRow, error) {
	row := q.db.QueryRow(ctx, upsertAbortedContextLifecycle,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
		arg.Snapshot,
	)
	var i UpsertAbortedContextLifecycleRow
	err := row.Scan(
		&i.RunID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTerminalContextLifecycle = `-- name: UpsertTerminalContextLifecycle :one
INSERT INTO context_lifecycles (
  run_id,
  bot_id,
  session_id,
  status,
  error_code,
  snapshot,
  selection_decisions
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::text,
  $6::jsonb - 'selection_decisions',
  $6::jsonb -> 'selection_decisions'
)
ON CONFLICT (run_id) DO UPDATE
SET
  status = EXCLUDED.status,
  error_code = CASE
    WHEN $7::boolean
      OR context_lifecycles.status IS DISTINCT FROM EXCLUDED.status
      THEN EXCLUDED.error_code
    ELSE COALESCE(context_lifecycles.error_code, EXCLUDED.error_code)
  END,
  snapshot = CASE
    WHEN $8::boolean THEN EXCLUDED.snapshot
    ELSE context_lifecycles.snapshot
  END,
  selection_decisions = CASE
    WHEN $8::boolean
      THEN COALESCE(EXCLUDED.selection_decisions, context_lifecycles.selection_decisions)
    ELSE context_lifecycles.selection_decisions
  END
WHERE context_lifecycles.team_id = public.memoh_current_team_id()
  AND context_lifecycles.team_id = EXCLUDED.team_id
  AND context_lifecycles.bot_id = EXCLUDED.bot_id
  AND context_lifecycles.session_id = EXCLUDED.session_id
RETURNING run_id, bot_id, session_id, status, error_code, created_at
`

type UpsertTerminalContextLifecycleParams struct {
	RunID            pgtype.UUID `json:"run_id"`
	BotID            pgtype.UUID `json:"bot_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	Status           string      `json:"status"`
	ErrorCode        pgtype.Text `json:"error_code"`
	Snapshot         []byte      `json:"snapshot"`
	ReplaceErrorCode bool        `json:"replace_error_code"`
	ReplaceSnapshot  bool        `json:"replace_snapshot"`
}

type UpsertTerminalContextLifecycleRow struct {
	RunID     pgtype.UUID        `json:"run_id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Status    string             `json:"status"`
	ErrorCode pgtype.Text        `json:"error_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertTerminalContextLifecycle(ctx context.Context, arg UpsertTerminalContextLifecycleParams) (UpsertTerminalContextLifecycleRow, error) {
	row := q.db.QueryRow(ctx, upsertTerminalContextLifecycle,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
		arg.Status,
		arg.ErrorCode,
		arg.Snapshot,
		arg.ReplaceErrorCode,
		arg.ReplaceSnapshot,
	)
	var i UpsertTerminalContextLifecycleRow
	err := row.Scan(
		&i.RunID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}
