// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPushDelivery = `-- name: ClaimPushDelivery :one
INSERT INTO push_deliveries (endpoint_id, dedupe_key, payload_hash) VALUES ($1, $2, $3)
ON CONFLICT (team_id, endpoint_id, dedupe_key) DO UPDATE
SET status = 'sending', attempts = push_deliveries.attempts + 1, error_code = '', updated_at = now()
WHERE push_deliveries.status = 'failed' AND push_deliveries.payload_hash = EXCLUDED.payload_hash
RETURNING id, team_id, endpoint_id, dedupe_key, payload_hash, status, attempts, error_code, created_at, updated_at
`

type ClaimPushDeliveryParams struct {
	EndpointID  pgtype.UUID `json:"endpoint_id"`
	DedupeKey   string      `json:"dedupe_key"`
	PayloadHash string      `json:"payload_hash"`
}

func (q *Queries) ClaimPushDelivery(ctx context.Context, arg ClaimPushDeliveryParams) (PushDelivery, error) {
	row := q.db.QueryRow(ctx, claimPushDelivery, arg.EndpointID, arg.DedupeKey, arg.PayloadHash)
	var i PushDelivery
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.EndpointID,
		&i.DedupeKey,
		&i.PayloadHash,
		&i.Status,
		&i.Attempts,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPushEndpoint = `-- name: CreatePushEndpoint :one
INSERT INTO push_endpoints (user_id, bot_id, channel_identity_id, name, token_hash)
VALUES ($1, $2, $3, $4, $5) RETURNING id, team_id, user_id, bot_id, channel_identity_id, name, token_hash, enabled, created_at, updated_at
`

type CreatePushEndpointParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	BotID             pgtype.UUID `json:"bot_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
	Name              string      `json:"name"`
	TokenHash         string      `json:"token_hash"`
}

func (q *Queries) CreatePushEndpoint(ctx context.Context, arg CreatePushEndpointParams) (PushEndpoint, error) {
	row := q.db.QueryRow(ctx, createPushEndpoint,
		arg.UserID,
		arg.BotID,
		arg.ChannelIdentityID,
		arg.Name,
		arg.TokenHash,
	)
	var i PushEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.BotID,
		&i.ChannelIdentityID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePushEndpoint = `-- name: DeletePushEndpoint :execrows
DELETE FROM push_endpoints WHERE team_id = public.memoh_current_team_id() AND id = $1 AND user_id = $2
`

type DeletePushEndpointParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePushEndpoint(ctx context.Context, arg DeletePushEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushEndpoint, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishPushDelivery = `-- name: FinishPushDelivery :exec
UPDATE push_deliveries SET status = $2, error_code = $3, updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1 AND status = 'sending'
`

type FinishPushDeliveryParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	ErrorCode string      `json:"error_code"`
}

func (q *Queries) FinishPushDelivery(ctx context.Context, arg FinishPushDeliveryParams) error {
	_, err := q.db.Exec(ctx, finishPushDelivery, arg.ID, arg.Status, arg.ErrorCode)
	return err
}

const getPushDelivery = `-- name: GetPushDelivery :one
SELECT id, team_id, endpoint_id, dedupe_key, payload_hash, status, attempts, error_code, created_at, updated_at FROM push_deliveries
WHERE team_id = public.memoh_current_team_id() AND endpoint_id = $1 AND dedupe_key = $2
`

type GetPushDeliveryParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	DedupeKey  string      `json:"dedupe_key"`
}

func (q *Queries) GetPushDelivery(ctx context.Context, arg GetPushDeliveryParams) (PushDelivery, error) {
	row := q.db.QueryRow(ctx, getPushDelivery, arg.EndpointID, arg.DedupeKey)
	var i PushDelivery
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.EndpointID,
		&i.DedupeKey,
		&i.PayloadHash,
		&i.Status,
		&i.Attempts,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPushEndpoint = `-- name: GetPushEndpoint :one
SELECT id, team_id, user_id, bot_id, channel_identity_id, name, token_hash, enabled, created_at, updated_at FROM push_endpoints WHERE team_id = public.memoh_current_team_id() AND id = $1
`

func (q *Queries) GetPushEndpoint(ctx context.Context, id pgtype.UUID) (PushEndpoint, error) {
	row := q.db.QueryRow(ctx, getPushEndpoint, id)
	var i PushEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.BotID,
		&i.ChannelIdentityID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPushRecipientTarget = `-- name: GetPushRecipientTarget :one
SELECT r.default_reply_target
FROM bot_channel_routes r
JOIN channel_identities ci ON ci.team_id = r.team_id AND ci.channel_type = r.channel_type
WHERE r.team_id = public.memoh_current_team_id()
  AND r.bot_id = $1 AND r.channel_config_id = $2
  AND ci.id = $3
  AND r.conversation_type = 'private'
  AND r.metadata->>'sender_id' = ci.channel_subject_id
  AND COALESCE(r.default_reply_target, '') <> ''
ORDER BY r.updated_at DESC LIMIT 1
`

type GetPushRecipientTargetParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	ChannelConfigID   pgtype.UUID `json:"channel_config_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) GetPushRecipientTarget(ctx context.Context, arg GetPushRecipientTargetParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getPushRecipientTarget, arg.BotID, arg.ChannelConfigID, arg.ChannelIdentityID)
	var default_reply_target pgtype.Text
	err := row.Scan(&default_reply_target)
	return default_reply_target, err
}

const listPushDeliveries = `-- name: ListPushDeliveries :many
SELECT id, team_id, endpoint_id, dedupe_key, payload_hash, status, attempts, error_code, created_at, updated_at FROM push_deliveries WHERE team_id = public.memoh_current_team_id() AND endpoint_id = $1
ORDER BY updated_at DESC LIMIT 20
`

func (q *Queries) ListPushDeliveries(ctx context.Context, endpointID pgtype.UUID) ([]PushDelivery, error) {
	rows, err := q.db.Query(ctx, listPushDeliveries, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushDelivery
	for rows.Next() {
		var i PushDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.EndpointID,
			&i.DedupeKey,
			&i.PayloadHash,
			&i.Status,
			&i.Attempts,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushEndpoints = `-- name: ListPushEndpoints :many
SELECT id, team_id, user_id, bot_id, channel_identity_id, name, token_hash, enabled, created_at, updated_at FROM push_endpoints
WHERE team_id = public.memoh_current_team_id() AND user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPushEndpoints(ctx context.Context, userID pgtype.UUID) ([]PushEndpoint, error) {
	rows, err := q.db.Query(ctx, listPushEndpoints, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushEndpoint
	for rows.Next() {
		var i PushEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.BotID,
			&i.ChannelIdentityID,
			&i.Name,
			&i.TokenHash,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prunePushDeliveries = `-- name: PrunePushDeliveries :exec
DELETE FROM push_deliveries WHERE team_id = public.memoh_current_team_id() AND endpoint_id = $1
AND updated_at < now() - interval '30 days'
`

func (q *Queries) PrunePushDeliveries(ctx context.Context, endpointID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, prunePushDeliveries, endpointID)
	return err
}

const rotatePushEndpointKey = `-- name: RotatePushEndpointKey :one
UPDATE push_endpoints SET token_hash = $3, updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1 AND user_id = $2 RETURNING id, team_id, user_id, bot_id, channel_identity_id, name, token_hash, enabled, created_at, updated_at
`

type RotatePushEndpointKeyParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) RotatePushEndpointKey(ctx context.Context, arg RotatePushEndpointKeyParams) (PushEndpoint, error) {
	row := q.db.QueryRow(ctx, rotatePushEndpointKey, arg.ID, arg.UserID, arg.TokenHash)
	var i PushEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.BotID,
		&i.ChannelIdentityID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePushEndpoint = `-- name: UpdatePushEndpoint :one
UPDATE push_endpoints SET enabled = $3, updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1 AND user_id = $2 RETURNING id, team_id, user_id, bot_id, channel_identity_id, name, token_hash, enabled, created_at, updated_at
`

type UpdatePushEndpointParams struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpdatePushEndpoint(ctx context.Context, arg UpdatePushEndpointParams) (PushEndpoint, error) {
	row := q.db.QueryRow(ctx, updatePushEndpoint, arg.ID, arg.UserID, arg.Enabled)
	var i PushEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.BotID,
		&i.ChannelIdentityID,
		&i.Name,
		&i.TokenHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
