// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessionEvents = `-- name: CountSessionEvents :one
SELECT COUNT(*) FROM bot_session_events
WHERE team_id = public.memoh_current_team_id() AND session_id = $1
`

func (q *Queries) CountSessionEvents(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionEvents, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSessionEvent = `-- name: CreateSessionEvent :one
INSERT INTO bot_session_events (
  bot_id,
  session_id,
  event_kind,
  event_data,
  external_message_id,
  sender_channel_identity_id,
  received_at_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreateSessionEventParams struct {
	BotID                   pgtype.UUID `json:"bot_id"`
	SessionID               pgtype.UUID `json:"session_id"`
	EventKind               string      `json:"event_kind"`
	EventData               []byte      `json:"event_data"`
	ExternalMessageID       pgtype.Text `json:"external_message_id"`
	SenderChannelIdentityID pgtype.UUID `json:"sender_channel_identity_id"`
	ReceivedAtMs            int64       `json:"received_at_ms"`
}

func (q *Queries) CreateSessionEvent(ctx context.Context, arg CreateSessionEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSessionEvent,
		arg.BotID,
		arg.SessionID,
		arg.EventKind,
		arg.EventData,
		arg.ExternalMessageID,
		arg.SenderChannelIdentityID,
		arg.ReceivedAtMs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSessionEventsByBot = `-- name: DeleteSessionEventsByBot :exec
DELETE FROM bot_session_events
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
`

func (q *Queries) DeleteSessionEventsByBot(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionEventsByBot, botID)
	return err
}

const listSessionEventsByBot = `-- name: ListSessionEventsByBot :many
SELECT id, bot_id, session_id, event_kind, event_data, external_message_id, sender_channel_identity_id, received_at_ms, created_at, team_id FROM bot_session_events
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
ORDER BY received_at_ms ASC, id ASC
`

func (q *Queries) ListSessionEventsByBot(ctx context.Context, botID pgtype.UUID) ([]BotSessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEventsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionEvent
	for rows.Next() {
		var i BotSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.EventKind,
			&i.EventData,
			&i.ExternalMessageID,
			&i.SenderChannelIdentityID,
			&i.ReceivedAtMs,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsBySession = `-- name: ListSessionEventsBySession :many
SELECT id, bot_id, session_id, event_kind, event_data, external_message_id, sender_channel_identity_id, received_at_ms, created_at, team_id FROM bot_session_events
WHERE team_id = public.memoh_current_team_id() AND session_id = $1
ORDER BY received_at_ms ASC, created_at ASC, id ASC
`

func (q *Queries) ListSessionEventsBySession(ctx context.Context, sessionID pgtype.UUID) ([]BotSessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionEvent
	for rows.Next() {
		var i BotSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.EventKind,
			&i.EventData,
			&i.ExternalMessageID,
			&i.SenderChannelIdentityID,
			&i.ReceivedAtMs,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsBySessionAfter = `-- name: ListSessionEventsBySessionAfter :many
SELECT id, bot_id, session_id, event_kind, event_data, external_message_id, sender_channel_identity_id, received_at_ms, created_at, team_id FROM bot_session_events
WHERE team_id = public.memoh_current_team_id() AND session_id = $1 AND received_at_ms >= $2
ORDER BY received_at_ms ASC, created_at ASC, id ASC
`

type ListSessionEventsBySessionAfterParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	ReceivedAtMs int64       `json:"received_at_ms"`
}

func (q *Queries) ListSessionEventsBySessionAfter(ctx context.Context, arg ListSessionEventsBySessionAfterParams) ([]BotSessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEventsBySessionAfter, arg.SessionID, arg.ReceivedAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionEvent
	for rows.Next() {
		var i BotSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.EventKind,
			&i.EventData,
			&i.ExternalMessageID,
			&i.SenderChannelIdentityID,
			&i.ReceivedAtMs,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsBySessionPageBeforeWithinBytes = `-- name: ListSessionEventsBySessionPageBeforeWithinBytes :many
WITH post_coverage_ids AS MATERIALIZED (
  SELECT DISTINCT changed.external_message_id
  FROM bot_session_events changed
  WHERE changed.team_id = public.memoh_current_team_id()
    AND changed.session_id = $1
    AND changed.external_message_id IS NOT NULL
    AND $2::jsonb ? changed.external_message_id
    AND changed.received_at_ms > COALESCE(
      ($2::jsonb ->> changed.external_message_id)::BIGINT,
      0
    )
), candidates AS MATERIALIZED (
  SELECT
    event.id,
    event.received_at_ms,
    event.created_at,
    octet_length(event.event_data::text)::BIGINT AS payload_bytes
  FROM bot_session_events event
  LEFT JOIN post_coverage_ids changed
    ON changed.external_message_id = event.external_message_id
  WHERE event.team_id = public.memoh_current_team_id()
    AND event.session_id = $1
    AND (
      NOT $3::boolean
      OR (event.received_at_ms, event.created_at, event.id) < (
        $4::BIGINT,
        $5::TIMESTAMPTZ,
        $6::UUID
      )
    )
    AND (
      event.external_message_id IS NULL
      OR NOT ($2::jsonb ? event.external_message_id)
      OR event.received_at_ms > COALESCE(
        ($2::jsonb ->> event.external_message_id)::BIGINT,
        0
      )
      OR changed.external_message_id IS NOT NULL
    )
), ranked AS MATERIALIZED (
  SELECT
    candidates.id, candidates.received_at_ms, candidates.created_at, candidates.payload_bytes,
    SUM(payload_bytes) OVER (
      ORDER BY received_at_ms DESC, created_at DESC, id DESC
    )::BIGINT AS cumulative_bytes
  FROM candidates
), admitted AS MATERIALIZED (
  SELECT id, received_at_ms, created_at, payload_bytes, cumulative_bytes
  FROM ranked
  WHERE cumulative_bytes <= $7::BIGINT
  ORDER BY received_at_ms DESC, created_at DESC, id DESC
  LIMIT $8
)
SELECT
  event.id,
  event.team_id,
  event.bot_id,
  event.session_id,
  event.event_kind,
  event.event_data,
  event.external_message_id,
  event.sender_channel_identity_id,
  event.received_at_ms,
  event.created_at,
  admitted.payload_bytes,
  admitted.cumulative_bytes
FROM admitted
JOIN bot_session_events event ON event.id = admitted.id
ORDER BY event.received_at_ms DESC, event.created_at DESC, event.id DESC
`

type ListSessionEventsBySessionPageBeforeWithinBytesParams struct {
	SessionID               pgtype.UUID        `json:"session_id"`
	CoveredExternalMessages []byte             `json:"covered_external_messages"`
	HasCursor               bool               `json:"has_cursor"`
	BeforeReceivedAtMs      int64              `json:"before_received_at_ms"`
	BeforeCreatedAt         pgtype.Timestamptz `json:"before_created_at"`
	BeforeID                pgtype.UUID        `json:"before_id"`
	MaxBytes                int64              `json:"max_bytes"`
	PageSize                int32              `json:"page_size"`
}

type ListSessionEventsBySessionPageBeforeWithinBytesRow struct {
	ID                      pgtype.UUID        `json:"id"`
	TeamID                  pgtype.UUID        `json:"team_id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	EventKind               string             `json:"event_kind"`
	EventData               []byte             `json:"event_data"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	ReceivedAtMs            int64              `json:"received_at_ms"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PayloadBytes            int64              `json:"payload_bytes"`
	CumulativeBytes         int64              `json:"cumulative_bytes"`
}

// Replay reads newest-first with a stable keyset and a hard page-byte budget.
// Covered message/edit payloads are excluded in SQL before event_data reaches
// the process. If a covered message has a post-frontier mutation, its complete
// event chain remains eligible so edit projection still has its base node.
func (q *Queries) ListSessionEventsBySessionPageBeforeWithinBytes(ctx context.Context, arg ListSessionEventsBySessionPageBeforeWithinBytesParams) ([]ListSessionEventsBySessionPageBeforeWithinBytesRow, error) {
	rows, err := q.db.Query(ctx, listSessionEventsBySessionPageBeforeWithinBytes,
		arg.SessionID,
		arg.CoveredExternalMessages,
		arg.HasCursor,
		arg.BeforeReceivedAtMs,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.MaxBytes,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionEventsBySessionPageBeforeWithinBytesRow
	for rows.Next() {
		var i ListSessionEventsBySessionPageBeforeWithinBytesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.EventKind,
			&i.EventData,
			&i.ExternalMessageID,
			&i.SenderChannelIdentityID,
			&i.ReceivedAtMs,
			&i.CreatedAt,
			&i.PayloadBytes,
			&i.CumulativeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSessionEventCursor = `-- name: NextSessionEventCursor :one
SELECT nextval('bot_session_event_cursor_seq')::bigint
`

func (q *Queries) NextSessionEventCursor(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionEventCursor)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
