// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const admitLockedSessionRun = `-- name: AdmitLockedSessionRun :one
WITH target_session AS MATERIALIZED (
  SELECT s.id AS session_id
  FROM bot_sessions AS s
  JOIN bots bot ON bot.team_id = s.team_id AND bot.id = s.bot_id
  WHERE s.team_id = public.memoh_current_team_id()
    AND s.id = $7
    AND s.bot_id = $2
    AND s.deleted_at IS NULL
    AND bot.status <> 'deleting'
    AND (
      bot.runtime_reset_expires_at IS NULL
      OR bot.runtime_reset_expires_at <= clock_timestamp()
    )
    AND (
      s.runtime_reset_expires_at IS NULL
      OR s.runtime_reset_expires_at <= clock_timestamp()
    )
),
existing AS (
  SELECT 1 AS present
  FROM session_runs AS prior
  WHERE prior.team_id = public.memoh_current_team_id()
    AND prior.session_id = $7
    AND prior.invocation_id = $3
),
allocated_position AS (
  UPDATE bot_sessions AS s
  SET next_turn_position = s.next_turn_position + 1
  FROM target_session
  WHERE s.team_id = public.memoh_current_team_id()
    AND s.id = target_session.session_id
    AND NOT EXISTS (SELECT 1 FROM existing)
  RETURNING (s.next_turn_position - 1)::bigint AS turn_position
)
INSERT INTO session_runs (
  run_id,
  bot_id,
  session_id,
  invocation_id,
  turn_id,
  turn_position,
  state,
  input_json,
  input_fingerprint
)
SELECT
  $1,
  $2,
  target_session.session_id,
  $3,
  $4,
  allocated_position.turn_position,
  'accepted',
  $5,
  $6
FROM target_session
CROSS JOIN allocated_position
ON CONFLICT (team_id, session_id, invocation_id) DO NOTHING
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

type AdmitLockedSessionRunParams struct {
	RunID            pgtype.UUID `json:"run_id"`
	BotID            pgtype.UUID `json:"bot_id"`
	InvocationID     string      `json:"invocation_id"`
	TurnID           pgtype.UUID `json:"turn_id"`
	InputJson        []byte      `json:"input_json"`
	InputFingerprint string      `json:"input_fingerprint"`
	SessionID        pgtype.UUID `json:"session_id"`
}

// Durable admission. There is no queue: SR-OWN-001 permits answering busy, so a
// second concurrent invocation is rejected rather than parked.
//
// Busy is rejected in two layers. The adapter's indexed pre-read catches the
// common case before this statement runs at all, so contended submissions never
// reach the write path. This statement handles only what slipped through that
// unlocked read: session_runs_single_active raises, and because the adapter
// runs this after a separate parent lock in one transaction, rollback takes the
// allocated turn position with it and leaves nothing for the caller to clean up.
//
// Returns no rows when this invocation_id was already admitted — ON CONFLICT
// keeps the ordinary retry path free of errors, which matters because channel
// redelivery makes it a routine event — or when the session does not exist. The
// caller re-selects by invocation to tell those two apart.
//
// A position is allocated only for an admission that can still succeed: never
// for a known duplicate (the NOT EXISTS guard below) and never for a rejected
// one (the rollback). The single exception is two callers racing on the *same*
// invocation_id, where both pass the guard against the statement snapshot and
// the loser's increment commits with no row. That leaves a gap in turn_position,
// which is ordering-only and never read as a count.
func (q *Queries) AdmitLockedSessionRun(ctx context.Context, arg AdmitLockedSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, admitLockedSessionRun,
		arg.RunID,
		arg.BotID,
		arg.InvocationID,
		arg.TurnID,
		arg.InputJson,
		arg.InputFingerprint,
		arg.SessionID,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimLockedSessionRun = `-- name: ClaimLockedSessionRun :one
WITH target_session AS MATERIALIZED (
  SELECT session.id
  FROM bot_sessions session
  JOIN bots bot ON bot.team_id = session.team_id AND bot.id = session.bot_id
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.id = $6
    AND session.bot_id = $5
    AND session.deleted_at IS NULL
    AND bot.status <> 'deleting'
    AND (bot.runtime_reset_expires_at IS NULL OR bot.runtime_reset_expires_at <= clock_timestamp())
    AND (session.runtime_reset_expires_at IS NULL OR session.runtime_reset_expires_at <= clock_timestamp())
  FOR UPDATE OF session
)
UPDATE session_runs run
SET owner_id = $1,
    owner_since = now(),
    fencing_token = $2,
    live_generation = $3,
    state = 'running',
    updated_at = now()
FROM target_session target
WHERE run.team_id = public.memoh_current_team_id()
  AND run.run_id = $4
  AND run.bot_id = $5
  AND run.session_id = target.id
  AND run.state = 'accepted'
  AND run.fencing_token < $2
RETURNING run.run_id, run.team_id, run.bot_id, run.session_id, run.invocation_id, run.turn_id, run.turn_position, run.state, run.input_json, run.input_fingerprint, run.owner_id, run.fencing_token, run.owner_since, run.live_generation, run.abort_requested_at, run.proposed_terminal_state, run.proposed_error_code, run.proposed_error_message, run.finish_proposed_at, run.error_code, run.error_message, run.created_at, run.updated_at
`

type ClaimLockedSessionRunParams struct {
	OwnerID        pgtype.Text `json:"owner_id"`
	FencingToken   int64       `json:"fencing_token"`
	LiveGeneration pgtype.Text `json:"live_generation"`
	RunID          pgtype.UUID `json:"run_id"`
	BotID          pgtype.UUID `json:"bot_id"`
	SessionID      pgtype.UUID `json:"session_id"`
}

// Ownership change: the only write that touches owner_id, fencing_token,
// owner_since and live_generation. live_generation is stamped once here and
// never updated, which keeps idx_session_runs_recovery a stable keyset cursor.
// Fencing tokens come from a monotonic sequence, so a newer claim always
// carries a strictly larger token than the one it replaces.
func (q *Queries) ClaimLockedSessionRun(ctx context.Context, arg ClaimLockedSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, claimLockedSessionRun,
		arg.OwnerID,
		arg.FencingToken,
		arg.LiveGeneration,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeSessionRun = `-- name: FinalizeSessionRun :one
UPDATE session_runs
SET state = CASE
        WHEN state = 'finishing' THEN proposed_terminal_state
        WHEN $1::text = 'lost' AND abort_requested_at IS NOT NULL THEN 'aborted'
        ELSE $1::text
    END,
    error_code = CASE
        WHEN state = 'finishing' THEN proposed_error_code
        WHEN $1::text = 'lost' AND abort_requested_at IS NOT NULL THEN NULL
        ELSE $2::text
    END,
    error_message = CASE
        WHEN state = 'finishing' THEN proposed_error_message
        WHEN $1::text = 'lost' AND abort_requested_at IS NOT NULL THEN NULL
        ELSE $3::text
    END,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $4
  AND fencing_token = $5
  AND state IN ('accepted', 'running', 'waiting_decision', 'finishing')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

type FinalizeSessionRunParams struct {
	State        string      `json:"state"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	RunID        pgtype.UUID `json:"run_id"`
	FencingToken int64       `json:"fencing_token"`
}

// Fenced idempotent terminal write, shared by the owner (completed / aborted /
// failed) and the reaper (lost). Zero rows affected means the transition was
// already applied or a newer owner superseded this token; neither is an error.
func (q *Queries) FinalizeSessionRun(ctx context.Context, arg FinalizeSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, finalizeSessionRun,
		arg.State,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.RunID,
		arg.FencingToken,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionRun = `-- name: GetActiveSessionRun :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
  AND state IN ('accepted', 'running', 'waiting_decision', 'finishing')
`

func (q *Queries) GetActiveSessionRun(ctx context.Context, sessionID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getActiveSessionRun, sessionID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSessionRun = `-- name: GetLatestSessionRun :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
ORDER BY created_at DESC, run_id DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionRun(ctx context.Context, sessionID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getLatestSessionRun, sessionID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionRun = `-- name: GetSessionRun :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
`

func (q *Queries) GetSessionRun(ctx context.Context, runID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getSessionRun, runID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionRunByInvocation = `-- name: GetSessionRunByInvocation :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
  AND invocation_id = $2
`

type GetSessionRunByInvocationParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	InvocationID string      `json:"invocation_id"`
}

func (q *Queries) GetSessionRunByInvocation(ctx context.Context, arg GetSessionRunByInvocationParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getSessionRunByInvocation, arg.SessionID, arg.InvocationID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSessionRunsByBot = `-- name: ListActiveSessionRunsByBot :many
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND state IN ('accepted', 'running', 'waiting_decision', 'finishing')
ORDER BY session_id, run_id
`

func (q *Queries) ListActiveSessionRunsByBot(ctx context.Context, botID pgtype.UUID) ([]SessionRun, error) {
	rows, err := q.db.Query(ctx, listActiveSessionRunsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionRun
	for rows.Next() {
		var i SessionRun
		if err := rows.Scan(
			&i.RunID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.InvocationID,
			&i.TurnID,
			&i.TurnPosition,
			&i.State,
			&i.InputJson,
			&i.InputFingerprint,
			&i.OwnerID,
			&i.FencingToken,
			&i.OwnerSince,
			&i.LiveGeneration,
			&i.AbortRequestedAt,
			&i.ProposedTerminalState,
			&i.ProposedErrorCode,
			&i.ProposedErrorMessage,
			&i.FinishProposedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedSessionRuns = `-- name: ListOrphanedSessionRuns :many
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND state = 'accepted'
  AND owner_id IS NULL
  AND created_at < now() - make_interval(secs => $1::double precision)
ORDER BY created_at, run_id
LIMIT $2
`

type ListOrphanedSessionRunsParams struct {
	GraceSeconds float64 `json:"grace_seconds"`
	BatchSize    int32   `json:"batch_size"`
}

// Admission committed but the process died before reserving the run in the live
// backend. No lease exists, so these never appear as expiry candidates and no
// generation change implicates them. A single leader reaper reads this, so no
// row locking is needed.
func (q *Queries) ListOrphanedSessionRuns(ctx context.Context, arg ListOrphanedSessionRunsParams) ([]SessionRun, error) {
	rows, err := q.db.Query(ctx, listOrphanedSessionRuns, arg.GraceSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionRun
	for rows.Next() {
		var i SessionRun
		if err := rows.Scan(
			&i.RunID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.InvocationID,
			&i.TurnID,
			&i.TurnPosition,
			&i.State,
			&i.InputJson,
			&i.InputFingerprint,
			&i.OwnerID,
			&i.FencingToken,
			&i.OwnerSince,
			&i.LiveGeneration,
			&i.AbortRequestedAt,
			&i.ProposedTerminalState,
			&i.ProposedErrorCode,
			&i.ProposedErrorMessage,
			&i.FinishProposedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleGenerationSessionRuns = `-- name: ListStaleGenerationSessionRuns :many
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND state IN ('accepted', 'running', 'waiting_decision', 'finishing')
  AND live_generation IS NOT NULL
  AND live_generation <> $1
  AND (
    $2::text IS NULL
    OR live_generation > $2
    OR (live_generation = $2 AND run_id > $3)
  )
ORDER BY live_generation, run_id
LIMIT $4
`

type ListStaleGenerationSessionRunsParams struct {
	CurrentGeneration pgtype.Text `json:"current_generation"`
	CursorGeneration  pgtype.Text `json:"cursor_generation"`
	CursorRunID       pgtype.UUID `json:"cursor_run_id"`
	BatchSize         int32       `json:"batch_size"`
}

// Fail-closed recovery sweep. Matching on "not the current generation" rather
// than one specific old value means a backend lost twice in quick succession
// cannot strand rows from the older incarnation. Orphans are excluded by
// live_generation IS NOT NULL: they were never claimed.
//
// A NULL cursor means "start from the beginning" and must be spelled out: the
// keyset comparison below is NULL for every row when the cursor is NULL, so
// without this branch the first batch of every sweep matches nothing, and a
// sweep that never returns a full batch never advances past it either.
func (q *Queries) ListStaleGenerationSessionRuns(ctx context.Context, arg ListStaleGenerationSessionRunsParams) ([]SessionRun, error) {
	rows, err := q.db.Query(ctx, listStaleGenerationSessionRuns,
		arg.CurrentGeneration,
		arg.CursorGeneration,
		arg.CursorRunID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionRun
	for rows.Next() {
		var i SessionRun
		if err := rows.Scan(
			&i.RunID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.InvocationID,
			&i.TurnID,
			&i.TurnPosition,
			&i.State,
			&i.InputJson,
			&i.InputFingerprint,
			&i.OwnerID,
			&i.FencingToken,
			&i.OwnerSince,
			&i.LiveGeneration,
			&i.AbortRequestedAt,
			&i.ProposedTerminalState,
			&i.ProposedErrorCode,
			&i.ProposedErrorMessage,
			&i.FinishProposedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveSessionRunForHistoryReset = `-- name: LockActiveSessionRunForHistoryReset :one
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND bot_id = $2
  AND session_id = $3
  AND fencing_token = $4
  AND state IN ('accepted', 'running', 'waiting_decision', 'finishing')
FOR UPDATE
`

type LockActiveSessionRunForHistoryResetParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	FencingToken int64       `json:"fencing_token"`
}

// The reset finalizer already holds the bot parent lock. Locking the target
// run in a fresh statement makes the old fencing token/state an atomic
// predicate for advancing the session persistence fence and terminalizing it.
func (q *Queries) LockActiveSessionRunForHistoryReset(ctx context.Context, arg LockActiveSessionRunForHistoryResetParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, lockActiveSessionRunForHistoryReset,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
		arg.FencingToken,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockBotForSessionRunClaim = `-- name: LockBotForSessionRunClaim :one
SELECT id
FROM bots
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
FOR UPDATE
`

// Claim uses a real transaction and a fresh statement after this parent lock.
// Reset acquisition takes the same lock, so neither can cross the other's
// committed gate using a statement snapshot captured while waiting.
func (q *Queries) LockBotForSessionRunClaim(ctx context.Context, botID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBotForSessionRunClaim, botID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockSessionRunForAgentStepCommit = `-- name: LockSessionRunForAgentStepCommit :one
SELECT run_id
FROM session_runs
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND bot_id = $2
  AND session_id = $3
  AND fencing_token = $4
  AND state IN ('running', 'waiting_decision')
  AND ($5::boolean OR abort_requested_at IS NULL)
FOR UPDATE
`

type LockSessionRunForAgentStepCommitParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	FencingToken int64       `json:"fencing_token"`
	Interrupted  bool        `json:"interrupted"`
}

// Complete steps must precede abort intent; interrupted checkpoints only need
// the same active owner because some cancellation paths do not record intent.
func (q *Queries) LockSessionRunForAgentStepCommit(ctx context.Context, arg LockSessionRunForAgentStepCommitParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockSessionRunForAgentStepCommit,
		arg.RunID,
		arg.BotID,
		arg.SessionID,
		arg.FencingToken,
		arg.Interrupted,
	)
	var run_id pgtype.UUID
	err := row.Scan(&run_id)
	return run_id, err
}

const nextSessionRunFencingToken = `-- name: NextSessionRunFencingToken :one
SELECT nextval('session_runtime_fencing_token_seq')::bigint AS token
`

func (q *Queries) NextSessionRunFencingToken(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionRunFencingToken)
	var token int64
	err := row.Scan(&token)
	return token, err
}

const prepareSessionRunFinish = `-- name: PrepareSessionRunFinish :one
UPDATE session_runs
SET state = 'finishing',
    proposed_terminal_state = COALESCE(
        proposed_terminal_state,
        CASE
            WHEN abort_requested_at IS NOT NULL THEN 'aborted'
            ELSE $1::text
        END
    ),
    proposed_error_code = CASE
        WHEN proposed_terminal_state IS NOT NULL THEN proposed_error_code
        WHEN abort_requested_at IS NOT NULL THEN NULL
        ELSE $2::text
    END,
    proposed_error_message = CASE
        WHEN proposed_terminal_state IS NOT NULL THEN proposed_error_message
        WHEN abort_requested_at IS NOT NULL THEN NULL
        ELSE $3::text
    END,
    finish_proposed_at = COALESCE(finish_proposed_at, now()),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $4
  AND fencing_token = $5
  AND (
      state IN ('running', 'finishing')
      OR ($6::boolean AND state = 'waiting_decision')
  )
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

type PrepareSessionRunFinishParams struct {
	ProposedTerminalState string      `json:"proposed_terminal_state"`
	ProposedErrorCode     pgtype.Text `json:"proposed_error_code"`
	ProposedErrorMessage  pgtype.Text `json:"proposed_error_message"`
	RunID                 pgtype.UUID `json:"run_id"`
	FencingToken          int64       `json:"fencing_token"`
	AllowWaitingDecision  bool        `json:"allow_waiting_decision"`
}

// Persist the terminal proposal before the live projection enters finishing.
// Replays preserve the first proposal. A concurrent abort intent wins so an
// owner cannot complete a run after the user has durably requested its stop.
func (q *Queries) PrepareSessionRunFinish(ctx context.Context, arg PrepareSessionRunFinishParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, prepareSessionRunFinish,
		arg.ProposedTerminalState,
		arg.ProposedErrorCode,
		arg.ProposedErrorMessage,
		arg.RunID,
		arg.FencingToken,
		arg.AllowWaitingDecision,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimWaitingDecisionSessionRun = `-- name: ReclaimWaitingDecisionSessionRun :one
UPDATE session_runs
SET owner_id = $1,
    owner_since = now(),
    fencing_token = $2,
    live_generation = $3,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $4
  AND state = 'waiting_decision'
  AND fencing_token = $5
  AND fencing_token < $2
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

type ReclaimWaitingDecisionSessionRunParams struct {
	OwnerID              pgtype.Text `json:"owner_id"`
	NewFencingToken      int64       `json:"new_fencing_token"`
	LiveGeneration       pgtype.Text `json:"live_generation"`
	RunID                pgtype.UUID `json:"run_id"`
	PreviousFencingToken int64       `json:"previous_fencing_token"`
}

// Recovery advances both durable ownership and the backend incarnation while
// preserving waiting_decision. The previous token is the CAS guard; the new
// token must be strictly newer so a stale reaper can never move ownership
// backwards.
func (q *Queries) ReclaimWaitingDecisionSessionRun(ctx context.Context, arg ReclaimWaitingDecisionSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, reclaimWaitingDecisionSessionRun,
		arg.OwnerID,
		arg.NewFencingToken,
		arg.LiveGeneration,
		arg.RunID,
		arg.PreviousFencingToken,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestSessionRunAbort = `-- name: RequestSessionRunAbort :one
UPDATE session_runs
SET abort_requested_at = COALESCE(abort_requested_at, now()),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND state IN ('accepted', 'running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

// Not fenced: abort is a user intent that may arrive at any instance, and the
// owner applies it. Repeating it keeps the first request time.
func (q *Queries) RequestSessionRunAbort(ctx context.Context, runID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, requestSessionRunAbort, runID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeSessionRun = `-- name: ResumeSessionRun :one
UPDATE session_runs
SET state = 'running',
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND fencing_token = $2
  AND state IN ('running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

type ResumeSessionRunParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	FencingToken int64       `json:"fencing_token"`
}

func (q *Queries) ResumeSessionRun(ctx context.Context, arg ResumeSessionRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, resumeSessionRun, arg.RunID, arg.FencingToken)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSessionRunWaitingDecision = `-- name: SetSessionRunWaitingDecision :one
UPDATE session_runs
SET state = 'waiting_decision',
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND fencing_token = $2
  AND state IN ('running', 'waiting_decision')
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, abort_requested_at, proposed_terminal_state, proposed_error_code, proposed_error_message, finish_proposed_at, error_code, error_message, created_at, updated_at
`

type SetSessionRunWaitingDecisionParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	FencingToken int64       `json:"fencing_token"`
}

func (q *Queries) SetSessionRunWaitingDecision(ctx context.Context, arg SetSessionRunWaitingDecisionParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, setSessionRunWaitingDecision, arg.RunID, arg.FencingToken)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.AbortRequestedAt,
		&i.ProposedTerminalState,
		&i.ProposedErrorCode,
		&i.ProposedErrorMessage,
		&i.FinishProposedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
