// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_approval.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveToolApprovalRequest = `-- name: ApproveToolApprovalRequest :one
UPDATE tool_approval_requests
SET status = 'approved',
    decision_reason = $1,
    selected_option_id = $2,
    decided_by_channel_identity_id = $3,
    response_control_id = $4::text,
    response_payload_hash = $5::text,
    decided_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND id = $6
  AND status = 'pending'
  AND (runtime_fencing_token IS NULL OR runtime_fencing_token = $7::bigint)
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type ApproveToolApprovalRequestParams struct {
	Reason                     string      `json:"reason"`
	SelectedOptionID           string      `json:"selected_option_id"`
	DecidedByChannelIdentityID pgtype.UUID `json:"decided_by_channel_identity_id"`
	ResponseControlID          pgtype.Text `json:"response_control_id"`
	ResponsePayloadHash        pgtype.Text `json:"response_payload_hash"`
	ID                         pgtype.UUID `json:"id"`
	RuntimeFencingToken        pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) ApproveToolApprovalRequest(ctx context.Context, arg ApproveToolApprovalRequestParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, approveToolApprovalRequest,
		arg.Reason,
		arg.SelectedOptionID,
		arg.DecidedByChannelIdentityID,
		arg.ResponseControlID,
		arg.ResponsePayloadHash,
		arg.ID,
		arg.RuntimeFencingToken,
	)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const cancelPendingToolApprovalsBySession = `-- name: CancelPendingToolApprovalsBySession :many
UPDATE tool_approval_requests
SET status = 'cancelled',
    decision_reason = $1,
    decided_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND session_id = $3
  AND status = 'pending'
  AND (runtime_fencing_token IS NULL OR runtime_fencing_token = $4::bigint)
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type CancelPendingToolApprovalsBySessionParams struct {
	Reason              string      `json:"reason"`
	BotID               pgtype.UUID `json:"bot_id"`
	SessionID           pgtype.UUID `json:"session_id"`
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) CancelPendingToolApprovalsBySession(ctx context.Context, arg CancelPendingToolApprovalsBySessionParams) ([]ToolApprovalRequest, error) {
	rows, err := q.db.Query(ctx, cancelPendingToolApprovalsBySession,
		arg.Reason,
		arg.BotID,
		arg.SessionID,
		arg.RuntimeFencingToken,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApprovalRequest
	for rows.Next() {
		var i ToolApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Operation,
			&i.ToolInput,
			&i.Options,
			&i.SelectedOptionID,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.DecisionReason,
			&i.RequestedByChannelIdentityID,
			&i.DecidedByChannelIdentityID,
			&i.RequestedMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimToolApprovalRequestForRuntime = `-- name: ClaimToolApprovalRequestForRuntime :one
UPDATE tool_approval_requests
SET runtime_fencing_token = $1
WHERE team_id = public.memoh_current_team_id()
  AND id = $2
  AND bot_id = $3
  AND session_id = $4
  AND status = 'pending'
  AND (runtime_fencing_token IS NULL OR runtime_fencing_token <= $1)
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type ClaimToolApprovalRequestForRuntimeParams struct {
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
	ID                  pgtype.UUID `json:"id"`
	BotID               pgtype.UUID `json:"bot_id"`
	SessionID           pgtype.UUID `json:"session_id"`
}

func (q *Queries) ClaimToolApprovalRequestForRuntime(ctx context.Context, arg ClaimToolApprovalRequestForRuntimeParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, claimToolApprovalRequestForRuntime,
		arg.RuntimeFencingToken,
		arg.ID,
		arg.BotID,
		arg.SessionID,
	)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const createToolApprovalRequest = `-- name: CreateToolApprovalRequest :one
WITH locked_session AS (
  SELECT id
  FROM bot_sessions
  WHERE team_id = public.memoh_current_team_id()
    AND id = $2
  FOR UPDATE
),
next_short_id AS (
  SELECT COALESCE(MAX(tool_approval_requests.short_id), 0) + 1 AS short_id
  FROM locked_session
  LEFT JOIN tool_approval_requests ON tool_approval_requests.session_id = locked_session.id
    AND tool_approval_requests.team_id = public.memoh_current_team_id()
),
runtime_scope AS (
  SELECT session_runs.run_id, session_runs.turn_id
  FROM session_runs
  WHERE session_runs.team_id = public.memoh_current_team_id()
    AND session_runs.bot_id = $1
    AND session_runs.session_id = $2
    AND session_runs.fencing_token = $11::bigint
    AND session_runs.state IN ('running', 'waiting_decision')
  UNION ALL
  SELECT NULL::uuid, NULL::uuid
  WHERE $11::bigint IS NULL
)
INSERT INTO tool_approval_requests (
  bot_id,
  session_id,
  run_id,
  turn_id,
  route_id,
  channel_identity_id,
  workspace_target_id,
  tool_call_id,
  tool_name,
  operation,
  tool_input,
  options,
  short_id,
  runtime_fencing_token,
  requested_by_channel_identity_id,
  requested_message_id,
  source_platform,
  reply_target,
  conversation_type
) SELECT
  $1,
  $2,
  runtime_scope.run_id,
  runtime_scope.turn_id,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  COALESCE($10::jsonb, '[]'::jsonb),
  next_short_id.short_id,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
FROM locked_session
CROSS JOIN next_short_id
CROSS JOIN runtime_scope
ON CONFLICT (team_id, session_id, tool_call_id) DO UPDATE
SET tool_input = tool_approval_requests.tool_input
WHERE tool_approval_requests.status = 'pending'
  AND tool_approval_requests.runtime_fencing_token IS NOT DISTINCT FROM EXCLUDED.runtime_fencing_token
  AND tool_approval_requests.run_id IS NOT DISTINCT FROM EXCLUDED.run_id
  AND tool_approval_requests.turn_id IS NOT DISTINCT FROM EXCLUDED.turn_id
  AND tool_approval_requests.tool_name = EXCLUDED.tool_name
  AND tool_approval_requests.operation = EXCLUDED.operation
  AND tool_approval_requests.tool_input = EXCLUDED.tool_input
  AND tool_approval_requests.options = EXCLUDED.options
  AND tool_approval_requests.workspace_target_id = EXCLUDED.workspace_target_id
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type CreateToolApprovalRequestParams struct {
	BotID                        pgtype.UUID `json:"bot_id"`
	SessionID                    pgtype.UUID `json:"session_id"`
	RouteID                      pgtype.UUID `json:"route_id"`
	ChannelIdentityID            pgtype.UUID `json:"channel_identity_id"`
	WorkspaceTargetID            string      `json:"workspace_target_id"`
	ToolCallID                   string      `json:"tool_call_id"`
	ToolName                     string      `json:"tool_name"`
	Operation                    string      `json:"operation"`
	ToolInput                    []byte      `json:"tool_input"`
	Options                      []byte      `json:"options"`
	RuntimeFencingToken          pgtype.Int8 `json:"runtime_fencing_token"`
	RequestedByChannelIdentityID pgtype.UUID `json:"requested_by_channel_identity_id"`
	RequestedMessageID           pgtype.UUID `json:"requested_message_id"`
	SourcePlatform               string      `json:"source_platform"`
	ReplyTarget                  string      `json:"reply_target"`
	ConversationType             string      `json:"conversation_type"`
}

func (q *Queries) CreateToolApprovalRequest(ctx context.Context, arg CreateToolApprovalRequestParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createToolApprovalRequest,
		arg.BotID,
		arg.SessionID,
		arg.RouteID,
		arg.ChannelIdentityID,
		arg.WorkspaceTargetID,
		arg.ToolCallID,
		arg.ToolName,
		arg.Operation,
		arg.ToolInput,
		arg.Options,
		arg.RuntimeFencingToken,
		arg.RequestedByChannelIdentityID,
		arg.RequestedMessageID,
		arg.SourcePlatform,
		arg.ReplyTarget,
		arg.ConversationType,
	)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getLatestPendingToolApprovalBySession = `-- name: GetLatestPendingToolApprovalBySession :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND status = 'pending'
ORDER BY created_at DESC, short_id DESC
LIMIT 1
`

type GetLatestPendingToolApprovalBySessionParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetLatestPendingToolApprovalBySession(ctx context.Context, arg GetLatestPendingToolApprovalBySessionParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getLatestPendingToolApprovalBySession, arg.BotID, arg.SessionID)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getPendingToolApprovalByReplyMessage = `-- name: GetPendingToolApprovalByReplyMessage :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND prompt_external_message_id = $3
  AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingToolApprovalByReplyMessageParams struct {
	BotID                   pgtype.UUID `json:"bot_id"`
	SessionID               pgtype.UUID `json:"session_id"`
	PromptExternalMessageID string      `json:"prompt_external_message_id"`
}

func (q *Queries) GetPendingToolApprovalByReplyMessage(ctx context.Context, arg GetPendingToolApprovalByReplyMessageParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getPendingToolApprovalByReplyMessage, arg.BotID, arg.SessionID, arg.PromptExternalMessageID)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getPendingToolApprovalBySessionShortID = `-- name: GetPendingToolApprovalBySessionShortID :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND short_id = $3
  AND status = 'pending'
`

type GetPendingToolApprovalBySessionShortIDParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	ShortID   int32       `json:"short_id"`
}

func (q *Queries) GetPendingToolApprovalBySessionShortID(ctx context.Context, arg GetPendingToolApprovalBySessionShortIDParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getPendingToolApprovalBySessionShortID, arg.BotID, arg.SessionID, arg.ShortID)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getToolApprovalRequest = `-- name: GetToolApprovalRequest :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id() AND id = $1
`

func (q *Queries) GetToolApprovalRequest(ctx context.Context, id pgtype.UUID) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getToolApprovalRequest, id)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const listPendingToolApprovalsByRun = `-- name: ListPendingToolApprovalsByRun :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND status = 'pending'
ORDER BY created_at ASC, short_id ASC
`

func (q *Queries) ListPendingToolApprovalsByRun(ctx context.Context, runID pgtype.UUID) ([]ToolApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingToolApprovalsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApprovalRequest
	for rows.Next() {
		var i ToolApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Operation,
			&i.ToolInput,
			&i.Options,
			&i.SelectedOptionID,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.DecisionReason,
			&i.RequestedByChannelIdentityID,
			&i.DecidedByChannelIdentityID,
			&i.RequestedMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingToolApprovalsBySession = `-- name: ListPendingToolApprovalsBySession :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND status = 'pending'
ORDER BY created_at ASC, short_id ASC
`

type ListPendingToolApprovalsBySessionParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListPendingToolApprovalsBySession(ctx context.Context, arg ListPendingToolApprovalsBySessionParams) ([]ToolApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingToolApprovalsBySession, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApprovalRequest
	for rows.Next() {
		var i ToolApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Operation,
			&i.ToolInput,
			&i.Options,
			&i.SelectedOptionID,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.DecisionReason,
			&i.RequestedByChannelIdentityID,
			&i.DecidedByChannelIdentityID,
			&i.RequestedMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolApprovalsBySession = `-- name: ListToolApprovalsBySession :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
ORDER BY created_at ASC, short_id ASC
`

type ListToolApprovalsBySessionParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListToolApprovalsBySession(ctx context.Context, arg ListToolApprovalsBySessionParams) ([]ToolApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listToolApprovalsBySession, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApprovalRequest
	for rows.Next() {
		var i ToolApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Operation,
			&i.ToolInput,
			&i.Options,
			&i.SelectedOptionID,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.DecisionReason,
			&i.RequestedByChannelIdentityID,
			&i.DecidedByChannelIdentityID,
			&i.RequestedMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolApprovalsBySessionToolCalls = `-- name: ListToolApprovalsBySessionToolCalls :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
FROM tool_approval_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND tool_call_id = ANY($3::text[])
ORDER BY created_at ASC, short_id ASC
`

type ListToolApprovalsBySessionToolCallsParams struct {
	BotID       pgtype.UUID `json:"bot_id"`
	SessionID   pgtype.UUID `json:"session_id"`
	ToolCallIds []string    `json:"tool_call_ids"`
}

func (q *Queries) ListToolApprovalsBySessionToolCalls(ctx context.Context, arg ListToolApprovalsBySessionToolCallsParams) ([]ToolApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listToolApprovalsBySessionToolCalls, arg.BotID, arg.SessionID, arg.ToolCallIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApprovalRequest
	for rows.Next() {
		var i ToolApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Operation,
			&i.ToolInput,
			&i.Options,
			&i.SelectedOptionID,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.DecisionReason,
			&i.RequestedByChannelIdentityID,
			&i.DecidedByChannelIdentityID,
			&i.RequestedMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectToolApprovalRequest = `-- name: RejectToolApprovalRequest :one
UPDATE tool_approval_requests
SET status = 'rejected',
    decision_reason = $1,
    selected_option_id = $2,
    decided_by_channel_identity_id = $3,
    response_control_id = $4::text,
    response_payload_hash = $5::text,
    decided_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND id = $6
  AND status = 'pending'
  AND (runtime_fencing_token IS NULL OR runtime_fencing_token = $7::bigint)
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type RejectToolApprovalRequestParams struct {
	Reason                     string      `json:"reason"`
	SelectedOptionID           string      `json:"selected_option_id"`
	DecidedByChannelIdentityID pgtype.UUID `json:"decided_by_channel_identity_id"`
	ResponseControlID          pgtype.Text `json:"response_control_id"`
	ResponsePayloadHash        pgtype.Text `json:"response_payload_hash"`
	ID                         pgtype.UUID `json:"id"`
	RuntimeFencingToken        pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) RejectToolApprovalRequest(ctx context.Context, arg RejectToolApprovalRequestParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, rejectToolApprovalRequest,
		arg.Reason,
		arg.SelectedOptionID,
		arg.DecidedByChannelIdentityID,
		arg.ResponseControlID,
		arg.ResponsePayloadHash,
		arg.ID,
		arg.RuntimeFencingToken,
	)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const supersedePendingToolApprovalsBySession = `-- name: SupersedePendingToolApprovalsBySession :many
UPDATE tool_approval_requests
SET status = 'cancelled',
    decision_reason = $1,
    decided_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND session_id = $3
  AND status = 'pending'
  AND runtime_fencing_token IS NOT NULL
  AND id != ALL($4::uuid[])
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type SupersedePendingToolApprovalsBySessionParams struct {
	Reason      string        `json:"reason"`
	BotID       pgtype.UUID   `json:"bot_id"`
	SessionID   pgtype.UUID   `json:"session_id"`
	PreserveIds []pgtype.UUID `json:"preserve_ids"`
}

func (q *Queries) SupersedePendingToolApprovalsBySession(ctx context.Context, arg SupersedePendingToolApprovalsBySessionParams) ([]ToolApprovalRequest, error) {
	rows, err := q.db.Query(ctx, supersedePendingToolApprovalsBySession,
		arg.Reason,
		arg.BotID,
		arg.SessionID,
		arg.PreserveIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolApprovalRequest
	for rows.Next() {
		var i ToolApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.Operation,
			&i.ToolInput,
			&i.Options,
			&i.SelectedOptionID,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.DecisionReason,
			&i.RequestedByChannelIdentityID,
			&i.DecidedByChannelIdentityID,
			&i.RequestedMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToolApprovalPromptMessage = `-- name: UpdateToolApprovalPromptMessage :one
UPDATE tool_approval_requests
SET prompt_message_id = $1,
    prompt_external_message_id = $2
WHERE team_id = public.memoh_current_team_id() AND id = $3
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, operation, tool_input, options, selected_option_id, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, decision_reason, requested_by_channel_identity_id, decided_by_channel_identity_id, requested_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, created_at, decided_at, team_id, run_id, turn_id
`

type UpdateToolApprovalPromptMessageParams struct {
	PromptMessageID         pgtype.UUID `json:"prompt_message_id"`
	PromptExternalMessageID string      `json:"prompt_external_message_id"`
	ID                      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateToolApprovalPromptMessage(ctx context.Context, arg UpdateToolApprovalPromptMessageParams) (ToolApprovalRequest, error) {
	row := q.db.QueryRow(ctx, updateToolApprovalPromptMessage, arg.PromptMessageID, arg.PromptExternalMessageID, arg.ID)
	var i ToolApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.Operation,
		&i.ToolInput,
		&i.Options,
		&i.SelectedOptionID,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.DecisionReason,
		&i.RequestedByChannelIdentityID,
		&i.DecidedByChannelIdentityID,
		&i.RequestedMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}
