// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_input.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingUserInputsByRun = `-- name: CancelPendingUserInputsByRun :many
UPDATE user_input_requests
SET status = 'canceled',
    result_json = $1,
    responded_at = now(),
    canceled_at = now(),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND session_id = $3
  AND run_id = $4
  AND status = 'pending'
  AND runtime_fencing_token IS NOT DISTINCT FROM $5::bigint
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type CancelPendingUserInputsByRunParams struct {
	ResultJson          []byte      `json:"result_json"`
	BotID               pgtype.UUID `json:"bot_id"`
	SessionID           pgtype.UUID `json:"session_id"`
	RunID               pgtype.UUID `json:"run_id"`
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
}

// A lost run must only invalidate decisions it created. Session-wide
// cancellation would also expire a newer run's ask_user request after a
// stale owner is reaped.
func (q *Queries) CancelPendingUserInputsByRun(ctx context.Context, arg CancelPendingUserInputsByRunParams) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, cancelPendingUserInputsByRun,
		arg.ResultJson,
		arg.BotID,
		arg.SessionID,
		arg.RunID,
		arg.RuntimeFencingToken,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelPendingUserInputsBySession = `-- name: CancelPendingUserInputsBySession :many
UPDATE user_input_requests
SET status = 'canceled',
    result_json = $1,
    responded_at = now(),
    canceled_at = now(),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND session_id = $3
  AND status = 'pending'
  AND (
    runtime_fencing_token = $4::bigint
    OR (runtime_fencing_token IS NULL AND (expires_at IS NULL OR expires_at > now()))
  )
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type CancelPendingUserInputsBySessionParams struct {
	ResultJson          []byte      `json:"result_json"`
	BotID               pgtype.UUID `json:"bot_id"`
	SessionID           pgtype.UUID `json:"session_id"`
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) CancelPendingUserInputsBySession(ctx context.Context, arg CancelPendingUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, cancelPendingUserInputsBySession,
		arg.ResultJson,
		arg.BotID,
		arg.SessionID,
		arg.RuntimeFencingToken,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelUserInputRequest = `-- name: CancelUserInputRequest :one
UPDATE user_input_requests
SET status = 'canceled',
    result_json = $1,
    responded_by_channel_identity_id = $2,
    response_control_id = $3::text,
    response_payload_hash = $4::text,
    responded_at = now(),
    canceled_at = now(),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND id = $5
  AND status = 'pending'
  AND (
    runtime_fencing_token = $6::bigint
    OR (runtime_fencing_token IS NULL AND (expires_at IS NULL OR expires_at > now()))
  )
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type CancelUserInputRequestParams struct {
	ResultJson                   []byte      `json:"result_json"`
	RespondedByChannelIdentityID pgtype.UUID `json:"responded_by_channel_identity_id"`
	ResponseControlID            pgtype.Text `json:"response_control_id"`
	ResponsePayloadHash          pgtype.Text `json:"response_payload_hash"`
	ID                           pgtype.UUID `json:"id"`
	RuntimeFencingToken          pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) CancelUserInputRequest(ctx context.Context, arg CancelUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, cancelUserInputRequest,
		arg.ResultJson,
		arg.RespondedByChannelIdentityID,
		arg.ResponseControlID,
		arg.ResponsePayloadHash,
		arg.ID,
		arg.RuntimeFencingToken,
	)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const claimUserInputRequestForRuntime = `-- name: ClaimUserInputRequestForRuntime :one
UPDATE user_input_requests
SET runtime_fencing_token = $1,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND id = $2
  AND bot_id = $3
  AND session_id = $4
  AND status = 'pending'
  AND (
    runtime_fencing_token = $1
    OR (
      (runtime_fencing_token IS NULL OR runtime_fencing_token < $1)
      AND (expires_at IS NULL OR expires_at > now())
    )
  )
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type ClaimUserInputRequestForRuntimeParams struct {
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
	ID                  pgtype.UUID `json:"id"`
	BotID               pgtype.UUID `json:"bot_id"`
	SessionID           pgtype.UUID `json:"session_id"`
}

func (q *Queries) ClaimUserInputRequestForRuntime(ctx context.Context, arg ClaimUserInputRequestForRuntimeParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, claimUserInputRequestForRuntime,
		arg.RuntimeFencingToken,
		arg.ID,
		arg.BotID,
		arg.SessionID,
	)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const createUserInputRequest = `-- name: CreateUserInputRequest :one
WITH locked_session AS (
  SELECT id
  FROM bot_sessions
  WHERE team_id = public.memoh_current_team_id()
    AND id = $2
  FOR UPDATE
),
next_short_id AS (
  SELECT COALESCE(MAX(user_input_requests.short_id), 0) + 1 AS short_id
  FROM locked_session
  LEFT JOIN user_input_requests ON user_input_requests.session_id = locked_session.id
    AND user_input_requests.team_id = public.memoh_current_team_id()
),
runtime_scope AS (
  SELECT session_runs.run_id, session_runs.turn_id
  FROM session_runs
  WHERE session_runs.team_id = public.memoh_current_team_id()
    AND session_runs.bot_id = $1
    AND session_runs.session_id = $2
    AND session_runs.fencing_token = $8::bigint
    AND session_runs.state IN ('running', 'waiting_decision')
  UNION ALL
  SELECT NULL::uuid, NULL::uuid
  WHERE $8::bigint IS NULL
)
INSERT INTO user_input_requests (
  bot_id,
  session_id,
  run_id,
  turn_id,
  route_id,
  channel_identity_id,
  workspace_target_id,
  tool_call_id,
  tool_name,
  short_id,
  runtime_fencing_token,
  input_json,
  ui_payload_json,
  provider_metadata,
  requested_by_channel_identity_id,
  source_platform,
  reply_target,
  conversation_type,
  expires_at
) SELECT
  $1,
  $2,
  runtime_scope.run_id,
  runtime_scope.turn_id,
  $3,
  $4,
  $5,
  $6,
  $7,
  next_short_id.short_id,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16
FROM locked_session
CROSS JOIN next_short_id
CROSS JOIN runtime_scope
ON CONFLICT (team_id, session_id, tool_call_id) DO UPDATE
SET requested_by_channel_identity_id = EXCLUDED.requested_by_channel_identity_id,
    source_platform = EXCLUDED.source_platform,
    reply_target = EXCLUDED.reply_target,
    conversation_type = EXCLUDED.conversation_type,
    expires_at = EXCLUDED.expires_at,
    updated_at = now()
WHERE user_input_requests.status = 'pending'
  AND user_input_requests.runtime_fencing_token IS NOT DISTINCT FROM EXCLUDED.runtime_fencing_token
  AND user_input_requests.run_id IS NOT DISTINCT FROM EXCLUDED.run_id
  AND user_input_requests.turn_id IS NOT DISTINCT FROM EXCLUDED.turn_id
  AND user_input_requests.input_json = EXCLUDED.input_json
  AND user_input_requests.ui_payload_json = EXCLUDED.ui_payload_json
  AND user_input_requests.provider_metadata = EXCLUDED.provider_metadata
  AND user_input_requests.workspace_target_id = EXCLUDED.workspace_target_id
  AND (user_input_requests.expires_at IS NULL OR user_input_requests.expires_at > now())
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type CreateUserInputRequestParams struct {
	BotID                        pgtype.UUID        `json:"bot_id"`
	SessionID                    pgtype.UUID        `json:"session_id"`
	RouteID                      pgtype.UUID        `json:"route_id"`
	ChannelIdentityID            pgtype.UUID        `json:"channel_identity_id"`
	WorkspaceTargetID            string             `json:"workspace_target_id"`
	ToolCallID                   string             `json:"tool_call_id"`
	ToolName                     string             `json:"tool_name"`
	RuntimeFencingToken          pgtype.Int8        `json:"runtime_fencing_token"`
	InputJson                    []byte             `json:"input_json"`
	UiPayloadJson                []byte             `json:"ui_payload_json"`
	ProviderMetadata             []byte             `json:"provider_metadata"`
	RequestedByChannelIdentityID pgtype.UUID        `json:"requested_by_channel_identity_id"`
	SourcePlatform               string             `json:"source_platform"`
	ReplyTarget                  string             `json:"reply_target"`
	ConversationType             string             `json:"conversation_type"`
	ExpiresAt                    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserInputRequest(ctx context.Context, arg CreateUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, createUserInputRequest,
		arg.BotID,
		arg.SessionID,
		arg.RouteID,
		arg.ChannelIdentityID,
		arg.WorkspaceTargetID,
		arg.ToolCallID,
		arg.ToolName,
		arg.RuntimeFencingToken,
		arg.InputJson,
		arg.UiPayloadJson,
		arg.ProviderMetadata,
		arg.RequestedByChannelIdentityID,
		arg.SourcePlatform,
		arg.ReplyTarget,
		arg.ConversationType,
		arg.ExpiresAt,
	)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const failUserInputRequest = `-- name: FailUserInputRequest :one
UPDATE user_input_requests
SET status = 'failed',
    result_json = $1,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND id = $2
  AND status = 'pending'
  AND (
    runtime_fencing_token = $3::bigint
    OR (runtime_fencing_token IS NULL AND (expires_at IS NULL OR expires_at > now()))
  )
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type FailUserInputRequestParams struct {
	ResultJson          []byte      `json:"result_json"`
	ID                  pgtype.UUID `json:"id"`
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) FailUserInputRequest(ctx context.Context, arg FailUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, failUserInputRequest, arg.ResultJson, arg.ID, arg.RuntimeFencingToken)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getInteractiveUserInputRequest = `-- name: GetInteractiveUserInputRequest :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
`

type GetInteractiveUserInputRequestParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

// Channel-native controls may advance the interaction without carrying the
// runtime fence. The eventual submit remains fence-protected; this lookup
// only admits a live, pending request in the requested bot scope.
func (q *Queries) GetInteractiveUserInputRequest(ctx context.Context, arg GetInteractiveUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getInteractiveUserInputRequest, arg.BotID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getLatestPendingUserInputBySession = `-- name: GetLatestPendingUserInputBySession :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC, short_id DESC
LIMIT 1
`

type GetLatestPendingUserInputBySessionParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) GetLatestPendingUserInputBySession(ctx context.Context, arg GetLatestPendingUserInputBySessionParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getLatestPendingUserInputBySession, arg.BotID, arg.SessionID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getPendingUserInputByReplyMessage = `-- name: GetPendingUserInputByReplyMessage :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND prompt_external_message_id = $3
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingUserInputByReplyMessageParams struct {
	BotID                   pgtype.UUID `json:"bot_id"`
	SessionID               pgtype.UUID `json:"session_id"`
	PromptExternalMessageID string      `json:"prompt_external_message_id"`
}

func (q *Queries) GetPendingUserInputByReplyMessage(ctx context.Context, arg GetPendingUserInputByReplyMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getPendingUserInputByReplyMessage, arg.BotID, arg.SessionID, arg.PromptExternalMessageID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getPendingUserInputBySessionShortID = `-- name: GetPendingUserInputBySessionShortID :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND short_id = $3
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
`

type GetPendingUserInputBySessionShortIDParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	ShortID   int32       `json:"short_id"`
}

func (q *Queries) GetPendingUserInputBySessionShortID(ctx context.Context, arg GetPendingUserInputBySessionShortIDParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getPendingUserInputBySessionShortID, arg.BotID, arg.SessionID, arg.ShortID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getRespondableUserInputRequest = `-- name: GetRespondableUserInputRequest :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
  AND status = 'pending'
  AND (
    (
      $2::bigint IS NOT NULL
      AND runtime_fencing_token = $2::bigint
    )
    OR (
      $2::bigint IS NULL
      AND runtime_fencing_token IS NULL
      AND (expires_at IS NULL OR expires_at > now())
    )
  )
`

type GetRespondableUserInputRequestParams struct {
	ID                  pgtype.UUID `json:"id"`
	RuntimeFencingToken pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) GetRespondableUserInputRequest(ctx context.Context, arg GetRespondableUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getRespondableUserInputRequest, arg.ID, arg.RuntimeFencingToken)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getUserInputRequest = `-- name: GetUserInputRequest :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id() AND id = $1
`

func (q *Queries) GetUserInputRequest(ctx context.Context, id pgtype.UUID) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getUserInputRequest, id)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const getUserInputRequestBySessionToolCall = `-- name: GetUserInputRequestBySessionToolCall :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
  AND tool_call_id = $2
`

type GetUserInputRequestBySessionToolCallParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	ToolCallID string      `json:"tool_call_id"`
}

func (q *Queries) GetUserInputRequestBySessionToolCall(ctx context.Context, arg GetUserInputRequestBySessionToolCallParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, getUserInputRequestBySessionToolCall, arg.SessionID, arg.ToolCallID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const listPendingUserInputsByRun = `-- name: ListPendingUserInputsByRun :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND run_id = $1
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at ASC, short_id ASC
`

func (q *Queries) ListPendingUserInputsByRun(ctx context.Context, runID pgtype.UUID) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, listPendingUserInputsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUserInputsBySession = `-- name: ListPendingUserInputsBySession :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at ASC, short_id ASC
`

type ListPendingUserInputsBySessionParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListPendingUserInputsBySession(ctx context.Context, arg ListPendingUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, listPendingUserInputsBySession, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInputsBySession = `-- name: ListUserInputsBySession :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
ORDER BY created_at ASC, short_id ASC
`

type ListUserInputsBySessionParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) ListUserInputsBySession(ctx context.Context, arg ListUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, listUserInputsBySession, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInputsBySessionToolCalls = `-- name: ListUserInputsBySessionToolCalls :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
FROM user_input_requests
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND session_id = $2
  AND tool_call_id = ANY($3::text[])
ORDER BY created_at ASC, short_id ASC
`

type ListUserInputsBySessionToolCallsParams struct {
	BotID       pgtype.UUID `json:"bot_id"`
	SessionID   pgtype.UUID `json:"session_id"`
	ToolCallIds []string    `json:"tool_call_ids"`
}

func (q *Queries) ListUserInputsBySessionToolCalls(ctx context.Context, arg ListUserInputsBySessionToolCallsParams) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, listUserInputsBySessionToolCalls, arg.BotID, arg.SessionID, arg.ToolCallIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitUserInputRequest = `-- name: SubmitUserInputRequest :one
UPDATE user_input_requests
SET status = 'submitted',
    result_json = $1,
    responded_by_channel_identity_id = $2,
    response_control_id = $3::text,
    response_payload_hash = $4::text,
    responded_at = now(),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND id = $5
  AND status = 'pending'
  AND (
    runtime_fencing_token = $6::bigint
    OR (runtime_fencing_token IS NULL AND (expires_at IS NULL OR expires_at > now()))
  )
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type SubmitUserInputRequestParams struct {
	ResultJson                   []byte      `json:"result_json"`
	RespondedByChannelIdentityID pgtype.UUID `json:"responded_by_channel_identity_id"`
	ResponseControlID            pgtype.Text `json:"response_control_id"`
	ResponsePayloadHash          pgtype.Text `json:"response_payload_hash"`
	ID                           pgtype.UUID `json:"id"`
	RuntimeFencingToken          pgtype.Int8 `json:"runtime_fencing_token"`
}

func (q *Queries) SubmitUserInputRequest(ctx context.Context, arg SubmitUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, submitUserInputRequest,
		arg.ResultJson,
		arg.RespondedByChannelIdentityID,
		arg.ResponseControlID,
		arg.ResponsePayloadHash,
		arg.ID,
		arg.RuntimeFencingToken,
	)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const supersedePendingUserInputsBySession = `-- name: SupersedePendingUserInputsBySession :many
UPDATE user_input_requests
SET status = 'canceled',
    result_json = $1,
    responded_at = now(),
    canceled_at = now(),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND session_id = $3
  AND status = 'pending'
  AND runtime_fencing_token IS NOT NULL
  AND id != ALL($4::uuid[])
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type SupersedePendingUserInputsBySessionParams struct {
	ResultJson  []byte        `json:"result_json"`
	BotID       pgtype.UUID   `json:"bot_id"`
	SessionID   pgtype.UUID   `json:"session_id"`
	PreserveIds []pgtype.UUID `json:"preserve_ids"`
}

func (q *Queries) SupersedePendingUserInputsBySession(ctx context.Context, arg SupersedePendingUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.Query(ctx, supersedePendingUserInputsBySession,
		arg.ResultJson,
		arg.BotID,
		arg.SessionID,
		arg.PreserveIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.WorkspaceTargetID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.RuntimeFencingToken,
			&i.ResponseControlID,
			&i.ResponsePayloadHash,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.InteractionJson,
			&i.InteractionRevision,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
			&i.TeamID,
			&i.RunID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserInputAssistantMessage = `-- name: UpdateUserInputAssistantMessage :one
UPDATE user_input_requests
SET assistant_message_id = $1,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $2
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type UpdateUserInputAssistantMessageParams struct {
	AssistantMessageID pgtype.UUID `json:"assistant_message_id"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserInputAssistantMessage(ctx context.Context, arg UpdateUserInputAssistantMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, updateUserInputAssistantMessage, arg.AssistantMessageID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const updateUserInputInteraction = `-- name: UpdateUserInputInteraction :one
UPDATE user_input_requests
SET interaction_json = $1,
    interaction_revision = interaction_revision + 1,
    updated_at = now()
WHERE id = $2
  AND status = 'pending'
  AND interaction_revision = $3
  AND (expires_at IS NULL OR expires_at > now())
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type UpdateUserInputInteractionParams struct {
	InteractionJson     []byte      `json:"interaction_json"`
	ID                  pgtype.UUID `json:"id"`
	InteractionRevision int32       `json:"interaction_revision"`
}

func (q *Queries) UpdateUserInputInteraction(ctx context.Context, arg UpdateUserInputInteractionParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, updateUserInputInteraction, arg.InteractionJson, arg.ID, arg.InteractionRevision)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const updateUserInputPromptMessage = `-- name: UpdateUserInputPromptMessage :one
UPDATE user_input_requests
SET prompt_message_id = $1,
    prompt_external_message_id = $2,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $3
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type UpdateUserInputPromptMessageParams struct {
	PromptMessageID         pgtype.UUID `json:"prompt_message_id"`
	PromptExternalMessageID string      `json:"prompt_external_message_id"`
	ID                      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserInputPromptMessage(ctx context.Context, arg UpdateUserInputPromptMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, updateUserInputPromptMessage, arg.PromptMessageID, arg.PromptExternalMessageID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}

const updateUserInputToolResultMessage = `-- name: UpdateUserInputToolResultMessage :one
UPDATE user_input_requests
SET tool_result_message_id = $1,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $2
RETURNING id, bot_id, session_id, route_id, channel_identity_id, workspace_target_id, tool_call_id, tool_name, short_id, status, runtime_fencing_token, response_control_id, response_payload_hash, input_json, ui_payload_json, interaction_json, interaction_revision, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at, team_id, run_id, turn_id
`

type UpdateUserInputToolResultMessageParams struct {
	ToolResultMessageID pgtype.UUID `json:"tool_result_message_id"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserInputToolResultMessage(ctx context.Context, arg UpdateUserInputToolResultMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRow(ctx, updateUserInputToolResultMessage, arg.ToolResultMessageID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.WorkspaceTargetID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.RuntimeFencingToken,
		&i.ResponseControlID,
		&i.ResponsePayloadHash,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.InteractionJson,
		&i.InteractionRevision,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.RunID,
		&i.TurnID,
	)
	return i, err
}
