// Code generated by gen-codex-protocol from the codex app-server v2 JSON
// Schema snapshot (codex-cli 0.151.0). DO NOT EDIT.
//
// Regenerate with `mise run codex-protocol-generate`; refresh the snapshot
// itself with `mise run codex-schema-sync`.

package protocol

// PinnedCodexVersion is the codex CLI version the vendored schema snapshot
// (and therefore these generated types) corresponds to.
const PinnedCodexVersion = "0.151.0"

// Client request methods (Memoh → app-server).
const (
	MethodInitialize            = "initialize"
	MethodThreadStart           = "thread/start"
	MethodThreadResume          = "thread/resume"
	MethodThreadFork            = "thread/fork"
	MethodThreadRead            = "thread/read"
	MethodThreadCompactStart    = "thread/compact/start"
	MethodTurnStart             = "turn/start"
	MethodTurnSteer             = "turn/steer"
	MethodTurnInterrupt         = "turn/interrupt"
	MethodModelList             = "model/list"
	MethodAccountRead           = "account/read"
	MethodAccountRateLimitsRead = "account/rateLimits/read"
	MethodAccountLoginStart     = "account/login/start"
	MethodAccountLoginCancel    = "account/login/cancel"
	MethodAccountLogout         = "account/logout"
)

// Server request methods (app-server → Memoh, expect a response).
const (
	MethodItemCommandExecutionRequestApproval = "item/commandExecution/requestApproval"
	MethodItemFileChangeRequestApproval       = "item/fileChange/requestApproval"
	MethodItemPermissionsRequestApproval      = "item/permissions/requestApproval"
	MethodItemToolRequestUserInput            = "item/tool/requestUserInput"
	MethodMCPServerElicitationRequest         = "mcpServer/elicitation/request"
	MethodAccountChatgptAuthTokensRefresh     = "account/chatgptAuthTokens/refresh"
)

// Server notification methods decoded into typed params.
const (
	MethodError                           = "error"
	MethodWarning                         = "warning"
	MethodConfigWarning                   = "configWarning"
	MethodDeprecationNotice               = "deprecationNotice"
	MethodThreadStarted                   = "thread/started"
	MethodThreadStatusChanged             = "thread/status/changed"
	MethodThreadTokenUsageUpdated         = "thread/tokenUsage/updated"
	MethodThreadCompacted                 = "thread/compacted"
	MethodTurnStarted                     = "turn/started"
	MethodTurnCompleted                   = "turn/completed"
	MethodTurnPlanUpdated                 = "turn/plan/updated"
	MethodItemStarted                     = "item/started"
	MethodItemCompleted                   = "item/completed"
	MethodItemAgentMessageDelta           = "item/agentMessage/delta"
	MethodItemReasoningTextDelta          = "item/reasoning/textDelta"
	MethodItemReasoningSummaryTextDelta   = "item/reasoning/summaryTextDelta"
	MethodItemReasoningSummaryPartAdded   = "item/reasoning/summaryPartAdded"
	MethodItemCommandExecutionOutputDelta = "item/commandExecution/outputDelta"
	MethodItemFileChangeOutputDelta       = "item/fileChange/outputDelta"
	MethodAccountUpdated                  = "account/updated"
	MethodAccountLoginCompleted           = "account/login/completed"
	MethodAccountRateLimitsUpdated        = "account/rateLimits/updated"
	MethodServerRequestResolved           = "serverRequest/resolved"
)

// NewResponseForMethod returns a pointer to the zero response value for a
// client request method, ready for unmarshaling. ok is false for methods
// whose responses are not generated (initialize) or unknown methods.
func NewResponseForMethod(method string) (resp any, ok bool) {
	switch method {
	case "thread/start":
		return new(ThreadStartResponse), true
	case "thread/resume":
		return new(ThreadResumeResponse), true
	case "thread/fork":
		return new(ThreadForkResponse), true
	case "thread/read":
		return new(ThreadReadResponse), true
	case "thread/compact/start":
		return new(ThreadCompactStartResponse), true
	case "turn/start":
		return new(TurnStartResponse), true
	case "turn/steer":
		return new(TurnSteerResponse), true
	case "turn/interrupt":
		return new(TurnInterruptResponse), true
	case "model/list":
		return new(ModelListResponse), true
	case "account/read":
		return new(GetAccountResponse), true
	case "account/rateLimits/read":
		return new(GetAccountRateLimitsResponse), true
	case "account/login/start":
		return new(LoginAccountResponse), true
	case "account/login/cancel":
		return new(CancelLoginAccountResponse), true
	case "account/logout":
		return new(LogoutAccountResponse), true
	}
	return nil, false
}

// DecodeServerRequestParams decodes the params of an app-server → Memoh
// request into its generated type. ok is false for unknown methods; the
// caller keeps the raw envelope in that case.
func DecodeServerRequestParams(method string, params []byte) (decoded any, ok bool, err error) {
	switch method {
	case "item/commandExecution/requestApproval":
		v := new(CommandExecutionRequestApprovalParams)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/fileChange/requestApproval":
		v := new(FileChangeRequestApprovalParams)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/permissions/requestApproval":
		v := new(PermissionsRequestApprovalParams)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/tool/requestUserInput":
		v := new(ToolRequestUserInputParams)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "mcpServer/elicitation/request":
		v := new(McpServerElicitationRequestParams)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "account/chatgptAuthTokens/refresh":
		v := new(ChatgptAuthTokensRefreshParams)
		err = jsonUnmarshal(params, v)
		return v, true, err
	}
	return nil, false, nil
}

// DecodeServerNotificationParams decodes the params of an app-server
// notification into its generated type. ok is false for methods outside the
// typed subset; those still surface to the caller as raw envelopes.
func DecodeServerNotificationParams(method string, params []byte) (decoded any, ok bool, err error) {
	switch method {
	case "error":
		v := new(ErrorNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "warning":
		v := new(WarningNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "configWarning":
		v := new(ConfigWarningNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "deprecationNotice":
		v := new(DeprecationNoticeNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "thread/started":
		v := new(ThreadStartedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "thread/status/changed":
		v := new(ThreadStatusChangedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "thread/tokenUsage/updated":
		v := new(ThreadTokenUsageUpdatedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "thread/compacted":
		v := new(ContextCompactedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "turn/started":
		v := new(TurnStartedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "turn/completed":
		v := new(TurnCompletedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "turn/plan/updated":
		v := new(TurnPlanUpdatedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/started":
		v := new(ItemStartedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/completed":
		v := new(ItemCompletedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/agentMessage/delta":
		v := new(AgentMessageDeltaNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/reasoning/textDelta":
		v := new(ReasoningTextDeltaNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/reasoning/summaryTextDelta":
		v := new(ReasoningSummaryTextDeltaNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/reasoning/summaryPartAdded":
		v := new(ReasoningSummaryPartAddedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/commandExecution/outputDelta":
		v := new(CommandExecutionOutputDeltaNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "item/fileChange/outputDelta":
		v := new(FileChangeOutputDeltaNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "account/updated":
		v := new(AccountUpdatedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "account/login/completed":
		v := new(AccountLoginCompletedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "account/rateLimits/updated":
		v := new(AccountRateLimitsUpdatedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	case "serverRequest/resolved":
		v := new(ServerRequestResolvedNotification)
		err = jsonUnmarshal(params, v)
		return v, true, err
	}
	return nil, false, nil
}
