// Code generated by gen-codex-protocol from the codex app-server v2 JSON
// Schema snapshot (codex-cli 0.151.0). DO NOT EDIT.
//
// Regenerate with `mise run codex-protocol-generate`; refresh the snapshot
// itself with `mise run codex-schema-sync`.

package protocol

// Account is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type Account struct {
	// Tag is the value of the "type" property observed on decode.
	Tag           string
	AmazonBedrock *AmazonBedrockAccount
	APIKey        *ApiKeyAccount
	Chatgpt       *ChatgptAccount
	raw           rawMessage
}

const (
	AccountTagAmazonBedrock = "amazonBedrock"
	AccountTagAPIKey        = "apiKey"
	AccountTagChatgpt       = "chatgpt"
)

func (u *Account) UnmarshalJSON(data []byte) error {
	*u = Account{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "amazonBedrock":
		u.AmazonBedrock = new(AmazonBedrockAccount)
		return jsonUnmarshal(data, u.AmazonBedrock)
	case "apiKey":
		u.APIKey = new(ApiKeyAccount)
		return jsonUnmarshal(data, u.APIKey)
	case "chatgpt":
		u.Chatgpt = new(ChatgptAccount)
		return jsonUnmarshal(data, u.Chatgpt)
	}
	return nil
}

func (u Account) MarshalJSON() ([]byte, error) {
	switch {
	case u.AmazonBedrock != nil:
		return marshalTagged("type", "amazonBedrock", u.AmazonBedrock)
	case u.APIKey != nil:
		return marshalTagged("type", "apiKey", u.APIKey)
	case u.Chatgpt != nil:
		return marshalTagged("type", "chatgpt", u.Chatgpt)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("Account")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u Account) Raw() []byte { return u.raw }

type AmazonBedrockAccount struct {
	UsesCodexManagedCredentials *bool `json:"usesCodexManagedCredentials,omitempty"`
}

type ApiKeyAccount struct {
}

type ChatgptAccount struct {
	Email    *string  `json:"email"`
	PlanType PlanType `json:"planType"`
}

// AskForApproval is a mixed union: on the wire it is either a bare string
// (Unit) or a single-key object (one payload field set). Unknown variants
// decode without error and are retained in Raw().
type AskForApproval struct {
	// Unit holds the bare-string variant value, if that form was used.
	Unit     string
	Granular *AskForApprovalGranular
	raw      rawMessage
}

const (
	AskForApprovalUnitNever     = "never"
	AskForApprovalUnitOnRequest = "on-request"
	AskForApprovalUnitUntrusted = "untrusted"
)

func (u *AskForApproval) UnmarshalJSON(data []byte) error {
	*u = AskForApproval{}
	u.raw = append(rawMessage(nil), data...)
	if isJSONString(data) {
		return jsonUnmarshal(data, &u.Unit)
	}
	var obj map[string]rawMessage
	if err := jsonUnmarshal(data, &obj); err != nil {
		return err
	}
	if len(obj) != 1 {
		return nil
	}
	for key, payload := range obj {
		switch key {
		case "granular":
			u.Granular = new(AskForApprovalGranular)
			return jsonUnmarshal(payload, u.Granular)
		}
	}
	return nil
}

func (u AskForApproval) MarshalJSON() ([]byte, error) {
	if u.Unit != "" {
		return jsonMarshal(u.Unit)
	}
	switch {
	case u.Granular != nil:
		return marshalKeyed("granular", u.Granular)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("AskForApproval")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u AskForApproval) Raw() []byte { return u.raw }

// This translation layer make sure that we expose codex error code in camel case.
// CodexErrorInfo is a mixed union: on the wire it is either a bare string
// (Unit) or a single-key object (one payload field set). Unknown variants
// decode without error and are retained in Raw().
type CodexErrorInfo struct {
	// Unit holds the bare-string variant value, if that form was used.
	Unit                           string
	ActiveTurnNotSteerable         *CodexErrorInfoActiveTurnNotSteerable
	HTTPConnectionFailed           *CodexErrorInfoHTTPConnectionFailed
	ResponseStreamConnectionFailed *CodexErrorInfoResponseStreamConnectionFailed
	ResponseStreamDisconnected     *CodexErrorInfoResponseStreamDisconnected
	ResponseTooManyFailedAttempts  *CodexErrorInfoResponseTooManyFailedAttempts
	raw                            rawMessage
}

const (
	CodexErrorInfoUnitBadRequest                  = "badRequest"
	CodexErrorInfoUnitContextWindowExceeded       = "contextWindowExceeded"
	CodexErrorInfoUnitCyberPolicy                 = "cyberPolicy"
	CodexErrorInfoUnitInternalServerError         = "internalServerError"
	CodexErrorInfoUnitMisalignmentPolicyViolation = "misalignmentPolicyViolation"
	CodexErrorInfoUnitOther                       = "other"
	CodexErrorInfoUnitRateLimitExceeded           = "rateLimitExceeded"
	CodexErrorInfoUnitSandboxError                = "sandboxError"
	CodexErrorInfoUnitServerOverloaded            = "serverOverloaded"
	CodexErrorInfoUnitSessionBudgetExceeded       = "sessionBudgetExceeded"
	CodexErrorInfoUnitThreadRollbackFailed        = "threadRollbackFailed"
	CodexErrorInfoUnitUnauthorized                = "unauthorized"
	CodexErrorInfoUnitUsageLimitExceeded          = "usageLimitExceeded"
)

func (u *CodexErrorInfo) UnmarshalJSON(data []byte) error {
	*u = CodexErrorInfo{}
	u.raw = append(rawMessage(nil), data...)
	if isJSONString(data) {
		return jsonUnmarshal(data, &u.Unit)
	}
	var obj map[string]rawMessage
	if err := jsonUnmarshal(data, &obj); err != nil {
		return err
	}
	if len(obj) != 1 {
		return nil
	}
	for key, payload := range obj {
		switch key {
		case "activeTurnNotSteerable":
			u.ActiveTurnNotSteerable = new(CodexErrorInfoActiveTurnNotSteerable)
			return jsonUnmarshal(payload, u.ActiveTurnNotSteerable)
		case "httpConnectionFailed":
			u.HTTPConnectionFailed = new(CodexErrorInfoHTTPConnectionFailed)
			return jsonUnmarshal(payload, u.HTTPConnectionFailed)
		case "responseStreamConnectionFailed":
			u.ResponseStreamConnectionFailed = new(CodexErrorInfoResponseStreamConnectionFailed)
			return jsonUnmarshal(payload, u.ResponseStreamConnectionFailed)
		case "responseStreamDisconnected":
			u.ResponseStreamDisconnected = new(CodexErrorInfoResponseStreamDisconnected)
			return jsonUnmarshal(payload, u.ResponseStreamDisconnected)
		case "responseTooManyFailedAttempts":
			u.ResponseTooManyFailedAttempts = new(CodexErrorInfoResponseTooManyFailedAttempts)
			return jsonUnmarshal(payload, u.ResponseTooManyFailedAttempts)
		}
	}
	return nil
}

func (u CodexErrorInfo) MarshalJSON() ([]byte, error) {
	if u.Unit != "" {
		return jsonMarshal(u.Unit)
	}
	switch {
	case u.ActiveTurnNotSteerable != nil:
		return marshalKeyed("activeTurnNotSteerable", u.ActiveTurnNotSteerable)
	case u.HTTPConnectionFailed != nil:
		return marshalKeyed("httpConnectionFailed", u.HTTPConnectionFailed)
	case u.ResponseStreamConnectionFailed != nil:
		return marshalKeyed("responseStreamConnectionFailed", u.ResponseStreamConnectionFailed)
	case u.ResponseStreamDisconnected != nil:
		return marshalKeyed("responseStreamDisconnected", u.ResponseStreamDisconnected)
	case u.ResponseTooManyFailedAttempts != nil:
		return marshalKeyed("responseTooManyFailedAttempts", u.ResponseTooManyFailedAttempts)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("CodexErrorInfo")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u CodexErrorInfo) Raw() []byte { return u.raw }

// CommandAction is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type CommandAction struct {
	// Tag is the value of the "type" property observed on decode.
	Tag       string
	ListFiles *ListFilesCommandAction
	Read      *ReadCommandAction
	Search    *SearchCommandAction
	Unknown   *UnknownCommandAction
	raw       rawMessage
}

const (
	CommandActionTagListFiles = "listFiles"
	CommandActionTagRead      = "read"
	CommandActionTagSearch    = "search"
	CommandActionTagUnknown   = "unknown"
)

func (u *CommandAction) UnmarshalJSON(data []byte) error {
	*u = CommandAction{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "listFiles":
		u.ListFiles = new(ListFilesCommandAction)
		return jsonUnmarshal(data, u.ListFiles)
	case "read":
		u.Read = new(ReadCommandAction)
		return jsonUnmarshal(data, u.Read)
	case "search":
		u.Search = new(SearchCommandAction)
		return jsonUnmarshal(data, u.Search)
	case "unknown":
		u.Unknown = new(UnknownCommandAction)
		return jsonUnmarshal(data, u.Unknown)
	}
	return nil
}

func (u CommandAction) MarshalJSON() ([]byte, error) {
	switch {
	case u.ListFiles != nil:
		return marshalTagged("type", "listFiles", u.ListFiles)
	case u.Read != nil:
		return marshalTagged("type", "read", u.Read)
	case u.Search != nil:
		return marshalTagged("type", "search", u.Search)
	case u.Unknown != nil:
		return marshalTagged("type", "unknown", u.Unknown)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("CommandAction")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u CommandAction) Raw() []byte { return u.raw }

type ListFilesCommandAction struct {
	Command string  `json:"command"`
	Path    *string `json:"path,omitempty"`
}

type ReadCommandAction struct {
	Command string              `json:"command"`
	Name    string              `json:"name"`
	Path    LegacyAppPathString `json:"path"`
}

type SearchCommandAction struct {
	Command string  `json:"command"`
	Path    *string `json:"path,omitempty"`
	Query   *string `json:"query,omitempty"`
}

type UnknownCommandAction struct {
	Command string `json:"command"`
}

// CommandExecutionApprovalDecision is a mixed union: on the wire it is either a bare string
// (Unit) or a single-key object (one payload field set). Unknown variants
// decode without error and are retained in Raw().
type CommandExecutionApprovalDecision struct {
	// Unit holds the bare-string variant value, if that form was used.
	Unit                          string
	AcceptWithExecpolicyAmendment *CommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment
	ApplyNetworkPolicyAmendment   *CommandExecutionApprovalDecisionApplyNetworkPolicyAmendment
	raw                           rawMessage
}

const (
	CommandExecutionApprovalDecisionUnitAccept           = "accept"
	CommandExecutionApprovalDecisionUnitAcceptForSession = "acceptForSession"
	CommandExecutionApprovalDecisionUnitCancel           = "cancel"
	CommandExecutionApprovalDecisionUnitDecline          = "decline"
)

func (u *CommandExecutionApprovalDecision) UnmarshalJSON(data []byte) error {
	*u = CommandExecutionApprovalDecision{}
	u.raw = append(rawMessage(nil), data...)
	if isJSONString(data) {
		return jsonUnmarshal(data, &u.Unit)
	}
	var obj map[string]rawMessage
	if err := jsonUnmarshal(data, &obj); err != nil {
		return err
	}
	if len(obj) != 1 {
		return nil
	}
	for key, payload := range obj {
		switch key {
		case "acceptWithExecpolicyAmendment":
			u.AcceptWithExecpolicyAmendment = new(CommandExecutionApprovalDecisionAcceptWithExecpolicyAmendment)
			return jsonUnmarshal(payload, u.AcceptWithExecpolicyAmendment)
		case "applyNetworkPolicyAmendment":
			u.ApplyNetworkPolicyAmendment = new(CommandExecutionApprovalDecisionApplyNetworkPolicyAmendment)
			return jsonUnmarshal(payload, u.ApplyNetworkPolicyAmendment)
		}
	}
	return nil
}

func (u CommandExecutionApprovalDecision) MarshalJSON() ([]byte, error) {
	if u.Unit != "" {
		return jsonMarshal(u.Unit)
	}
	switch {
	case u.AcceptWithExecpolicyAmendment != nil:
		return marshalKeyed("acceptWithExecpolicyAmendment", u.AcceptWithExecpolicyAmendment)
	case u.ApplyNetworkPolicyAmendment != nil:
		return marshalKeyed("applyNetworkPolicyAmendment", u.ApplyNetworkPolicyAmendment)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("CommandExecutionApprovalDecision")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u CommandExecutionApprovalDecision) Raw() []byte { return u.raw }

// DynamicToolCallOutputContentItem is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type DynamicToolCallOutputContentItem struct {
	// Tag is the value of the "type" property observed on decode.
	Tag        string
	InputAudio *InputAudioDynamicToolCallOutputContentItem
	InputImage *InputImageDynamicToolCallOutputContentItem
	InputText  *InputTextDynamicToolCallOutputContentItem
	raw        rawMessage
}

const (
	DynamicToolCallOutputContentItemTagInputAudio = "inputAudio"
	DynamicToolCallOutputContentItemTagInputImage = "inputImage"
	DynamicToolCallOutputContentItemTagInputText  = "inputText"
)

func (u *DynamicToolCallOutputContentItem) UnmarshalJSON(data []byte) error {
	*u = DynamicToolCallOutputContentItem{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "inputAudio":
		u.InputAudio = new(InputAudioDynamicToolCallOutputContentItem)
		return jsonUnmarshal(data, u.InputAudio)
	case "inputImage":
		u.InputImage = new(InputImageDynamicToolCallOutputContentItem)
		return jsonUnmarshal(data, u.InputImage)
	case "inputText":
		u.InputText = new(InputTextDynamicToolCallOutputContentItem)
		return jsonUnmarshal(data, u.InputText)
	}
	return nil
}

func (u DynamicToolCallOutputContentItem) MarshalJSON() ([]byte, error) {
	switch {
	case u.InputAudio != nil:
		return marshalTagged("type", "inputAudio", u.InputAudio)
	case u.InputImage != nil:
		return marshalTagged("type", "inputImage", u.InputImage)
	case u.InputText != nil:
		return marshalTagged("type", "inputText", u.InputText)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("DynamicToolCallOutputContentItem")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u DynamicToolCallOutputContentItem) Raw() []byte { return u.raw }

type InputAudioDynamicToolCallOutputContentItem struct {
	AudioURL string `json:"audioUrl"`
}

type InputImageDynamicToolCallOutputContentItem struct {
	ImageURL string `json:"imageUrl"`
}

type InputTextDynamicToolCallOutputContentItem struct {
	Text string `json:"text"`
}

// FileSystemPath is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type FileSystemPath struct {
	// Tag is the value of the "type" property observed on decode.
	Tag         string
	GlobPattern *GlobPatternFileSystemPath
	Path        *PathFileSystemPath
	Special     *SpecialFileSystemPath
	raw         rawMessage
}

const (
	FileSystemPathTagGlobPattern = "glob_pattern"
	FileSystemPathTagPath        = "path"
	FileSystemPathTagSpecial     = "special"
)

func (u *FileSystemPath) UnmarshalJSON(data []byte) error {
	*u = FileSystemPath{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "glob_pattern":
		u.GlobPattern = new(GlobPatternFileSystemPath)
		return jsonUnmarshal(data, u.GlobPattern)
	case "path":
		u.Path = new(PathFileSystemPath)
		return jsonUnmarshal(data, u.Path)
	case "special":
		u.Special = new(SpecialFileSystemPath)
		return jsonUnmarshal(data, u.Special)
	}
	return nil
}

func (u FileSystemPath) MarshalJSON() ([]byte, error) {
	switch {
	case u.GlobPattern != nil:
		return marshalTagged("type", "glob_pattern", u.GlobPattern)
	case u.Path != nil:
		return marshalTagged("type", "path", u.Path)
	case u.Special != nil:
		return marshalTagged("type", "special", u.Special)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("FileSystemPath")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u FileSystemPath) Raw() []byte { return u.raw }

type GlobPatternFileSystemPath struct {
	Pattern string `json:"pattern"`
}

type PathFileSystemPath struct {
	Path LegacyAppPathString `json:"path"`
}

type SpecialFileSystemPath struct {
	Value FileSystemSpecialPath `json:"value"`
}

// FileSystemSpecialPath is an internally-tagged union (tag property "kind").
// Unknown variants decode without error: only Tag and Raw() are populated.
type FileSystemSpecialPath struct {
	// Tag is the value of the "kind" property observed on decode.
	Tag          string
	Minimal      *MinimalFileSystemSpecialPath
	ProjectRoots *KindFileSystemSpecialPath
	Root         *RootFileSystemSpecialPath
	SlashTmp     *SlashTmpFileSystemSpecialPath
	Tmpdir       *TmpdirFileSystemSpecialPath
	Unknown      *UnknownFileSystemSpecialPath
	raw          rawMessage
}

const (
	FileSystemSpecialPathTagMinimal      = "minimal"
	FileSystemSpecialPathTagProjectRoots = "project_roots"
	FileSystemSpecialPathTagRoot         = "root"
	FileSystemSpecialPathTagSlashTmp     = "slash_tmp"
	FileSystemSpecialPathTagTmpdir       = "tmpdir"
	FileSystemSpecialPathTagUnknown      = "unknown"
)

func (u *FileSystemSpecialPath) UnmarshalJSON(data []byte) error {
	*u = FileSystemSpecialPath{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"kind"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "minimal":
		u.Minimal = new(MinimalFileSystemSpecialPath)
		return jsonUnmarshal(data, u.Minimal)
	case "project_roots":
		u.ProjectRoots = new(KindFileSystemSpecialPath)
		return jsonUnmarshal(data, u.ProjectRoots)
	case "root":
		u.Root = new(RootFileSystemSpecialPath)
		return jsonUnmarshal(data, u.Root)
	case "slash_tmp":
		u.SlashTmp = new(SlashTmpFileSystemSpecialPath)
		return jsonUnmarshal(data, u.SlashTmp)
	case "tmpdir":
		u.Tmpdir = new(TmpdirFileSystemSpecialPath)
		return jsonUnmarshal(data, u.Tmpdir)
	case "unknown":
		u.Unknown = new(UnknownFileSystemSpecialPath)
		return jsonUnmarshal(data, u.Unknown)
	}
	return nil
}

func (u FileSystemSpecialPath) MarshalJSON() ([]byte, error) {
	switch {
	case u.Minimal != nil:
		return marshalTagged("kind", "minimal", u.Minimal)
	case u.ProjectRoots != nil:
		return marshalTagged("kind", "project_roots", u.ProjectRoots)
	case u.Root != nil:
		return marshalTagged("kind", "root", u.Root)
	case u.SlashTmp != nil:
		return marshalTagged("kind", "slash_tmp", u.SlashTmp)
	case u.Tmpdir != nil:
		return marshalTagged("kind", "tmpdir", u.Tmpdir)
	case u.Unknown != nil:
		return marshalTagged("kind", "unknown", u.Unknown)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("FileSystemSpecialPath")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u FileSystemSpecialPath) Raw() []byte { return u.raw }

type MinimalFileSystemSpecialPath struct {
}

type KindFileSystemSpecialPath struct {
	Subpath *LegacyAppPathString `json:"subpath,omitempty"`
}

type RootFileSystemSpecialPath struct {
}

type SlashTmpFileSystemSpecialPath struct {
}

type TmpdirFileSystemSpecialPath struct {
}

type UnknownFileSystemSpecialPath struct {
	Path    string               `json:"path"`
	Subpath *LegacyAppPathString `json:"subpath,omitempty"`
}

// Responses API compatible content items that can be returned by a tool call. This is a subset of ContentItem with the types we support as function call outputs.
// FunctionCallOutputContentItem is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type FunctionCallOutputContentItem struct {
	// Tag is the value of the "type" property observed on decode.
	Tag              string
	EncryptedContent *EncryptedContentFunctionCallOutputContentItem
	InputAudio       *InputAudioFunctionCallOutputContentItem
	InputImage       *InputImageFunctionCallOutputContentItem
	InputText        *InputTextFunctionCallOutputContentItem
	raw              rawMessage
}

const (
	FunctionCallOutputContentItemTagEncryptedContent = "encrypted_content"
	FunctionCallOutputContentItemTagInputAudio       = "input_audio"
	FunctionCallOutputContentItemTagInputImage       = "input_image"
	FunctionCallOutputContentItemTagInputText        = "input_text"
)

func (u *FunctionCallOutputContentItem) UnmarshalJSON(data []byte) error {
	*u = FunctionCallOutputContentItem{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "encrypted_content":
		u.EncryptedContent = new(EncryptedContentFunctionCallOutputContentItem)
		return jsonUnmarshal(data, u.EncryptedContent)
	case "input_audio":
		u.InputAudio = new(InputAudioFunctionCallOutputContentItem)
		return jsonUnmarshal(data, u.InputAudio)
	case "input_image":
		u.InputImage = new(InputImageFunctionCallOutputContentItem)
		return jsonUnmarshal(data, u.InputImage)
	case "input_text":
		u.InputText = new(InputTextFunctionCallOutputContentItem)
		return jsonUnmarshal(data, u.InputText)
	}
	return nil
}

func (u FunctionCallOutputContentItem) MarshalJSON() ([]byte, error) {
	switch {
	case u.EncryptedContent != nil:
		return marshalTagged("type", "encrypted_content", u.EncryptedContent)
	case u.InputAudio != nil:
		return marshalTagged("type", "input_audio", u.InputAudio)
	case u.InputImage != nil:
		return marshalTagged("type", "input_image", u.InputImage)
	case u.InputText != nil:
		return marshalTagged("type", "input_text", u.InputText)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("FunctionCallOutputContentItem")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u FunctionCallOutputContentItem) Raw() []byte { return u.raw }

type EncryptedContentFunctionCallOutputContentItem struct {
	EncryptedContent string `json:"encrypted_content"`
}

type InputAudioFunctionCallOutputContentItem struct {
	AudioURL string `json:"audio_url"`
}

type InputImageFunctionCallOutputContentItem struct {
	Detail   *ImageDetail `json:"detail,omitempty"`
	ImageURL string       `json:"image_url"`
}

type InputTextFunctionCallOutputContentItem struct {
	Text string `json:"text"`
}

// ImageGenerationFailure is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type ImageGenerationFailure struct {
	// Tag is the value of the "type" property observed on decode.
	Tag                string
	UsageLimitExceeded *UsageLimitExceededImageGenerationFailure
	raw                rawMessage
}

const (
	ImageGenerationFailureTagUsageLimitExceeded = "usageLimitExceeded"
)

func (u *ImageGenerationFailure) UnmarshalJSON(data []byte) error {
	*u = ImageGenerationFailure{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "usageLimitExceeded":
		u.UsageLimitExceeded = new(UsageLimitExceededImageGenerationFailure)
		return jsonUnmarshal(data, u.UsageLimitExceeded)
	}
	return nil
}

func (u ImageGenerationFailure) MarshalJSON() ([]byte, error) {
	switch {
	case u.UsageLimitExceeded != nil:
		return marshalTagged("type", "usageLimitExceeded", u.UsageLimitExceeded)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("ImageGenerationFailure")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u ImageGenerationFailure) Raw() []byte { return u.raw }

type UsageLimitExceededImageGenerationFailure struct {
	LimitID  string `json:"limitId"`
	ResetsAt *int64 `json:"resetsAt,omitempty"`
}

// LoginAccountParams is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type LoginAccountParams struct {
	// Tag is the value of the "type" property observed on decode.
	Tag                     string
	AmazonBedrock           *AmazonBedrockLoginAccountParams
	AmazonBedrockAccessKeys *AmazonBedrockAccessKeysLoginAccountParams
	APIKey                  *APIKeyLoginAccountParams
	Chatgpt                 *ChatgptLoginAccountParams
	ChatgptAuthTokens       *ChatgptAuthTokensLoginAccountParams
	ChatgptDeviceCode       *ChatgptDeviceCodeLoginAccountParams
	raw                     rawMessage
}

const (
	LoginAccountParamsTagAmazonBedrock           = "amazonBedrock"
	LoginAccountParamsTagAmazonBedrockAccessKeys = "amazonBedrockAccessKeys"
	LoginAccountParamsTagAPIKey                  = "apiKey"
	LoginAccountParamsTagChatgpt                 = "chatgpt"
	LoginAccountParamsTagChatgptAuthTokens       = "chatgptAuthTokens"
	LoginAccountParamsTagChatgptDeviceCode       = "chatgptDeviceCode"
)

func (u *LoginAccountParams) UnmarshalJSON(data []byte) error {
	*u = LoginAccountParams{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "amazonBedrock":
		u.AmazonBedrock = new(AmazonBedrockLoginAccountParams)
		return jsonUnmarshal(data, u.AmazonBedrock)
	case "amazonBedrockAccessKeys":
		u.AmazonBedrockAccessKeys = new(AmazonBedrockAccessKeysLoginAccountParams)
		return jsonUnmarshal(data, u.AmazonBedrockAccessKeys)
	case "apiKey":
		u.APIKey = new(APIKeyLoginAccountParams)
		return jsonUnmarshal(data, u.APIKey)
	case "chatgpt":
		u.Chatgpt = new(ChatgptLoginAccountParams)
		return jsonUnmarshal(data, u.Chatgpt)
	case "chatgptAuthTokens":
		u.ChatgptAuthTokens = new(ChatgptAuthTokensLoginAccountParams)
		return jsonUnmarshal(data, u.ChatgptAuthTokens)
	case "chatgptDeviceCode":
		u.ChatgptDeviceCode = new(ChatgptDeviceCodeLoginAccountParams)
		return jsonUnmarshal(data, u.ChatgptDeviceCode)
	}
	return nil
}

func (u LoginAccountParams) MarshalJSON() ([]byte, error) {
	switch {
	case u.AmazonBedrock != nil:
		return marshalTagged("type", "amazonBedrock", u.AmazonBedrock)
	case u.AmazonBedrockAccessKeys != nil:
		return marshalTagged("type", "amazonBedrockAccessKeys", u.AmazonBedrockAccessKeys)
	case u.APIKey != nil:
		return marshalTagged("type", "apiKey", u.APIKey)
	case u.Chatgpt != nil:
		return marshalTagged("type", "chatgpt", u.Chatgpt)
	case u.ChatgptAuthTokens != nil:
		return marshalTagged("type", "chatgptAuthTokens", u.ChatgptAuthTokens)
	case u.ChatgptDeviceCode != nil:
		return marshalTagged("type", "chatgptDeviceCode", u.ChatgptDeviceCode)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("LoginAccountParams")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u LoginAccountParams) Raw() []byte { return u.raw }

// [UNSTABLE] Managed Amazon Bedrock login is experimental.
type AmazonBedrockLoginAccountParams struct {
	APIKey string `json:"apiKey"`
	Region string `json:"region"`
}

// [UNSTABLE] Managed Amazon Bedrock AWS access key login is experimental.
type AmazonBedrockAccessKeysLoginAccountParams struct {
	AccessKeyID     string  `json:"accessKeyId"`
	Region          string  `json:"region"`
	SecretAccessKey string  `json:"secretAccessKey"`
	SessionToken    *string `json:"sessionToken,omitempty"`
}

type APIKeyLoginAccountParams struct {
	APIKey string `json:"apiKey"`
}

type ChatgptLoginAccountParams struct {
	AppBrand                  *LoginAppBrand `json:"appBrand,omitempty"`
	CodexStreamlinedLogin     *bool          `json:"codexStreamlinedLogin,omitempty"`
	UseHostedLoginSuccessPage *bool          `json:"useHostedLoginSuccessPage,omitempty"`
}

// [UNSTABLE] FOR OPENAI INTERNAL USE ONLY - DO NOT USE. The access token must contain the same scopes that Codex-managed ChatGPT auth tokens have.
type ChatgptAuthTokensLoginAccountParams struct {
	// Access token (JWT) supplied by the client. This token is used for backend API requests and email extraction.
	AccessToken string `json:"accessToken"`
	// Workspace/account identifier supplied by the client.
	ChatgptAccountID string `json:"chatgptAccountId"`
	// Optional plan type supplied by the client.
	ChatgptPlanType *string `json:"chatgptPlanType,omitempty"`
}

type ChatgptDeviceCodeLoginAccountParams struct {
}

// LoginAccountResponse is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type LoginAccountResponse struct {
	// Tag is the value of the "type" property observed on decode.
	Tag               string
	AmazonBedrock     *AmazonBedrockLoginAccountResponse
	APIKey            *APIKeyLoginAccountResponse
	Chatgpt           *ChatgptLoginAccountResponse
	ChatgptAuthTokens *ChatgptAuthTokensLoginAccountResponse
	ChatgptDeviceCode *ChatgptDeviceCodeLoginAccountResponse
	raw               rawMessage
}

const (
	LoginAccountResponseTagAmazonBedrock     = "amazonBedrock"
	LoginAccountResponseTagAPIKey            = "apiKey"
	LoginAccountResponseTagChatgpt           = "chatgpt"
	LoginAccountResponseTagChatgptAuthTokens = "chatgptAuthTokens"
	LoginAccountResponseTagChatgptDeviceCode = "chatgptDeviceCode"
)

func (u *LoginAccountResponse) UnmarshalJSON(data []byte) error {
	*u = LoginAccountResponse{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "amazonBedrock":
		u.AmazonBedrock = new(AmazonBedrockLoginAccountResponse)
		return jsonUnmarshal(data, u.AmazonBedrock)
	case "apiKey":
		u.APIKey = new(APIKeyLoginAccountResponse)
		return jsonUnmarshal(data, u.APIKey)
	case "chatgpt":
		u.Chatgpt = new(ChatgptLoginAccountResponse)
		return jsonUnmarshal(data, u.Chatgpt)
	case "chatgptAuthTokens":
		u.ChatgptAuthTokens = new(ChatgptAuthTokensLoginAccountResponse)
		return jsonUnmarshal(data, u.ChatgptAuthTokens)
	case "chatgptDeviceCode":
		u.ChatgptDeviceCode = new(ChatgptDeviceCodeLoginAccountResponse)
		return jsonUnmarshal(data, u.ChatgptDeviceCode)
	}
	return nil
}

func (u LoginAccountResponse) MarshalJSON() ([]byte, error) {
	switch {
	case u.AmazonBedrock != nil:
		return marshalTagged("type", "amazonBedrock", u.AmazonBedrock)
	case u.APIKey != nil:
		return marshalTagged("type", "apiKey", u.APIKey)
	case u.Chatgpt != nil:
		return marshalTagged("type", "chatgpt", u.Chatgpt)
	case u.ChatgptAuthTokens != nil:
		return marshalTagged("type", "chatgptAuthTokens", u.ChatgptAuthTokens)
	case u.ChatgptDeviceCode != nil:
		return marshalTagged("type", "chatgptDeviceCode", u.ChatgptDeviceCode)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("LoginAccountResponse")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u LoginAccountResponse) Raw() []byte { return u.raw }

type AmazonBedrockLoginAccountResponse struct {
}

type APIKeyLoginAccountResponse struct {
}

type ChatgptLoginAccountResponse struct {
	// URL the client should open in a browser to initiate the OAuth flow.
	AuthURL string `json:"authUrl"`
	LoginID string `json:"loginId"`
}

type ChatgptAuthTokensLoginAccountResponse struct {
}

type ChatgptDeviceCodeLoginAccountResponse struct {
	LoginID string `json:"loginId"`
	// One-time code the user must enter after signing in.
	UserCode string `json:"userCode"`
	// URL the client should open in a browser to complete device code authorization.
	VerificationURL string `json:"verificationUrl"`
}

// McpServerElicitationRequestParams is an internally-tagged union (tag property "mode").
// Unknown variants decode without error: only Tag and Raw() are populated.
type McpServerElicitationRequestParams struct {
	// Tag is the value of the "mode" property observed on decode.
	Tag        string
	Form       *FormMcpServerElicitationRequestParams
	OpenaiForm *OpenaiFormMcpServerElicitationRequestParams
	URL        *URLMcpServerElicitationRequestParams
	raw        rawMessage
}

const (
	McpServerElicitationRequestParamsTagForm       = "form"
	McpServerElicitationRequestParamsTagOpenaiForm = "openai/form"
	McpServerElicitationRequestParamsTagURL        = "url"
)

func (u *McpServerElicitationRequestParams) UnmarshalJSON(data []byte) error {
	*u = McpServerElicitationRequestParams{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"mode"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "form":
		u.Form = new(FormMcpServerElicitationRequestParams)
		return jsonUnmarshal(data, u.Form)
	case "openai/form":
		u.OpenaiForm = new(OpenaiFormMcpServerElicitationRequestParams)
		return jsonUnmarshal(data, u.OpenaiForm)
	case "url":
		u.URL = new(URLMcpServerElicitationRequestParams)
		return jsonUnmarshal(data, u.URL)
	}
	return nil
}

func (u McpServerElicitationRequestParams) MarshalJSON() ([]byte, error) {
	switch {
	case u.Form != nil:
		return marshalTagged("mode", "form", u.Form)
	case u.OpenaiForm != nil:
		return marshalTagged("mode", "openai/form", u.OpenaiForm)
	case u.URL != nil:
		return marshalTagged("mode", "url", u.URL)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("McpServerElicitationRequestParams")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u McpServerElicitationRequestParams) Raw() []byte { return u.raw }

type FormMcpServerElicitationRequestParams struct {
	Meta            any                  `json:"_meta,omitempty"`
	Message         string               `json:"message"`
	RequestedSchema McpElicitationSchema `json:"requestedSchema"`
}

type OpenaiFormMcpServerElicitationRequestParams struct {
	Meta            any    `json:"_meta,omitempty"`
	Message         string `json:"message"`
	RequestedSchema any    `json:"requestedSchema"`
}

type URLMcpServerElicitationRequestParams struct {
	Meta          any    `json:"_meta,omitempty"`
	ElicitationID string `json:"elicitationId"`
	Message       string `json:"message"`
	URL           string `json:"url"`
}

// PatchChangeKind is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type PatchChangeKind struct {
	// Tag is the value of the "type" property observed on decode.
	Tag    string
	Add    *AddPatchChangeKind
	Delete *DeletePatchChangeKind
	Update *UpdatePatchChangeKind
	raw    rawMessage
}

const (
	PatchChangeKindTagAdd    = "add"
	PatchChangeKindTagDelete = "delete"
	PatchChangeKindTagUpdate = "update"
)

func (u *PatchChangeKind) UnmarshalJSON(data []byte) error {
	*u = PatchChangeKind{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "add":
		u.Add = new(AddPatchChangeKind)
		return jsonUnmarshal(data, u.Add)
	case "delete":
		u.Delete = new(DeletePatchChangeKind)
		return jsonUnmarshal(data, u.Delete)
	case "update":
		u.Update = new(UpdatePatchChangeKind)
		return jsonUnmarshal(data, u.Update)
	}
	return nil
}

func (u PatchChangeKind) MarshalJSON() ([]byte, error) {
	switch {
	case u.Add != nil:
		return marshalTagged("type", "add", u.Add)
	case u.Delete != nil:
		return marshalTagged("type", "delete", u.Delete)
	case u.Update != nil:
		return marshalTagged("type", "update", u.Update)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("PatchChangeKind")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u PatchChangeKind) Raw() []byte { return u.raw }

type AddPatchChangeKind struct {
}

type DeletePatchChangeKind struct {
}

type UpdatePatchChangeKind struct {
	MovePath *string `json:"move_path,omitempty"`
}

// SandboxPolicy is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type SandboxPolicy struct {
	// Tag is the value of the "type" property observed on decode.
	Tag              string
	DangerFullAccess *DangerFullAccessSandboxPolicy
	ExternalSandbox  *ExternalSandboxSandboxPolicy
	ReadOnly         *ReadOnlySandboxPolicy
	WorkspaceWrite   *WorkspaceWriteSandboxPolicy
	raw              rawMessage
}

const (
	SandboxPolicyTagDangerFullAccess = "dangerFullAccess"
	SandboxPolicyTagExternalSandbox  = "externalSandbox"
	SandboxPolicyTagReadOnly         = "readOnly"
	SandboxPolicyTagWorkspaceWrite   = "workspaceWrite"
)

func (u *SandboxPolicy) UnmarshalJSON(data []byte) error {
	*u = SandboxPolicy{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "dangerFullAccess":
		u.DangerFullAccess = new(DangerFullAccessSandboxPolicy)
		return jsonUnmarshal(data, u.DangerFullAccess)
	case "externalSandbox":
		u.ExternalSandbox = new(ExternalSandboxSandboxPolicy)
		return jsonUnmarshal(data, u.ExternalSandbox)
	case "readOnly":
		u.ReadOnly = new(ReadOnlySandboxPolicy)
		return jsonUnmarshal(data, u.ReadOnly)
	case "workspaceWrite":
		u.WorkspaceWrite = new(WorkspaceWriteSandboxPolicy)
		return jsonUnmarshal(data, u.WorkspaceWrite)
	}
	return nil
}

func (u SandboxPolicy) MarshalJSON() ([]byte, error) {
	switch {
	case u.DangerFullAccess != nil:
		return marshalTagged("type", "dangerFullAccess", u.DangerFullAccess)
	case u.ExternalSandbox != nil:
		return marshalTagged("type", "externalSandbox", u.ExternalSandbox)
	case u.ReadOnly != nil:
		return marshalTagged("type", "readOnly", u.ReadOnly)
	case u.WorkspaceWrite != nil:
		return marshalTagged("type", "workspaceWrite", u.WorkspaceWrite)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("SandboxPolicy")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u SandboxPolicy) Raw() []byte { return u.raw }

type DangerFullAccessSandboxPolicy struct {
}

type ExternalSandboxSandboxPolicy struct {
	NetworkAccess *NetworkAccess `json:"networkAccess,omitempty"`
}

type ReadOnlySandboxPolicy struct {
	NetworkAccess *bool `json:"networkAccess,omitempty"`
}

type WorkspaceWriteSandboxPolicy struct {
	ExcludeSlashTmp     *bool             `json:"excludeSlashTmp,omitempty"`
	ExcludeTmpdirEnvVar *bool             `json:"excludeTmpdirEnvVar,omitempty"`
	NetworkAccess       *bool             `json:"networkAccess,omitempty"`
	WritableRoots       []AbsolutePathBuf `json:"writableRoots,omitempty"`
}

// SessionSource is a mixed union: on the wire it is either a bare string
// (Unit) or a single-key object (one payload field set). Unknown variants
// decode without error and are retained in Raw().
type SessionSource struct {
	// Unit holds the bare-string variant value, if that form was used.
	Unit     string
	Custom   *string
	SubAgent *SubAgentSource
	raw      rawMessage
}

const (
	SessionSourceUnitAppServer = "appServer"
	SessionSourceUnitCli       = "cli"
	SessionSourceUnitExec      = "exec"
	SessionSourceUnitUnknown   = "unknown"
	SessionSourceUnitVscode    = "vscode"
)

func (u *SessionSource) UnmarshalJSON(data []byte) error {
	*u = SessionSource{}
	u.raw = append(rawMessage(nil), data...)
	if isJSONString(data) {
		return jsonUnmarshal(data, &u.Unit)
	}
	var obj map[string]rawMessage
	if err := jsonUnmarshal(data, &obj); err != nil {
		return err
	}
	if len(obj) != 1 {
		return nil
	}
	for key, payload := range obj {
		switch key {
		case "custom":
			u.Custom = new(string)
			return jsonUnmarshal(payload, u.Custom)
		case "subAgent":
			u.SubAgent = new(SubAgentSource)
			return jsonUnmarshal(payload, u.SubAgent)
		}
	}
	return nil
}

func (u SessionSource) MarshalJSON() ([]byte, error) {
	if u.Unit != "" {
		return jsonMarshal(u.Unit)
	}
	switch {
	case u.Custom != nil:
		return marshalKeyed("custom", u.Custom)
	case u.SubAgent != nil:
		return marshalKeyed("subAgent", u.SubAgent)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("SessionSource")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u SessionSource) Raw() []byte { return u.raw }

// SubAgentSource is a mixed union: on the wire it is either a bare string
// (Unit) or a single-key object (one payload field set). Unknown variants
// decode without error and are retained in Raw().
type SubAgentSource struct {
	// Unit holds the bare-string variant value, if that form was used.
	Unit        string
	Other       *string
	ThreadSpawn *SubAgentSourceThreadSpawn
	raw         rawMessage
}

const (
	SubAgentSourceUnitCompact             = "compact"
	SubAgentSourceUnitMemoryConsolidation = "memory_consolidation"
	SubAgentSourceUnitReview              = "review"
)

func (u *SubAgentSource) UnmarshalJSON(data []byte) error {
	*u = SubAgentSource{}
	u.raw = append(rawMessage(nil), data...)
	if isJSONString(data) {
		return jsonUnmarshal(data, &u.Unit)
	}
	var obj map[string]rawMessage
	if err := jsonUnmarshal(data, &obj); err != nil {
		return err
	}
	if len(obj) != 1 {
		return nil
	}
	for key, payload := range obj {
		switch key {
		case "other":
			u.Other = new(string)
			return jsonUnmarshal(payload, u.Other)
		case "thread_spawn":
			u.ThreadSpawn = new(SubAgentSourceThreadSpawn)
			return jsonUnmarshal(payload, u.ThreadSpawn)
		}
	}
	return nil
}

func (u SubAgentSource) MarshalJSON() ([]byte, error) {
	if u.Unit != "" {
		return jsonMarshal(u.Unit)
	}
	switch {
	case u.Other != nil:
		return marshalKeyed("other", u.Other)
	case u.ThreadSpawn != nil:
		return marshalKeyed("thread_spawn", u.ThreadSpawn)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("SubAgentSource")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u SubAgentSource) Raw() []byte { return u.raw }

// ThreadItem is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type ThreadItem struct {
	// Tag is the value of the "type" property observed on decode.
	Tag                 string
	AgentMessage        *AgentMessageThreadItem
	CollabAgentToolCall *CollabAgentToolCallThreadItem
	CommandExecution    *CommandExecutionThreadItem
	ContextCompaction   *ContextCompactionThreadItem
	DynamicToolCall     *DynamicToolCallThreadItem
	EnteredReviewMode   *EnteredReviewModeThreadItem
	ExitedReviewMode    *ExitedReviewModeThreadItem
	FileChange          *FileChangeThreadItem
	FunctionCallOutput  *FunctionCallOutputThreadItem
	HookPrompt          *HookPromptThreadItem
	ImageGeneration     *ImageGenerationThreadItem
	ImageView           *ImageViewThreadItem
	MCPToolCall         *McpToolCallThreadItem
	Plan                *PlanThreadItem
	Reasoning           *ReasoningThreadItem
	Sleep               *SleepThreadItem
	SubAgentActivity    *SubAgentActivityThreadItem
	UserMessage         *UserMessageThreadItem
	WebSearch           *WebSearchThreadItem
	raw                 rawMessage
}

const (
	ThreadItemTagAgentMessage        = "agentMessage"
	ThreadItemTagCollabAgentToolCall = "collabAgentToolCall"
	ThreadItemTagCommandExecution    = "commandExecution"
	ThreadItemTagContextCompaction   = "contextCompaction"
	ThreadItemTagDynamicToolCall     = "dynamicToolCall"
	ThreadItemTagEnteredReviewMode   = "enteredReviewMode"
	ThreadItemTagExitedReviewMode    = "exitedReviewMode"
	ThreadItemTagFileChange          = "fileChange"
	ThreadItemTagFunctionCallOutput  = "functionCallOutput"
	ThreadItemTagHookPrompt          = "hookPrompt"
	ThreadItemTagImageGeneration     = "imageGeneration"
	ThreadItemTagImageView           = "imageView"
	ThreadItemTagMCPToolCall         = "mcpToolCall"
	ThreadItemTagPlan                = "plan"
	ThreadItemTagReasoning           = "reasoning"
	ThreadItemTagSleep               = "sleep"
	ThreadItemTagSubAgentActivity    = "subAgentActivity"
	ThreadItemTagUserMessage         = "userMessage"
	ThreadItemTagWebSearch           = "webSearch"
)

func (u *ThreadItem) UnmarshalJSON(data []byte) error {
	*u = ThreadItem{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "agentMessage":
		u.AgentMessage = new(AgentMessageThreadItem)
		return jsonUnmarshal(data, u.AgentMessage)
	case "collabAgentToolCall":
		u.CollabAgentToolCall = new(CollabAgentToolCallThreadItem)
		return jsonUnmarshal(data, u.CollabAgentToolCall)
	case "commandExecution":
		u.CommandExecution = new(CommandExecutionThreadItem)
		return jsonUnmarshal(data, u.CommandExecution)
	case "contextCompaction":
		u.ContextCompaction = new(ContextCompactionThreadItem)
		return jsonUnmarshal(data, u.ContextCompaction)
	case "dynamicToolCall":
		u.DynamicToolCall = new(DynamicToolCallThreadItem)
		return jsonUnmarshal(data, u.DynamicToolCall)
	case "enteredReviewMode":
		u.EnteredReviewMode = new(EnteredReviewModeThreadItem)
		return jsonUnmarshal(data, u.EnteredReviewMode)
	case "exitedReviewMode":
		u.ExitedReviewMode = new(ExitedReviewModeThreadItem)
		return jsonUnmarshal(data, u.ExitedReviewMode)
	case "fileChange":
		u.FileChange = new(FileChangeThreadItem)
		return jsonUnmarshal(data, u.FileChange)
	case "functionCallOutput":
		u.FunctionCallOutput = new(FunctionCallOutputThreadItem)
		return jsonUnmarshal(data, u.FunctionCallOutput)
	case "hookPrompt":
		u.HookPrompt = new(HookPromptThreadItem)
		return jsonUnmarshal(data, u.HookPrompt)
	case "imageGeneration":
		u.ImageGeneration = new(ImageGenerationThreadItem)
		return jsonUnmarshal(data, u.ImageGeneration)
	case "imageView":
		u.ImageView = new(ImageViewThreadItem)
		return jsonUnmarshal(data, u.ImageView)
	case "mcpToolCall":
		u.MCPToolCall = new(McpToolCallThreadItem)
		return jsonUnmarshal(data, u.MCPToolCall)
	case "plan":
		u.Plan = new(PlanThreadItem)
		return jsonUnmarshal(data, u.Plan)
	case "reasoning":
		u.Reasoning = new(ReasoningThreadItem)
		return jsonUnmarshal(data, u.Reasoning)
	case "sleep":
		u.Sleep = new(SleepThreadItem)
		return jsonUnmarshal(data, u.Sleep)
	case "subAgentActivity":
		u.SubAgentActivity = new(SubAgentActivityThreadItem)
		return jsonUnmarshal(data, u.SubAgentActivity)
	case "userMessage":
		u.UserMessage = new(UserMessageThreadItem)
		return jsonUnmarshal(data, u.UserMessage)
	case "webSearch":
		u.WebSearch = new(WebSearchThreadItem)
		return jsonUnmarshal(data, u.WebSearch)
	}
	return nil
}

func (u ThreadItem) MarshalJSON() ([]byte, error) {
	switch {
	case u.AgentMessage != nil:
		return marshalTagged("type", "agentMessage", u.AgentMessage)
	case u.CollabAgentToolCall != nil:
		return marshalTagged("type", "collabAgentToolCall", u.CollabAgentToolCall)
	case u.CommandExecution != nil:
		return marshalTagged("type", "commandExecution", u.CommandExecution)
	case u.ContextCompaction != nil:
		return marshalTagged("type", "contextCompaction", u.ContextCompaction)
	case u.DynamicToolCall != nil:
		return marshalTagged("type", "dynamicToolCall", u.DynamicToolCall)
	case u.EnteredReviewMode != nil:
		return marshalTagged("type", "enteredReviewMode", u.EnteredReviewMode)
	case u.ExitedReviewMode != nil:
		return marshalTagged("type", "exitedReviewMode", u.ExitedReviewMode)
	case u.FileChange != nil:
		return marshalTagged("type", "fileChange", u.FileChange)
	case u.FunctionCallOutput != nil:
		return marshalTagged("type", "functionCallOutput", u.FunctionCallOutput)
	case u.HookPrompt != nil:
		return marshalTagged("type", "hookPrompt", u.HookPrompt)
	case u.ImageGeneration != nil:
		return marshalTagged("type", "imageGeneration", u.ImageGeneration)
	case u.ImageView != nil:
		return marshalTagged("type", "imageView", u.ImageView)
	case u.MCPToolCall != nil:
		return marshalTagged("type", "mcpToolCall", u.MCPToolCall)
	case u.Plan != nil:
		return marshalTagged("type", "plan", u.Plan)
	case u.Reasoning != nil:
		return marshalTagged("type", "reasoning", u.Reasoning)
	case u.Sleep != nil:
		return marshalTagged("type", "sleep", u.Sleep)
	case u.SubAgentActivity != nil:
		return marshalTagged("type", "subAgentActivity", u.SubAgentActivity)
	case u.UserMessage != nil:
		return marshalTagged("type", "userMessage", u.UserMessage)
	case u.WebSearch != nil:
		return marshalTagged("type", "webSearch", u.WebSearch)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("ThreadItem")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u ThreadItem) Raw() []byte { return u.raw }

type AgentMessageThreadItem struct {
	Delivery       *AgentMessageDelivery `json:"delivery,omitempty"`
	ID             string                `json:"id"`
	MemoryCitation *MemoryCitation       `json:"memoryCitation,omitempty"`
	Phase          *MessagePhase         `json:"phase,omitempty"`
	Text           string                `json:"text"`
}

type CollabAgentToolCallThreadItem struct {
	// Last known status of the target agents, when available.
	AgentsStates map[string]CollabAgentState `json:"agentsStates"`
	// Unique identifier for this collab tool call.
	ID string `json:"id"`
	// Model requested for the spawned agent, when applicable.
	Model *string `json:"model,omitempty"`
	// Prompt text sent as part of the collab tool call, when available.
	Prompt *string `json:"prompt,omitempty"`
	// Reasoning effort requested for the spawned agent, when applicable.
	ReasoningEffort *ReasoningEffort `json:"reasoningEffort,omitempty"`
	// Thread ID of the receiving agent, when applicable. In case of spawn operation, this corresponds to the newly spawned agent.
	ReceiverThreadIds []string `json:"receiverThreadIds"`
	// Thread ID of the agent issuing the collab request.
	SenderThreadID string `json:"senderThreadId"`
	// Current status of the collab tool call.
	Status CollabAgentToolCallStatus `json:"status"`
	// Name of the collab tool that was invoked.
	Tool CollabAgentTool `json:"tool"`
}

func (v CollabAgentToolCallThreadItem) MarshalJSON() ([]byte, error) {
	type plain CollabAgentToolCallThreadItem
	p := plain(v)
	if p.AgentsStates == nil {
		p.AgentsStates = map[string]CollabAgentState{}
	}
	if p.ReceiverThreadIds == nil {
		p.ReceiverThreadIds = []string{}
	}
	return jsonMarshal(p)
}

type CommandExecutionThreadItem struct {
	// The command's output, aggregated from stdout and stderr.
	AggregatedOutput *string `json:"aggregatedOutput,omitempty"`
	// The command to be executed.
	Command string `json:"command"`
	// A best-effort parsing of the command to understand the action(s) it will perform. This returns a list of CommandAction objects because a single shell command may be composed of many commands piped together.
	CommandActions []CommandAction `json:"commandActions"`
	// The command's working directory.
	Cwd LegacyAppPathString `json:"cwd"`
	// The duration of the command execution in milliseconds.
	DurationMs *int64 `json:"durationMs,omitempty"`
	// The command's exit code.
	ExitCode *int64 `json:"exitCode,omitempty"`
	ID       string `json:"id"`
	// Trusted first-party plugin id when this command resolves to one plugin script.
	PluginID *string `json:"pluginId,omitempty"`
	// Identifier for the underlying PTY process (when available).
	ProcessID *string `json:"processId,omitempty"`
	// Safe plugin-relative path when this command resolves to one plugin script.
	ScriptPath *string                 `json:"scriptPath,omitempty"`
	Source     *CommandExecutionSource `json:"source,omitempty"`
	Status     CommandExecutionStatus  `json:"status"`
}

func (v CommandExecutionThreadItem) MarshalJSON() ([]byte, error) {
	type plain CommandExecutionThreadItem
	p := plain(v)
	if p.CommandActions == nil {
		p.CommandActions = []CommandAction{}
	}
	return jsonMarshal(p)
}

type ContextCompactionThreadItem struct {
	ID string `json:"id"`
}

type DynamicToolCallThreadItem struct {
	Arguments    any                                `json:"arguments"`
	ContentItems []DynamicToolCallOutputContentItem `json:"contentItems,omitempty"`
	// The duration of the dynamic tool call in milliseconds.
	DurationMs *int64                `json:"durationMs,omitempty"`
	ID         string                `json:"id"`
	Namespace  *string               `json:"namespace,omitempty"`
	Status     DynamicToolCallStatus `json:"status"`
	Success    *bool                 `json:"success,omitempty"`
	Tool       string                `json:"tool"`
}

type EnteredReviewModeThreadItem struct {
	ID     string `json:"id"`
	Review string `json:"review"`
}

type ExitedReviewModeThreadItem struct {
	ID     string `json:"id"`
	Review string `json:"review"`
}

type FileChangeThreadItem struct {
	Changes []FileUpdateChange `json:"changes"`
	ID      string             `json:"id"`
	Status  PatchApplyStatus   `json:"status"`
}

func (v FileChangeThreadItem) MarshalJSON() ([]byte, error) {
	type plain FileChangeThreadItem
	p := plain(v)
	if p.Changes == nil {
		p.Changes = []FileUpdateChange{}
	}
	return jsonMarshal(p)
}

type FunctionCallOutputThreadItem struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Namespace *string    `json:"namespace,omitempty"`
	Output    rawMessage `json:"output"`
}

type HookPromptThreadItem struct {
	Fragments []HookPromptFragment `json:"fragments"`
	ID        string               `json:"id"`
}

func (v HookPromptThreadItem) MarshalJSON() ([]byte, error) {
	type plain HookPromptThreadItem
	p := plain(v)
	if p.Fragments == nil {
		p.Fragments = []HookPromptFragment{}
	}
	return jsonMarshal(p)
}

type ImageGenerationThreadItem struct {
	Failure               *ImageGenerationFailure `json:"failure,omitempty"`
	ID                    string                  `json:"id"`
	Result                string                  `json:"result"`
	RevisedPrompt         *string                 `json:"revisedPrompt,omitempty"`
	SavedPath             *AbsolutePathBuf        `json:"savedPath,omitempty"`
	Status                string                  `json:"status"`
	TransparentBackground *bool                   `json:"transparentBackground,omitempty"`
}

type ImageViewThreadItem struct {
	ID   string              `json:"id"`
	Path LegacyAppPathString `json:"path"`
}

type McpToolCallThreadItem struct {
	AppContext *McpToolCallAppContext `json:"appContext,omitempty"`
	Arguments  any                    `json:"arguments"`
	// The duration of the MCP tool call in milliseconds.
	DurationMs *int64            `json:"durationMs,omitempty"`
	Error      *McpToolCallError `json:"error,omitempty"`
	ID         string            `json:"id"`
	// Deprecated: use `appContext.resourceUri` instead.
	MCPAppResourceURI *string            `json:"mcpAppResourceUri,omitempty"`
	PluginID          *string            `json:"pluginId,omitempty"`
	ReadOnlyHint      *bool              `json:"readOnlyHint,omitempty"`
	Result            *McpToolCallResult `json:"result,omitempty"`
	Server            string             `json:"server"`
	Status            McpToolCallStatus  `json:"status"`
	Tool              string             `json:"tool"`
}

// EXPERIMENTAL - proposed plan item content. The completed plan item is authoritative and may not match the concatenation of `PlanDelta` text.
type PlanThreadItem struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type ReasoningThreadItem struct {
	Content []string `json:"content,omitempty"`
	ID      string   `json:"id"`
	Summary []string `json:"summary,omitempty"`
}

// Display item emitted by the interruptible `clock.sleep` tool.
type SleepThreadItem struct {
	DurationMs uint64 `json:"durationMs"`
	ID         string `json:"id"`
}

type SubAgentActivityThreadItem struct {
	AgentPath     string               `json:"agentPath"`
	AgentThreadID string               `json:"agentThreadId"`
	ID            string               `json:"id"`
	Kind          SubAgentActivityKind `json:"kind"`
}

type UserMessageThreadItem struct {
	ClientID *string     `json:"clientId,omitempty"`
	Content  []UserInput `json:"content"`
	ID       string      `json:"id"`
}

func (v UserMessageThreadItem) MarshalJSON() ([]byte, error) {
	type plain UserMessageThreadItem
	p := plain(v)
	if p.Content == nil {
		p.Content = []UserInput{}
	}
	return jsonMarshal(p)
}

type WebSearchThreadItem struct {
	Action *WebSearchAction `json:"action,omitempty"`
	ID     string           `json:"id"`
	Query  string           `json:"query"`
	// Structured search results returned out-of-band by standalone web search.
	Results []any `json:"results,omitempty"`
}

// ThreadStatus is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type ThreadStatus struct {
	// Tag is the value of the "type" property observed on decode.
	Tag         string
	Active      *ActiveThreadStatus
	Idle        *IdleThreadStatus
	NotLoaded   *NotLoadedThreadStatus
	SystemError *SystemErrorThreadStatus
	raw         rawMessage
}

const (
	ThreadStatusTagActive      = "active"
	ThreadStatusTagIdle        = "idle"
	ThreadStatusTagNotLoaded   = "notLoaded"
	ThreadStatusTagSystemError = "systemError"
)

func (u *ThreadStatus) UnmarshalJSON(data []byte) error {
	*u = ThreadStatus{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "active":
		u.Active = new(ActiveThreadStatus)
		return jsonUnmarshal(data, u.Active)
	case "idle":
		u.Idle = new(IdleThreadStatus)
		return jsonUnmarshal(data, u.Idle)
	case "notLoaded":
		u.NotLoaded = new(NotLoadedThreadStatus)
		return jsonUnmarshal(data, u.NotLoaded)
	case "systemError":
		u.SystemError = new(SystemErrorThreadStatus)
		return jsonUnmarshal(data, u.SystemError)
	}
	return nil
}

func (u ThreadStatus) MarshalJSON() ([]byte, error) {
	switch {
	case u.Active != nil:
		return marshalTagged("type", "active", u.Active)
	case u.Idle != nil:
		return marshalTagged("type", "idle", u.Idle)
	case u.NotLoaded != nil:
		return marshalTagged("type", "notLoaded", u.NotLoaded)
	case u.SystemError != nil:
		return marshalTagged("type", "systemError", u.SystemError)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("ThreadStatus")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u ThreadStatus) Raw() []byte { return u.raw }

type ActiveThreadStatus struct {
	ActiveFlags []ThreadActiveFlag `json:"activeFlags"`
}

func (v ActiveThreadStatus) MarshalJSON() ([]byte, error) {
	type plain ActiveThreadStatus
	p := plain(v)
	if p.ActiveFlags == nil {
		p.ActiveFlags = []ThreadActiveFlag{}
	}
	return jsonMarshal(p)
}

type IdleThreadStatus struct {
}

type NotLoadedThreadStatus struct {
}

type SystemErrorThreadStatus struct {
}

// UserInput is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type UserInput struct {
	// Tag is the value of the "type" property observed on decode.
	Tag        string
	Audio      *AudioUserInput
	Image      *ImageUserInput
	LocalAudio *LocalAudioUserInput
	LocalImage *LocalImageUserInput
	Mention    *MentionUserInput
	Skill      *SkillUserInput
	Text       *TextUserInput
	raw        rawMessage
}

const (
	UserInputTagAudio      = "audio"
	UserInputTagImage      = "image"
	UserInputTagLocalAudio = "localAudio"
	UserInputTagLocalImage = "localImage"
	UserInputTagMention    = "mention"
	UserInputTagSkill      = "skill"
	UserInputTagText       = "text"
)

func (u *UserInput) UnmarshalJSON(data []byte) error {
	*u = UserInput{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "audio":
		u.Audio = new(AudioUserInput)
		return jsonUnmarshal(data, u.Audio)
	case "image":
		u.Image = new(ImageUserInput)
		return jsonUnmarshal(data, u.Image)
	case "localAudio":
		u.LocalAudio = new(LocalAudioUserInput)
		return jsonUnmarshal(data, u.LocalAudio)
	case "localImage":
		u.LocalImage = new(LocalImageUserInput)
		return jsonUnmarshal(data, u.LocalImage)
	case "mention":
		u.Mention = new(MentionUserInput)
		return jsonUnmarshal(data, u.Mention)
	case "skill":
		u.Skill = new(SkillUserInput)
		return jsonUnmarshal(data, u.Skill)
	case "text":
		u.Text = new(TextUserInput)
		return jsonUnmarshal(data, u.Text)
	}
	return nil
}

func (u UserInput) MarshalJSON() ([]byte, error) {
	switch {
	case u.Audio != nil:
		return marshalTagged("type", "audio", u.Audio)
	case u.Image != nil:
		return marshalTagged("type", "image", u.Image)
	case u.LocalAudio != nil:
		return marshalTagged("type", "localAudio", u.LocalAudio)
	case u.LocalImage != nil:
		return marshalTagged("type", "localImage", u.LocalImage)
	case u.Mention != nil:
		return marshalTagged("type", "mention", u.Mention)
	case u.Skill != nil:
		return marshalTagged("type", "skill", u.Skill)
	case u.Text != nil:
		return marshalTagged("type", "text", u.Text)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("UserInput")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u UserInput) Raw() []byte { return u.raw }

type AudioUserInput struct {
	URL string `json:"url"`
}

type ImageUserInput struct {
	Detail *ImageDetail `json:"detail,omitempty"`
	URL    string       `json:"url"`
}

type LocalAudioUserInput struct {
	Path string `json:"path"`
}

type LocalImageUserInput struct {
	Detail *ImageDetail `json:"detail,omitempty"`
	Path   string       `json:"path"`
}

type MentionUserInput struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

type SkillUserInput struct {
	Name string `json:"name"`
	Path string `json:"path"`
}

type TextUserInput struct {
	Text string `json:"text"`
	// UI-defined spans within `text` used to render or persist special elements.
	TextElements []TextElement `json:"text_elements,omitempty"`
}

// WebSearchAction is an internally-tagged union (tag property "type").
// Unknown variants decode without error: only Tag and Raw() are populated.
type WebSearchAction struct {
	// Tag is the value of the "type" property observed on decode.
	Tag        string
	FindInPage *FindInPageWebSearchAction
	OpenPage   *OpenPageWebSearchAction
	Other      *OtherWebSearchAction
	Search     *SearchWebSearchAction
	raw        rawMessage
}

const (
	WebSearchActionTagFindInPage = "findInPage"
	WebSearchActionTagOpenPage   = "openPage"
	WebSearchActionTagOther      = "other"
	WebSearchActionTagSearch     = "search"
)

func (u *WebSearchAction) UnmarshalJSON(data []byte) error {
	*u = WebSearchAction{}
	u.raw = append(rawMessage(nil), data...)
	var probe struct {
		Tag string `json:"type"`
	}
	if err := jsonUnmarshal(data, &probe); err != nil {
		return err
	}
	u.Tag = probe.Tag
	switch probe.Tag {
	case "findInPage":
		u.FindInPage = new(FindInPageWebSearchAction)
		return jsonUnmarshal(data, u.FindInPage)
	case "openPage":
		u.OpenPage = new(OpenPageWebSearchAction)
		return jsonUnmarshal(data, u.OpenPage)
	case "other":
		u.Other = new(OtherWebSearchAction)
		return jsonUnmarshal(data, u.Other)
	case "search":
		u.Search = new(SearchWebSearchAction)
		return jsonUnmarshal(data, u.Search)
	}
	return nil
}

func (u WebSearchAction) MarshalJSON() ([]byte, error) {
	switch {
	case u.FindInPage != nil:
		return marshalTagged("type", "findInPage", u.FindInPage)
	case u.OpenPage != nil:
		return marshalTagged("type", "openPage", u.OpenPage)
	case u.Other != nil:
		return marshalTagged("type", "other", u.Other)
	case u.Search != nil:
		return marshalTagged("type", "search", u.Search)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return nil, errNoVariant("WebSearchAction")
}

// Raw returns the original JSON for this union value, if it was decoded.
func (u WebSearchAction) Raw() []byte { return u.raw }

type FindInPageWebSearchAction struct {
	Pattern *string `json:"pattern,omitempty"`
	URL     *string `json:"url,omitempty"`
}

type OpenPageWebSearchAction struct {
	URL *string `json:"url,omitempty"`
}

type OtherWebSearchAction struct {
}

type SearchWebSearchAction struct {
	Queries []string `json:"queries,omitempty"`
	Query   *string  `json:"query,omitempty"`
}
