DROP TABLE IF EXISTS public.workspace_dependency_catalogs;
DROP TABLE IF EXISTS public.workspace_dependency_definitions;
ALTER TABLE IF EXISTS bot_channel_routes DROP CONSTRAINT IF EXISTS fk_bot_channel_routes_active_session;
ALTER TABLE IF EXISTS bot_history_messages DROP CONSTRAINT IF EXISTS fk_compact_id;

DROP VIEW IF EXISTS public.team_accounts CASCADE;
DO $drop_team_members_guard$
BEGIN
  IF to_regclass('public.team_members') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS team_members_last_active_admin_guard ON public.team_members;
  END IF;
END
$drop_team_members_guard$;
DROP FUNCTION IF EXISTS public.memoh_guard_last_active_team_admin();

DROP TABLE IF EXISTS memory_edges CASCADE;
DROP TABLE IF EXISTS memory_nodes CASCADE;
DROP TABLE IF EXISTS bot_user_grants CASCADE;
DROP TABLE IF EXISTS user_provider_oauth_tokens CASCADE;
DROP TABLE IF EXISTS provider_oauth_tokens CASCADE;
DROP TABLE IF EXISTS email_outbox CASCADE;
DROP TABLE IF EXISTS bot_email_bindings CASCADE;
DROP TABLE IF EXISTS email_oauth_tokens CASCADE;
DROP TABLE IF EXISTS email_providers CASCADE;
DROP TABLE IF EXISTS schedule_logs CASCADE;
DROP TABLE IF EXISTS bot_history_message_compacts CASCADE;
DROP TABLE IF EXISTS bot_history_message_assets CASCADE;
DROP TABLE IF EXISTS media_assets CASCADE;
DROP TABLE IF EXISTS bot_storage_bindings CASCADE;
DROP TABLE IF EXISTS storage_providers CASCADE;
DROP TABLE IF EXISTS schedule CASCADE;
DROP TABLE IF EXISTS lifecycle_events CASCADE;
DROP TABLE IF EXISTS container_versions CASCADE;
DROP TABLE IF EXISTS snapshots CASCADE;
DROP TABLE IF EXISTS bot_workspace_resource_limits CASCADE;
DROP TABLE IF EXISTS containers CASCADE;
DROP TABLE IF EXISTS user_input_requests CASCADE;
DROP TABLE IF EXISTS tool_approval_requests CASCADE;
DROP VIEW IF EXISTS bot_visible_history_messages CASCADE;
DROP TABLE IF EXISTS bot_history_messages CASCADE;
DROP TABLE IF EXISTS bot_session_events CASCADE;
DROP TABLE IF EXISTS bot_session_discuss_cursors CASCADE;
DROP TABLE IF EXISTS agent_session_state_lines CASCADE;
DROP TABLE IF EXISTS agent_session_publications CASCADE;
DROP TABLE IF EXISTS agent_session_states CASCADE;
DROP TABLE IF EXISTS session_runs CASCADE;
DROP TABLE IF EXISTS bot_sessions CASCADE;
DROP SEQUENCE IF EXISTS session_runtime_fencing_token_seq;
DROP SEQUENCE IF EXISTS bot_session_event_cursor_seq;
DROP TABLE IF EXISTS bot_channel_routes CASCADE;
DROP TABLE IF EXISTS channel_identity_bind_codes CASCADE;
DROP TABLE IF EXISTS bot_channel_configs CASCADE;
DROP TABLE IF EXISTS mcp_oauth_tokens CASCADE;
DROP TABLE IF EXISTS mcp_connections CASCADE;
DROP TABLE IF EXISTS channel_link_codes CASCADE;
DROP TABLE IF EXISTS user_channel_identity_bindings CASCADE;
DROP TABLE IF EXISTS bot_channel_admins CASCADE;
DROP TABLE IF EXISTS bot_acl_rules CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS bot_inbox CASCADE;
DROP TABLE IF EXISTS subagents CASCADE;
DROP TABLE IF EXISTS bot_preauth_keys CASCADE;
DROP TABLE IF EXISTS bot_members CASCADE;
DROP TABLE IF EXISTS bot_remote_runtime_bindings CASCADE;
DROP TABLE IF EXISTS bot_dependency_installations CASCADE;
DROP TABLE IF EXISTS bot_skill_package_installations CASCADE;
DROP TABLE IF EXISTS user_runtimes CASCADE;
DROP TABLE IF EXISTS connectors CASCADE;
DROP TABLE IF EXISTS bots CASCADE;
DROP TABLE IF EXISTS browser_contexts CASCADE;
DROP TABLE IF EXISTS tts_models CASCADE;
DROP TABLE IF EXISTS tts_providers CASCADE;
DROP TABLE IF EXISTS memory_providers CASCADE;
DROP TABLE IF EXISTS model_variants CASCADE;
DROP TABLE IF EXISTS models CASCADE;
DROP TABLE IF EXISTS llm_provider_oauth_tokens CASCADE;
DROP TABLE IF EXISTS llm_providers CASCADE;
DROP TABLE IF EXISTS fetch_providers CASCADE;
DROP TABLE IF EXISTS search_providers CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS user_channel_bindings CASCADE;
DROP TABLE IF EXISTS channel_identities CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP FUNCTION IF EXISTS public.memoh_current_team_id() CASCADE;
DROP TYPE IF EXISTS user_role;

DROP TABLE IF EXISTS template.provider_template_models CASCADE;
DROP TABLE IF EXISTS template.provider_templates CASCADE;
DROP SCHEMA IF EXISTS template;
