package protocolgen

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// Generate produces the generated protocol source files, keyed by file name.
// Output is deterministic for a given schema snapshot and subset config.
func Generate() (map[string][]byte, error) {
	c, err := loadCorpus()
	if err != nil {
		return nil, err
	}
	defs, err := closure(c)
	if err != nil {
		return nil, err
	}
	g := newGenerator(c, defs)

	var types, unions, methods strings.Builder

	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)

	emitOne := func(cls *classified) error {
		switch cls.kind {
		case kindMethodUnion, kindHandWritten:
			return nil
		case kindStruct:
			return g.emitStruct(&types, cls.name, cls.schema, nil)
		case kindEnum:
			return g.emitEnum(&types, cls)
		case kindAlias, kindArrayAlias, kindMapAlias, kindOpaqueUnion:
			return g.emitAlias(&types, cls)
		case kindTaggedUnion:
			return g.emitTaggedUnion(&unions, cls)
		case kindMixedUnion:
			return g.emitMixedUnion(&unions, cls)
		}
		return fmt.Errorf("definition %q: unknown kind", cls.name)
	}

	for _, name := range names {
		if err := emitOne(defs[name]); err != nil {
			return nil, err
		}
	}
	// Emitting definitions can synthesize types for inline schemas; emitting
	// those can synthesize more, so drain the queue.
	for i := 0; i < len(g.extraNames); i++ {
		if err := emitOne(g.extra[g.extraNames[i]]); err != nil {
			return nil, err
		}
	}

	if err := g.emitMethods(&methods); err != nil {
		return nil, err
	}

	version, err := snapshotVersion()
	if err != nil {
		return nil, err
	}
	header := fmt.Sprintf(`// Code generated by gen-codex-protocol from the codex app-server v2 JSON
// Schema snapshot (codex-cli %s). DO NOT EDIT.
//
// Regenerate with `+"`mise run codex-protocol-generate`"+`; refresh the snapshot
// itself with `+"`mise run codex-schema-sync`"+`.

package protocol

`, version)

	files := map[string][]byte{}
	for name, body := range map[string]*strings.Builder{
		"types.gen.go":   &types,
		"unions.gen.go":  &unions,
		"methods.gen.go": &methods,
	} {
		formatted, err := format.Source([]byte(header + body.String()))
		if err != nil {
			return nil, fmt.Errorf("gofmt %s: %w", name, err)
		}
		files[name] = formatted
	}
	return files, nil
}

// snapshotVersion reads the pinned codex version from schema/VERSION.json.
func snapshotVersion() (string, error) {
	raw, err := schemaFS.ReadFile("schema/VERSION.json")
	if err != nil {
		return "", err
	}
	var v struct {
		CodexVersion string `json:"codexVersion"`
	}
	if err := json.Unmarshal(raw, &v); err != nil {
		return "", fmt.Errorf("schema/VERSION.json: %w", err)
	}
	if v.CodexVersion == "" {
		return "", errors.New("schema/VERSION.json: missing codexVersion")
	}
	return v.CodexVersion, nil
}
